using Xunit;

namespace CommunityToolkit.Maui.SourceGenerators.Internal.UnitTests.AttachedBindablePropertySourceGeneratorTests;

public class EdgeCaseTests : BaseAttachedBindablePropertyAttributeSourceGeneratorTest
{
    [Fact]
    public async Task GenerateAttachedBindableProperty_PropertyIsByteEnum_GeneratesCorrectCode()
    {
        const string source =
            /* language=C#-test */
            //lang=csharp
            $$"""
            using CommunityToolkit.Maui;
            using Microsoft.Maui.Controls;

            namespace {{defaultTestNamespace}};

            public partial class {{defaultTestClassName}} : View
            {
                [AttachedBindableProperty]
                public partial Status InvoiceStatus { get; set; } = Status.Approved;
            }
            
            public enum Status : byte
            {
                Pending = 0,
                Approved = 1,
                Rejected = 2
            }
            """;

        const string expectedGenerated =
            /* language=C#-test */
            //lang=csharp
            $$"""
            // <auto-generated>
            // See: CommunityToolkit.Maui.SourceGenerators.Internal.AttachedBindablePropertySourceGenerator
            #pragma warning disable
            #nullable enable
            using global::Microsoft.Maui.Controls;

            namespace {{defaultTestNamespace}};
            public partial class {{defaultTestClassName}}
            {
                /// <summary>
                /// Backing BindableProperty for the <see cref = "InvoiceStatus"/> property.
                /// </summary>
                public static readonly global::Microsoft.Maui.Controls.BindableProperty InvoiceStatusProperty = global::Microsoft.Maui.Controls.BindableProperty.CreateAttached("InvoiceStatus", typeof(TestNamespace.Status), typeof({{defaultTestNamespace}}.{{defaultTestClassName}}), null, Microsoft.Maui.Controls.BindingMode.OneWay, null, null, null, null, __{{defaultTestClassName}}BindablePropertyInitHelpers.CreateDefaultInvoiceStatus);
                public partial TestNamespace.Status InvoiceStatus { get => __{{defaultTestClassName}}BindablePropertyInitHelpers.IsInitializingInvoiceStatus ? field : (TestNamespace.Status)GetValue(InvoiceStatusProperty); set => SetValue(InvoiceStatusProperty, value); }

                public static TestNamespace.Status GetInvoiceStatus(BindableObject view) => (TestNamespace.Status)view.GetValue(InvoiceStatusProperty);
                public static void SetInvoiceStatus(BindableObject view, TestNamespace.Status value) => view.SetValue(InvoiceStatusProperty, value);
            }

            file static class __{{defaultTestClassName}}BindablePropertyInitHelpers
            {
                public static bool IsInitializingInvoiceStatus = false;
                public static object CreateDefaultInvoiceStatus(BindableObject bindable)
                {
                    IsInitializingInvoiceStatus = true;
                    object defaultValue;
                    if (bindable is TestView inst)
                    {
                        defaultValue = ((TestView)bindable).InvoiceStatus;
                    }
                    else
                    {
                        defaultValue = default(TestNamespace.Status);
                    }
            
                    IsInitializingInvoiceStatus = false;
                    return defaultValue;
                }
            }
            """;

        await VerifyAttachedSourceGeneratorAsync(source, expectedGenerated);
    }

    [Fact]
    public async Task GenerateAttachedBindableProperty_ArrayTypes_GeneratesCorrectCode()
    {
        const string source =
            /* language=C#-test */
            //lang=csharp
            $$"""
            using CommunityToolkit.Maui;
            using Microsoft.Maui.Controls;

            namespace {{defaultTestNamespace}};

            public partial class {{defaultTestClassName}} : View
            {
                [AttachedBindableProperty]
                public partial string[] StringArray { get; set; }

                [AttachedBindableProperty]
                public partial int[,] MultiDimensionalArray { get; set; }

                [AttachedBindableProperty]
                public partial byte[][] JaggedArray { get; set; }
            }
            """;

        const string expectedGenerated =
            /* language=C#-test */
            //lang=csharp
            $$"""
            // <auto-generated>
            // See: CommunityToolkit.Maui.SourceGenerators.Internal.AttachedBindablePropertySourceGenerator
            #pragma warning disable
            #nullable enable
            using global::Microsoft.Maui.Controls;

            namespace {{defaultTestNamespace}};
            public partial class {{defaultTestClassName}}
            {
                /// <summary>
                /// Backing BindableProperty for the <see cref = "StringArray"/> property.
                /// </summary>
                public static readonly global::Microsoft.Maui.Controls.BindableProperty StringArrayProperty = global::Microsoft.Maui.Controls.BindableProperty.CreateAttached("StringArray", typeof(string[]), typeof({{defaultTestNamespace}}.{{defaultTestClassName}}), null, Microsoft.Maui.Controls.BindingMode.OneWay, null, null, null, null, null);
                public partial string[] StringArray { get => (string[])GetValue(StringArrayProperty); set => SetValue(StringArrayProperty, value); }

                public static string[] GetStringArray(BindableObject view) => (string[])view.GetValue(StringArrayProperty);
                public static void SetStringArray(BindableObject view, string[] value) => view.SetValue(StringArrayProperty, value);
                /// <summary>
                /// Backing BindableProperty for the <see cref = "MultiDimensionalArray"/> property.
                /// </summary>
                public static readonly global::Microsoft.Maui.Controls.BindableProperty MultiDimensionalArrayProperty = global::Microsoft.Maui.Controls.BindableProperty.CreateAttached("MultiDimensionalArray", typeof(int[, ]), typeof({{defaultTestNamespace}}.{{defaultTestClassName}}), null, Microsoft.Maui.Controls.BindingMode.OneWay, null, null, null, null, null);
                public partial int[, ] MultiDimensionalArray { get => (int[, ])GetValue(MultiDimensionalArrayProperty); set => SetValue(MultiDimensionalArrayProperty, value); }

                public static int[, ] GetMultiDimensionalArray(BindableObject view) => (int[, ])view.GetValue(MultiDimensionalArrayProperty);
                public static void SetMultiDimensionalArray(BindableObject view, int[, ] value) => view.SetValue(MultiDimensionalArrayProperty, value);
                /// <summary>
                /// Backing BindableProperty for the <see cref = "JaggedArray"/> property.
                /// </summary>
                public static readonly global::Microsoft.Maui.Controls.BindableProperty JaggedArrayProperty = global::Microsoft.Maui.Controls.BindableProperty.CreateAttached("JaggedArray", typeof(byte[][]), typeof({{defaultTestNamespace}}.{{defaultTestClassName}}), null, Microsoft.Maui.Controls.BindingMode.OneWay, null, null, null, null, null);
                public partial byte[][] JaggedArray { get => (byte[][])GetValue(JaggedArrayProperty); set => SetValue(JaggedArrayProperty, value); }

                public static byte[][] GetJaggedArray(BindableObject view) => (byte[][])view.GetValue(JaggedArrayProperty);
                public static void SetJaggedArray(BindableObject view, byte[][] value) => view.SetValue(JaggedArrayProperty, value);
            }
            """;

        await VerifyAttachedSourceGeneratorAsync(source, expectedGenerated);
    }
}
