using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Testing;
using Microsoft.CodeAnalysis.Testing;
using Xunit;

namespace CommunityToolkit.Maui.SourceGenerators.Internal.UnitTests.AttachedBindablePropertySourceGeneratorTests;

public class IntegrationTests : BaseAttachedBindablePropertyAttributeSourceGeneratorTest
{
    [Fact]
    public async Task GenerateAttachedBindableProperty_Basic_GeneratesCorrectCode()
    {
        const string source =
            /* language=C#-test */
            //lang=csharp
            $$"""
            using CommunityToolkit.Maui;
            using Microsoft.Maui.Controls;

            namespace TestNamespace;

            public partial class TestView : View
            {
                [AttachedBindableProperty]
                public partial string Text { get; set; }
            }
            """;

                const string expectedGenerated =
            /* language=C#-test */
            //lang=csharp
            $$"""
            // <auto-generated>
            // See: CommunityToolkit.Maui.SourceGenerators.Internal.AttachedBindablePropertySourceGenerator
            #pragma warning disable
            #nullable enable
            using global::Microsoft.Maui.Controls;

            namespace TestNamespace;
            public partial class TestView
            {
                /// <summary>
                /// Backing BindableProperty for the <see cref = "Text"/> property.
                /// </summary>
                public static readonly global::Microsoft.Maui.Controls.BindableProperty TextProperty = global::Microsoft.Maui.Controls.BindableProperty.CreateAttached("Text", typeof(string), typeof(TestNamespace.TestView), null, Microsoft.Maui.Controls.BindingMode.OneWay, null, null, null, null, null);
                public partial string Text { get => (string)GetValue(TextProperty); set => SetValue(TextProperty, value); }

                public static string GetText(BindableObject view) => (string)view.GetValue(TextProperty);
                public static void SetText(BindableObject view, string value) => view.SetValue(TextProperty, value);
            }
            """;

        await VerifyAttachedSourceGeneratorAsync(source, expectedGenerated);
    }
}
