using Xunit;

namespace CommunityToolkit.Maui.MediaElement.SourceGenerators.UnitTests.AndroidMediaElementServiceConfigurationGeneratorTests;

/// <summary>
/// Unit tests for AndroidMediaElementServiceConfigurationGenerator to verify that the generator
/// correctly detects when UseMauiCommunityToolkitMediaElement is called with isAndroidForegroundServiceEnabled set to true
/// and generates the appropriate AndroidMediaElementServiceConfiguration.g.cs file.
/// </summary>
public class AndroidMediaElementForegroundServiceConfigurationGenerator_UseMauiCommunityToolkitMediaElementTests : BaseAndroidMediaElementForegroundServiceConfigurationGeneratorTest
{
	[Fact]
	public async Task GenerateConfiguration_WhenUseMauiCommunityToolkitMediaElementCalledWithTrue_GeneratesCorrectCode()
	{
		const string source =
			/* language=C#-test */
			$$"""
			using System;
			using CommunityToolkit.Maui.Core;
			using Microsoft.Maui.Hosting;

			namespace {{defaultTestNamespace}};

			public class MediaElementOptions
			{
				internal static bool IsAndroidForegroundServiceEnabled { get; private set; } = false;

				public void SetIsAndroidForegroundServiceEnabled(bool isEnabled)
				{
					IsAndroidForegroundServiceEnabled = isEnabled;
				}
			}

			public static class AppBuilderExtensions
			{
				public static MauiAppBuilder UseMauiCommunityToolkitMediaElement(
					this MauiAppBuilder builder,
					bool isAndroidForegroundServiceEnabled,
					Action<MediaElementOptions>? options = null)
				{
					var mediaElementOptions = new MediaElementOptions();
					options?.Invoke(mediaElementOptions);
					mediaElementOptions.SetIsAndroidForegroundServiceEnabled(isAndroidForegroundServiceEnabled);
					return builder;
				}
			}

			public class MauiProgram
			{
				public static MauiApp CreateMauiApp()
				{
					var builder = MauiApp.CreateBuilder();
					builder.UseMauiCommunityToolkitMediaElement(isAndroidForegroundServiceEnabled: true);
					return builder.Build();
				}
			}
			""";

		const string expectedGenerated =
			/* language=C#-test */
			"""
			// <auto-generated>
			// See: CommunityToolkit.Maui.MediaElement.SourceGenerators.AndroidMediaElementServiceConfigurationGenerator
			// This file provides assembly-level Android permissions and service attributes
			// when Android Foreground Service is enabled for MediaElement.

			#pragma warning disable
			#nullable enable

			#if ANDROID
			using Android.App;

			[assembly: UsesPermission(Android.Manifest.Permission.ForegroundServiceMediaPlayback)]
			[assembly: UsesPermission(Android.Manifest.Permission.ForegroundService)]
			[assembly: UsesPermission(Android.Manifest.Permission.MediaContentControl)]
			[assembly: UsesPermission(Android.Manifest.Permission.PostNotifications)]

			namespace CommunityToolkit.Maui.Android;

			/// <summary>
			/// Auto-generated configuration for Android MediaElement Service.
			/// </summary>
			/// <remarks>
			/// This file is auto-generated and provides assembly-level permissions
			/// for MediaElement when <see cref="CommunityToolkit.Maui.Core.MediaElementOptions.IsAndroidForegroundServiceEnabled"/> is enabled
			/// or when <see cref="UseMauiCommunityToolkitMediaElement(Microsoft.Maui.MauiAppBuilder, bool, System.Action{CommunityToolkit.Maui.Core.MediaElementOptions})"/>
			/// is called with <c>isAndroidForegroundServiceEnabled</c> set to <c>true</c>.
			/// </remarks>
			internal static class AndroidMediaElementServiceConfiguration
			{
				/// <summary>
				/// Indicates that Android MediaElement Service configuration is required.
				/// </summary>
				public const bool IsRequired = true;
			}
			#endif
			""";

		await VerifySourceGeneratorAsync(source, expectedGenerated);
	}

	[Fact]
	public async Task GenerateConfiguration_WhenUseMauiCommunityToolkitMediaElementCalledWithFalse_GeneratesNoCode()
	{
		const string source =
			/* language=C#-test */
			$$"""
			using System;
			using CommunityToolkit.Maui.Core;
			using Microsoft.Maui.Hosting;

			namespace {{defaultTestNamespace}};

			public class MediaElementOptions
			{
				internal static bool IsAndroidForegroundServiceEnabled { get; private set; } = false;

				public void SetIsAndroidForegroundServiceEnabled(bool isEnabled)
				{
					IsAndroidForegroundServiceEnabled = isEnabled;
				}
			}

			public static class AppBuilderExtensions
			{
				public static MauiAppBuilder UseMauiCommunityToolkitMediaElement(
					this MauiAppBuilder builder,
					bool isAndroidForegroundServiceEnabled,
					Action<MediaElementOptions>? options = null)
				{
					var mediaElementOptions = new MediaElementOptions();
					options?.Invoke(mediaElementOptions);
					mediaElementOptions.SetIsAndroidForegroundServiceEnabled(isAndroidForegroundServiceEnabled);
					return builder;
				}
			}

			public class MauiProgram
			{
				public static MauiApp CreateMauiApp()
				{
					var builder = MauiApp.CreateBuilder();
					builder.UseMauiCommunityToolkitMediaElement(isAndroidForegroundServiceEnabled: false);
					return builder.Build();
				}
			}
			""";

		await VerifySourceGeneratorAsync(source);
	}

	[Fact]
	public async Task GenerateConfiguration_WhenUseMauiCommunityToolkitMediaElementCalledWithTrueAndOptions_GeneratesCorrectCode()
	{
		const string source =
			/* language=C#-test */
			$$"""
			using System;
			using CommunityToolkit.Maui.Core;
			using Microsoft.Maui.Hosting;

			namespace {{defaultTestNamespace}};

			public class MediaElementOptions
			{
				internal static bool IsAndroidForegroundServiceEnabled { get; private set; } = false;

				public void SetIsAndroidForegroundServiceEnabled(bool isEnabled)
				{
					IsAndroidForegroundServiceEnabled = isEnabled;
				}
			}

			public static class AppBuilderExtensions
			{
				public static MauiAppBuilder UseMauiCommunityToolkitMediaElement(
					this MauiAppBuilder builder,
					bool isAndroidForegroundServiceEnabled,
					Action<MediaElementOptions>? options = null)
				{
					var mediaElementOptions = new MediaElementOptions();
					options?.Invoke(mediaElementOptions);
					mediaElementOptions.SetIsAndroidForegroundServiceEnabled(isAndroidForegroundServiceEnabled);
					return builder;
				}
			}

			public class MauiProgram
			{
				public static MauiApp CreateMauiApp()
				{
					var builder = MauiApp.CreateBuilder();
					builder.UseMauiCommunityToolkitMediaElement(
						isAndroidForegroundServiceEnabled: true,
						options: static opts =>
						{
							// Configure options here
						});
					return builder.Build();
				}
			}
			""";

		const string expectedGenerated =
			/* language=C#-test */
			"""
			// <auto-generated>
			// See: CommunityToolkit.Maui.MediaElement.SourceGenerators.AndroidMediaElementServiceConfigurationGenerator
			// This file provides assembly-level Android permissions and service attributes
			// when Android Foreground Service is enabled for MediaElement.

			#pragma warning disable
			#nullable enable

			#if ANDROID
			using Android.App;

			[assembly: UsesPermission(Android.Manifest.Permission.ForegroundServiceMediaPlayback)]
			[assembly: UsesPermission(Android.Manifest.Permission.ForegroundService)]
			[assembly: UsesPermission(Android.Manifest.Permission.MediaContentControl)]
			[assembly: UsesPermission(Android.Manifest.Permission.PostNotifications)]

			namespace CommunityToolkit.Maui.Android;

			/// <summary>
			/// Auto-generated configuration for Android MediaElement Service.
			/// </summary>
			/// <remarks>
			/// This file is auto-generated and provides assembly-level permissions
			/// for MediaElement when <see cref="CommunityToolkit.Maui.Core.MediaElementOptions.IsAndroidForegroundServiceEnabled"/> is enabled
			/// or when <see cref="UseMauiCommunityToolkitMediaElement(Microsoft.Maui.MauiAppBuilder, bool, System.Action{CommunityToolkit.Maui.Core.MediaElementOptions})"/>
			/// is called with <c>isAndroidForegroundServiceEnabled</c> set to <c>true</c>.
			/// </remarks>
			internal static class AndroidMediaElementServiceConfiguration
			{
				/// <summary>
				/// Indicates that Android MediaElement Service configuration is required.
				/// </summary>
				public const bool IsRequired = true;
			}
			#endif
			""";

		await VerifySourceGeneratorAsync(source, expectedGenerated);
	}

	[Fact]
	public async Task GenerateConfiguration_WhenUseMauiCommunityToolkitMediaElementCalledWithBoolVariableTrue_GeneratesCorrectCode()
	{
		const string source =
			/* language=C#-test */
			$$"""
			using System;
			using CommunityToolkit.Maui.Core;
			using Microsoft.Maui.Hosting;

			namespace {{defaultTestNamespace}};

			public class MediaElementOptions
			{
				internal static bool IsAndroidForegroundServiceEnabled { get; private set; } = false;

				public void SetIsAndroidForegroundServiceEnabled(bool isEnabled)
				{
					IsAndroidForegroundServiceEnabled = isEnabled;
				}
			}

			public static class AppBuilderExtensions
			{
				public static MauiAppBuilder UseMauiCommunityToolkitMediaElement(
					this MauiAppBuilder builder,
					bool isAndroidForegroundServiceEnabled,
					Action<MediaElementOptions>? options = null)
				{
					var mediaElementOptions = new MediaElementOptions();
					options?.Invoke(mediaElementOptions);
					mediaElementOptions.SetIsAndroidForegroundServiceEnabled(isAndroidForegroundServiceEnabled);
					return builder;
				}
			}

			public class MauiProgram
			{
				public static MauiApp CreateMauiApp()
				{
					var builder = MauiApp.CreateBuilder();
					const bool enableForegroundService = true;
					builder.UseMauiCommunityToolkitMediaElement(isAndroidForegroundServiceEnabled: enableForegroundService);
					return builder.Build();
				}
			}
			""";

		const string expectedGenerated =
			/* language=C#-test */
			"""
			// <auto-generated>
			// See: CommunityToolkit.Maui.MediaElement.SourceGenerators.AndroidMediaElementServiceConfigurationGenerator
			// This file provides assembly-level Android permissions and service attributes
			// when Android Foreground Service is enabled for MediaElement.

			#pragma warning disable
			#nullable enable

			#if ANDROID
			using Android.App;

			[assembly: UsesPermission(Android.Manifest.Permission.ForegroundServiceMediaPlayback)]
			[assembly: UsesPermission(Android.Manifest.Permission.ForegroundService)]
			[assembly: UsesPermission(Android.Manifest.Permission.MediaContentControl)]
			[assembly: UsesPermission(Android.Manifest.Permission.PostNotifications)]

			namespace CommunityToolkit.Maui.Android;

			/// <summary>
			/// Auto-generated configuration for Android MediaElement Service.
			/// </summary>
			/// <remarks>
			/// This file is auto-generated and provides assembly-level permissions
			/// for MediaElement when <see cref="CommunityToolkit.Maui.Core.MediaElementOptions.IsAndroidForegroundServiceEnabled"/> is enabled
			/// or when <see cref="UseMauiCommunityToolkitMediaElement(Microsoft.Maui.MauiAppBuilder, bool, System.Action{CommunityToolkit.Maui.Core.MediaElementOptions})"/>
			/// is called with <c>isAndroidForegroundServiceEnabled</c> set to <c>true</c>.
			/// </remarks>
			internal static class AndroidMediaElementServiceConfiguration
			{
				/// <summary>
				/// Indicates that Android MediaElement Service configuration is required.
				/// </summary>
				public const bool IsRequired = true;
			}
			#endif
			""";

		await VerifySourceGeneratorAsync(source, expectedGenerated);
	}

	[Fact]
	public async Task GenerateConfiguration_WhenUseMauiCommunityToolkitMediaElementCalledWithPositionalArgument_GeneratesCorrectCode()
	{
		const string source =
			/* language=C#-test */
			$$"""
			using System;
			using CommunityToolkit.Maui.Core;
			using Microsoft.Maui.Hosting;

			namespace {{defaultTestNamespace}};

			public class MediaElementOptions
			{
				internal static bool IsAndroidForegroundServiceEnabled { get; private set; } = false;

				public void SetIsAndroidForegroundServiceEnabled(bool isEnabled)
				{
					IsAndroidForegroundServiceEnabled = isEnabled;
				}
			}

			public static class AppBuilderExtensions
			{
				public static MauiAppBuilder UseMauiCommunityToolkitMediaElement(
					this MauiAppBuilder builder,
					bool isAndroidForegroundServiceEnabled,
					Action<MediaElementOptions>? options = null)
				{
					var mediaElementOptions = new MediaElementOptions();
					options?.Invoke(mediaElementOptions);
					mediaElementOptions.SetIsAndroidForegroundServiceEnabled(isAndroidForegroundServiceEnabled);
					return builder;
				}
			}

			public class MauiProgram
			{
				public static MauiApp CreateMauiApp()
				{
					var builder = MauiApp.CreateBuilder();
					builder.UseMauiCommunityToolkitMediaElement(true);
					return builder.Build();
				}
			}
			""";

		const string expectedGenerated =
			/* language=C#-test */
			"""
			// <auto-generated>
			// See: CommunityToolkit.Maui.MediaElement.SourceGenerators.AndroidMediaElementServiceConfigurationGenerator
			// This file provides assembly-level Android permissions and service attributes
			// when Android Foreground Service is enabled for MediaElement.

			#pragma warning disable
			#nullable enable

			#if ANDROID
			using Android.App;

			[assembly: UsesPermission(Android.Manifest.Permission.ForegroundServiceMediaPlayback)]
			[assembly: UsesPermission(Android.Manifest.Permission.ForegroundService)]
			[assembly: UsesPermission(Android.Manifest.Permission.MediaContentControl)]
			[assembly: UsesPermission(Android.Manifest.Permission.PostNotifications)]

			namespace CommunityToolkit.Maui.Android;

			/// <summary>
			/// Auto-generated configuration for Android MediaElement Service.
			/// </summary>
			/// <remarks>
			/// This file is auto-generated and provides assembly-level permissions
			/// for MediaElement when <see cref="CommunityToolkit.Maui.Core.MediaElementOptions.IsAndroidForegroundServiceEnabled"/> is enabled
			/// or when <see cref="UseMauiCommunityToolkitMediaElement(Microsoft.Maui.MauiAppBuilder, bool, System.Action{CommunityToolkit.Maui.Core.MediaElementOptions})"/>
			/// is called with <c>isAndroidForegroundServiceEnabled</c> set to <c>true</c>.
			/// </remarks>
			internal static class AndroidMediaElementServiceConfiguration
			{
				/// <summary>
				/// Indicates that Android MediaElement Service configuration is required.
				/// </summary>
				public const bool IsRequired = true;
			}
			#endif
			""";

		await VerifySourceGeneratorAsync(source, expectedGenerated);
	}

	[Fact]
	public async Task GenerateConfiguration_WhenMultipleUseMauiCommunityToolkitMediaElementCallsWithTrue_GeneratesCorrectCode()
	{
		const string source =
			/* language=C#-test */
			$$"""
			using System;
			using CommunityToolkit.Maui.Core;
			using Microsoft.Maui.Hosting;

			namespace {{defaultTestNamespace}};

			public class MediaElementOptions
			{
				internal static bool IsAndroidForegroundServiceEnabled { get; private set; } = false;

				public void SetIsAndroidForegroundServiceEnabled(bool isEnabled)
				{
					IsAndroidForegroundServiceEnabled = isEnabled;
				}
			}

			public static class AppBuilderExtensions
			{
				public static MauiAppBuilder UseMauiCommunityToolkitMediaElement(
					this MauiAppBuilder builder,
					bool isAndroidForegroundServiceEnabled,
					Action<MediaElementOptions>? options = null)
				{
					var mediaElementOptions = new MediaElementOptions();
					options?.Invoke(mediaElementOptions);
					mediaElementOptions.SetIsAndroidForegroundServiceEnabled(isAndroidForegroundServiceEnabled);
					return builder;
				}
			}

			public class FirstConfiguration
			{
				public MauiAppBuilder Configure(MauiAppBuilder builder)
				{
					return builder.UseMauiCommunityToolkitMediaElement(isAndroidForegroundServiceEnabled: true);
				}
			}

			public class SecondConfiguration
			{
				public MauiAppBuilder Configure(MauiAppBuilder builder)
				{
					return builder.UseMauiCommunityToolkitMediaElement(true);
				}
			}
			""";

		const string expectedGenerated =
			/* language=C#-test */
			"""
			// <auto-generated>
			// See: CommunityToolkit.Maui.MediaElement.SourceGenerators.AndroidMediaElementServiceConfigurationGenerator
			// This file provides assembly-level Android permissions and service attributes
			// when Android Foreground Service is enabled for MediaElement.

			#pragma warning disable
			#nullable enable

			#if ANDROID
			using Android.App;

			[assembly: UsesPermission(Android.Manifest.Permission.ForegroundServiceMediaPlayback)]
			[assembly: UsesPermission(Android.Manifest.Permission.ForegroundService)]
			[assembly: UsesPermission(Android.Manifest.Permission.MediaContentControl)]
			[assembly: UsesPermission(Android.Manifest.Permission.PostNotifications)]

			namespace CommunityToolkit.Maui.Android;

			/// <summary>
			/// Auto-generated configuration for Android MediaElement Service.
			/// </summary>
			/// <remarks>
			/// This file is auto-generated and provides assembly-level permissions
			/// for MediaElement when <see cref="CommunityToolkit.Maui.Core.MediaElementOptions.IsAndroidForegroundServiceEnabled"/> is enabled
			/// or when <see cref="UseMauiCommunityToolkitMediaElement(Microsoft.Maui.MauiAppBuilder, bool, System.Action{CommunityToolkit.Maui.Core.MediaElementOptions})"/>
			/// is called with <c>isAndroidForegroundServiceEnabled</c> set to <c>true</c>.
			/// </remarks>
			internal static class AndroidMediaElementServiceConfiguration
			{
				/// <summary>
				/// Indicates that Android MediaElement Service configuration is required.
				/// </summary>
				public const bool IsRequired = true;
			}
			#endif
			""";

		await VerifySourceGeneratorAsync(source, expectedGenerated);
	}

	[Fact]
	public async Task GenerateConfiguration_WhenUseMauiCommunityToolkitMediaElementNotCalled_GeneratesNoCode()
	{
		const string source =
			/* language=C#-test */
			$$"""
			using System;
			using CommunityToolkit.Maui.Core;
			using Microsoft.Maui.Hosting;

			namespace {{defaultTestNamespace}};

			public class MediaElementOptions
			{
				internal static bool IsAndroidForegroundServiceEnabled { get; private set; } = false;

				public void SetIsAndroidForegroundServiceEnabled(bool isEnabled)
				{
					IsAndroidForegroundServiceEnabled = isEnabled;
				}
			}

			public static class AppBuilderExtensions
			{
				public static MauiAppBuilder UseMauiCommunityToolkitMediaElement(
					this MauiAppBuilder builder,
					bool isAndroidForegroundServiceEnabled,
					Action<MediaElementOptions>? options = null)
				{
					var mediaElementOptions = new MediaElementOptions();
					options?.Invoke(mediaElementOptions);
					mediaElementOptions.SetIsAndroidForegroundServiceEnabled(isAndroidForegroundServiceEnabled);
					return builder;
				}
			}

			public class MauiProgram
			{
				public static MauiApp CreateMauiApp()
				{
					var builder = MauiApp.CreateBuilder();
					return builder.Build();
				}
			}
			""";

		await VerifySourceGeneratorAsync(source);
	}

	[Fact]
	public async Task GenerateConfiguration_WhenCombinedWithPropertyAndMethodAndExtensionMethodTrue_GeneratesCorrectCode()
	{
		const string source =
			/* language=C#-test */
			$$"""
			using System;
			using CommunityToolkit.Maui.Core;
			using Microsoft.Maui.Hosting;

			namespace {{defaultTestNamespace}};

			public class MediaElementOptions
			{
				internal static bool IsAndroidForegroundServiceEnabled { get; private set; } = true;

				public void SetIsAndroidForegroundServiceEnabled(bool isEnabled)
				{
					IsAndroidForegroundServiceEnabled = isEnabled;
				}
			}

			public static class AppBuilderExtensions
			{
				public static MauiAppBuilder UseMauiCommunityToolkitMediaElement(
					this MauiAppBuilder builder,
					bool isAndroidForegroundServiceEnabled,
					Action<MediaElementOptions>? options = null)
				{
					var mediaElementOptions = new MediaElementOptions();
					options?.Invoke(mediaElementOptions);
					mediaElementOptions.SetIsAndroidForegroundServiceEnabled(isAndroidForegroundServiceEnabled);
					return builder;
				}
			}

			public class MauiProgram
			{
				public static MauiApp CreateMauiApp()
				{
					var builder = MauiApp.CreateBuilder();
					builder.UseMauiCommunityToolkitMediaElement(isAndroidForegroundServiceEnabled: true);
					return builder.Build();
				}
			}
			""";

		const string expectedGenerated =
			/* language=C#-test */
			"""
			// <auto-generated>
			// See: CommunityToolkit.Maui.MediaElement.SourceGenerators.AndroidMediaElementServiceConfigurationGenerator
			// This file provides assembly-level Android permissions and service attributes
			// when Android Foreground Service is enabled for MediaElement.

			#pragma warning disable
			#nullable enable

			#if ANDROID
			using Android.App;

			[assembly: UsesPermission(Android.Manifest.Permission.ForegroundServiceMediaPlayback)]
			[assembly: UsesPermission(Android.Manifest.Permission.ForegroundService)]
			[assembly: UsesPermission(Android.Manifest.Permission.MediaContentControl)]
			[assembly: UsesPermission(Android.Manifest.Permission.PostNotifications)]

			namespace CommunityToolkit.Maui.Android;

			/// <summary>
			/// Auto-generated configuration for Android MediaElement Service.
			/// </summary>
			/// <remarks>
			/// This file is auto-generated and provides assembly-level permissions
			/// for MediaElement when <see cref="CommunityToolkit.Maui.Core.MediaElementOptions.IsAndroidForegroundServiceEnabled"/> is enabled
			/// or when <see cref="UseMauiCommunityToolkitMediaElement(Microsoft.Maui.MauiAppBuilder, bool, System.Action{CommunityToolkit.Maui.Core.MediaElementOptions})"/>
			/// is called with <c>isAndroidForegroundServiceEnabled</c> set to <c>true</c>.
			/// </remarks>
			internal static class AndroidMediaElementServiceConfiguration
			{
				/// <summary>
				/// Indicates that Android MediaElement Service configuration is required.
				/// </summary>
				public const bool IsRequired = true;
			}
			#endif
			""";

		await VerifySourceGeneratorAsync(source, expectedGenerated);
	}
}