using Xunit;

namespace CommunityToolkit.Maui.MediaElement.SourceGenerators.UnitTests.AndroidMediaElementServiceConfigurationGeneratorTests;

public class AndroidMediaElementForegroundServiceConfigurationGenerator_IntegrationTests : BaseAndroidMediaElementForegroundServiceConfigurationGeneratorTest
{
	[Fact]
	public async Task GenerateConfiguration_RealWorldScenarioWithMauiProgram_GeneratesCorrectCode()
	{
		const string source =
			/* language=C#-test */
			$$"""
			using CommunityToolkit.Maui.Core;
			using Microsoft.Maui.Hosting;

			namespace {{defaultTestNamespace}};

			public static class MauiProgram
			{
				public static MauiApp CreateMauiApp()
				{
					var builder = MauiApp.CreateBuilder();
					builder.UseMauiApp<App>();
					return builder.Build();
				}
			}

			public class App : Application
			{
			}

			public class MediaElementOptions
			{
				internal static bool IsAndroidForegroundServiceEnabled { get; private set; } = true;

				public void SetDefaultAndroidViewType(int androidViewType) { }
			}
			""";

		const string expectedGenerated =
			/* language=C#-test */
			"""
			// <auto-generated>
			// See: CommunityToolkit.Maui.MediaElement.SourceGenerators.AndroidMediaElementServiceConfigurationGenerator
			// This file provides assembly-level Android permissions and service attributes
			// when Android Foreground Service is enabled for MediaElement.

			#pragma warning disable
			#nullable enable

			#if ANDROID
			using Android.App;

			[assembly: UsesPermission(Android.Manifest.Permission.ForegroundServiceMediaPlayback)]
			[assembly: UsesPermission(Android.Manifest.Permission.ForegroundService)]
			[assembly: UsesPermission(Android.Manifest.Permission.MediaContentControl)]
			[assembly: UsesPermission(Android.Manifest.Permission.PostNotifications)]

			namespace CommunityToolkit.Maui.Android;

			/// <summary>
			/// Auto-generated configuration for Android MediaElement Service.
			/// </summary>
			/// <remarks>
			/// This file is auto-generated and provides assembly-level permissions
			/// for MediaElement when <see cref="CommunityToolkit.Maui.Core.MediaElementOptions.IsAndroidForegroundServiceEnabled"/> is enabled
			/// or when <see cref="UseMauiCommunityToolkitMediaElement(Microsoft.Maui.MauiAppBuilder, bool, System.Action{CommunityToolkit.Maui.Core.MediaElementOptions})"/>
			/// is called with <c>isAndroidForegroundServiceEnabled</c> set to <c>true</c>.
			/// </remarks>
			internal static class AndroidMediaElementServiceConfiguration
			{
				/// <summary>
				/// Indicates that Android MediaElement Service configuration is required.
				/// </summary>
				public const bool IsRequired = true;
			}
			#endif
			""";

		await VerifySourceGeneratorAsync(source, expectedGenerated);
	}

	[Fact]
	public async Task GenerateConfiguration_ComplexAppWithMultipleFiles_GeneratesCorrectly()
	{
		const string source =
			/* language=C#-test */
			$$"""
			using CommunityToolkit.Maui.Core;
			using Microsoft.Maui.Hosting;
			using System;

			namespace {{defaultTestNamespace}};

			public class MediaElementOptions
			{
				internal static bool IsAndroidForegroundServiceEnabled { get; private set; } = false;

				public void SetIsAndroidForegroundServiceEnabled(bool isEnabled)
				{
					IsAndroidForegroundServiceEnabled = isEnabled;
				}
			}

			public static class MediaElementExtensions
			{
				public static MauiAppBuilder ConfigureMediaElement(this MauiAppBuilder builder)
				{
					var options = new MediaElementOptions();
					options.SetIsAndroidForegroundServiceEnabled(true);
					return builder;
				}
			}

			public static class MauiProgram
			{
				public static MauiApp CreateMauiApp()
				{
					var builder = MauiApp.CreateBuilder();
					builder.ConfigureMediaElement();
					return builder.Build();
				}
			}
			""";

		const string expectedGenerated =
			/* language=C#-test */
			"""
			// <auto-generated>
			// See: CommunityToolkit.Maui.MediaElement.SourceGenerators.AndroidMediaElementServiceConfigurationGenerator
			// This file provides assembly-level Android permissions and service attributes
			// when Android Foreground Service is enabled for MediaElement.

			#pragma warning disable
			#nullable enable

			#if ANDROID
			using Android.App;

			[assembly: UsesPermission(Android.Manifest.Permission.ForegroundServiceMediaPlayback)]
			[assembly: UsesPermission(Android.Manifest.Permission.ForegroundService)]
			[assembly: UsesPermission(Android.Manifest.Permission.MediaContentControl)]
			[assembly: UsesPermission(Android.Manifest.Permission.PostNotifications)]

			namespace CommunityToolkit.Maui.Android;

			/// <summary>
			/// Auto-generated configuration for Android MediaElement Service.
			/// </summary>
			/// <remarks>
			/// This file is auto-generated and provides assembly-level permissions
			/// for MediaElement when <see cref="CommunityToolkit.Maui.Core.MediaElementOptions.IsAndroidForegroundServiceEnabled"/> is enabled
			/// or when <see cref="UseMauiCommunityToolkitMediaElement(Microsoft.Maui.MauiAppBuilder, bool, System.Action{CommunityToolkit.Maui.Core.MediaElementOptions})"/>
			/// is called with <c>isAndroidForegroundServiceEnabled</c> set to <c>true</c>.
			/// </remarks>
			internal static class AndroidMediaElementServiceConfiguration
			{
				/// <summary>
				/// Indicates that Android MediaElement Service configuration is required.
				/// </summary>
				public const bool IsRequired = true;
			}
			#endif
			""";

		await VerifySourceGeneratorAsync(source, expectedGenerated);
	}

	[Fact]
	public async Task GenerateConfiguration_PropertyAndMethodCombination_GeneratesCorrectly()
	{
		const string source =
			/* language=C#-test */
			$$"""
			using CommunityToolkit.Maui.Core;

			namespace {{defaultTestNamespace}};

			public class MediaElementOptions
			{
				internal static bool IsAndroidForegroundServiceEnabled { get; private set; } = false;

				public void SetIsAndroidForegroundServiceEnabled(bool isEnabled)
				{
					IsAndroidForegroundServiceEnabled = isEnabled;
				}
			}

			public class FirstConfiguration
			{
				public void Configure()
				{
					var options = new MediaElementOptions();
					options.SetIsAndroidForegroundServiceEnabled(false);
				}
			}

			public class SecondConfiguration
			{
				public void Configure()
				{
					var options = new MediaElementOptions();
					options.SetIsAndroidForegroundServiceEnabled(true);
				}
			}
			""";

		const string expectedGenerated =
			/* language=C#-test */
			"""
			// <auto-generated>
			// See: CommunityToolkit.Maui.MediaElement.SourceGenerators.AndroidMediaElementServiceConfigurationGenerator
			// This file provides assembly-level Android permissions and service attributes
			// when Android Foreground Service is enabled for MediaElement.

			#pragma warning disable
			#nullable enable

			#if ANDROID
			using Android.App;

			[assembly: UsesPermission(Android.Manifest.Permission.ForegroundServiceMediaPlayback)]
			[assembly: UsesPermission(Android.Manifest.Permission.ForegroundService)]
			[assembly: UsesPermission(Android.Manifest.Permission.MediaContentControl)]
			[assembly: UsesPermission(Android.Manifest.Permission.PostNotifications)]

			namespace CommunityToolkit.Maui.Android;

			/// <summary>
			/// Auto-generated configuration for Android MediaElement Service.
			/// </summary>
			/// <remarks>
			/// This file is auto-generated and provides assembly-level permissions
			/// for MediaElement when <see cref="CommunityToolkit.Maui.Core.MediaElementOptions.IsAndroidForegroundServiceEnabled"/> is enabled
			/// or when <see cref="UseMauiCommunityToolkitMediaElement(Microsoft.Maui.MauiAppBuilder, bool, System.Action{CommunityToolkit.Maui.Core.MediaElementOptions})"/>
			/// is called with <c>isAndroidForegroundServiceEnabled</c> set to <c>true</c>.
			/// </remarks>
			internal static class AndroidMediaElementServiceConfiguration
			{
				/// <summary>
				/// Indicates that Android MediaElement Service configuration is required.
				/// </summary>
				public const bool IsRequired = true;
			}
			#endif
			""";

		await VerifySourceGeneratorAsync(source, expectedGenerated);
	}
}
