using Xunit;

namespace CommunityToolkit.Maui.MediaElement.SourceGenerators.UnitTests.AndroidMediaElementServiceConfigurationGeneratorTests;

public class AndroidMediaElementForegroundServiceConfigurationGenerator_EdgeCaseTests : BaseAndroidMediaElementForegroundServiceConfigurationGeneratorTest
{
	[Fact]
	public async Task GenerateConfiguration_WithMultipleMediaElementOptionsClasses_GeneratesOnce()
	{
		const string source =
			/* language=C#-test */
			$$"""
			using CommunityToolkit.Maui.Core;

			namespace {{defaultTestNamespace}};

			public class MediaElementOptions
			{
				internal static bool IsAndroidForegroundServiceEnabled { get; private set; } = true;
			}

			public class MyCustomMediaElementOptions
			{
				internal static bool IsAndroidForegroundServiceEnabled { get; private set; } = true;
			}
			""";

		const string expectedGenerated =
			/* language=C#-test */
			"""
			// <auto-generated>
			// See: CommunityToolkit.Maui.MediaElement.SourceGenerators.AndroidMediaElementServiceConfigurationGenerator
			// This file provides assembly-level Android permissions and service attributes
			// when Android Foreground Service is enabled for MediaElement.

			#pragma warning disable
			#nullable enable

			#if ANDROID
			using Android.App;

			[assembly: UsesPermission(Android.Manifest.Permission.ForegroundServiceMediaPlayback)]
			[assembly: UsesPermission(Android.Manifest.Permission.ForegroundService)]
			[assembly: UsesPermission(Android.Manifest.Permission.MediaContentControl)]
			[assembly: UsesPermission(Android.Manifest.Permission.PostNotifications)]

			namespace CommunityToolkit.Maui.Android;

			/// <summary>
			/// Auto-generated configuration for Android MediaElement Service.
			/// </summary>
			/// <remarks>
			/// This file is auto-generated and provides assembly-level permissions
			/// for MediaElement when <see cref="CommunityToolkit.Maui.Core.MediaElementOptions.IsAndroidForegroundServiceEnabled"/> is enabled
			/// or when <see cref="UseMauiCommunityToolkitMediaElement(Microsoft.Maui.MauiAppBuilder, bool, System.Action{CommunityToolkit.Maui.Core.MediaElementOptions})"/>
			/// is called with <c>isAndroidForegroundServiceEnabled</c> set to <c>true</c>.
			/// </remarks>
			internal static class AndroidMediaElementServiceConfiguration
			{
				/// <summary>
				/// Indicates that Android MediaElement Service configuration is required.
				/// </summary>
				public const bool IsRequired = true;
			}
			#endif
			""";

		await VerifySourceGeneratorAsync(source, expectedGenerated);
	}

	[Fact]
	public async Task GenerateConfiguration_WithNestedNamespace_GeneratesCorrectCode()
	{
		const string source =
			/* language=C#-test */
			"""
			using CommunityToolkit.Maui.Core;

			namespace Company.Product.App;

			public class MediaElementOptions
			{
				internal static bool IsAndroidForegroundServiceEnabled { get; private set; } = true;
			}
			""";

		const string expectedGenerated =
			/* language=C#-test */
			"""
			// <auto-generated>
			// See: CommunityToolkit.Maui.MediaElement.SourceGenerators.AndroidMediaElementServiceConfigurationGenerator
			// This file provides assembly-level Android permissions and service attributes
			// when Android Foreground Service is enabled for MediaElement.

			#pragma warning disable
			#nullable enable

			#if ANDROID
			using Android.App;

			[assembly: UsesPermission(Android.Manifest.Permission.ForegroundServiceMediaPlayback)]
			[assembly: UsesPermission(Android.Manifest.Permission.ForegroundService)]
			[assembly: UsesPermission(Android.Manifest.Permission.MediaContentControl)]
			[assembly: UsesPermission(Android.Manifest.Permission.PostNotifications)]

			namespace CommunityToolkit.Maui.Android;

			/// <summary>
			/// Auto-generated configuration for Android MediaElement Service.
			/// </summary>
			/// <remarks>
			/// This file is auto-generated and provides assembly-level permissions
			/// for MediaElement when <see cref="CommunityToolkit.Maui.Core.MediaElementOptions.IsAndroidForegroundServiceEnabled"/> is enabled
			/// or when <see cref="UseMauiCommunityToolkitMediaElement(Microsoft.Maui.MauiAppBuilder, bool, System.Action{CommunityToolkit.Maui.Core.MediaElementOptions})"/>
			/// is called with <c>isAndroidForegroundServiceEnabled</c> set to <c>true</c>.
			/// </remarks>
			internal static class AndroidMediaElementServiceConfiguration
			{
				/// <summary>
				/// Indicates that Android MediaElement Service configuration is required.
				/// </summary>
				public const bool IsRequired = true;
			}
			#endif
			""";

		await VerifySourceGeneratorAsync(source, expectedGenerated);
	}

	[Fact]
	public async Task GenerateConfiguration_WithBothPropertyAndMethod_GeneratesOnce()
	{
		const string source =
			/* language=C#-test */
			$$"""
			using CommunityToolkit.Maui.Core;

			namespace {{defaultTestNamespace}};

			public class MediaElementOptions
			{
				internal static bool IsAndroidForegroundServiceEnabled { get; private set; } = true;

				public void SetIsAndroidForegroundServiceEnabled(bool isEnabled)
				{
					IsAndroidForegroundServiceEnabled = isEnabled;
				}
			}

			public class TestConfiguration
			{
				public void Configure()
				{
					var options = new MediaElementOptions();
					options.SetIsAndroidForegroundServiceEnabled(true);
				}
			}
			""";

		const string expectedGenerated =
			/* language=C#-test */
			"""
			// <auto-generated>
			// See: CommunityToolkit.Maui.MediaElement.SourceGenerators.AndroidMediaElementServiceConfigurationGenerator
			// This file provides assembly-level Android permissions and service attributes
			// when Android Foreground Service is enabled for MediaElement.

			#pragma warning disable
			#nullable enable

			#if ANDROID
			using Android.App;

			[assembly: UsesPermission(Android.Manifest.Permission.ForegroundServiceMediaPlayback)]
			[assembly: UsesPermission(Android.Manifest.Permission.ForegroundService)]
			[assembly: UsesPermission(Android.Manifest.Permission.MediaContentControl)]
			[assembly: UsesPermission(Android.Manifest.Permission.PostNotifications)]

			namespace CommunityToolkit.Maui.Android;

			/// <summary>
			/// Auto-generated configuration for Android MediaElement Service.
			/// </summary>
			/// <remarks>
			/// This file is auto-generated and provides assembly-level permissions
			/// for MediaElement when <see cref="CommunityToolkit.Maui.Core.MediaElementOptions.IsAndroidForegroundServiceEnabled"/> is enabled
			/// or when <see cref="UseMauiCommunityToolkitMediaElement(Microsoft.Maui.MauiAppBuilder, bool, System.Action{CommunityToolkit.Maui.Core.MediaElementOptions})"/>
			/// is called with <c>isAndroidForegroundServiceEnabled</c> set to <c>true</c>.
			/// </remarks>
			internal static class AndroidMediaElementServiceConfiguration
			{
				/// <summary>
				/// Indicates that Android MediaElement Service configuration is required.
				/// </summary>
				public const bool IsRequired = true;
			}
			#endif
			""";

		await VerifySourceGeneratorAsync(source, expectedGenerated);
	}

	[Fact]
	public async Task GenerateConfiguration_WithEmptySource_GeneratesNoCode()
	{
		const string source =
			/* language=C#-test */
			"""
			namespace TestNamespace;

			public class EmptyClass
			{
			}
			""";

		await VerifySourceGeneratorAsync(source);
	}

	[Fact]
	public async Task GenerateConfiguration_WithPropertyInDifferentClass_GeneratesNoCode()
	{
		const string source =
			/* language=C#-test */
			$$"""
			using CommunityToolkit.Maui.Core;

			namespace {{defaultTestNamespace}};

			public class OtherOptions
			{
				internal static bool IsAndroidForegroundServiceEnabled { get; private set; } = true;
			}
			""";

		await VerifySourceGeneratorAsync(source);
	}
}
