using Xunit;

namespace CommunityToolkit.Maui.SourceGenerators.UnitTests.BindablePropertyAttributeSourceGeneratorTests;

public class BindablePropertyAttributeSourceGenerator_EdgeCaseTests : BaseBindablePropertyAttributeSourceGeneratorTest
{
	[Fact]
	public async Task GenerateBindableProperty_PropertyWithReservedKeywords_GeneratesCorrectCode()
	{
		const string source =
			/* language=C#-test */
			//lang=csharp
			$$"""
            using CommunityToolkit.Maui;
            using Microsoft.Maui.Controls;

            namespace {{defaultTestNamespace}};

            public partial class {{defaultTestClassName}} : View
            {
                [BindableProperty]
                public partial string @class { get; set; }

                [BindableProperty]
                public partial string @namespace { get; set; }
            }
            """;

		const string expectedGenerated =
			/* language=C#-test */
			//lang=csharp
			$$"""
            // <auto-generated>
            // See: CommunityToolkit.Maui.SourceGenerators.BindablePropertyAttributeSourceGenerator
            #pragma warning disable
            #nullable enable
            namespace {{defaultTestNamespace}};
            public partial class {{defaultTestClassName}}
            {
                /// <summary>
                /// BindableProperty for the <see cref = "@class"/> property.
                /// </summary>
                public static readonly global::Microsoft.Maui.Controls.BindableProperty classProperty = global::Microsoft.Maui.Controls.BindableProperty.Create("@class", typeof(string), typeof({{defaultTestNamespace}}.{{defaultTestClassName}}), null, (Microsoft.Maui.Controls.BindingMode)0, null, null, null, null, null);
                public partial string @class { get => (string)GetValue(classProperty); set => SetValue(classProperty, value); }

                /// <summary>
                /// BindableProperty for the <see cref = "@namespace"/> property.
                /// </summary>
                public static readonly global::Microsoft.Maui.Controls.BindableProperty namespaceProperty = global::Microsoft.Maui.Controls.BindableProperty.Create("@namespace", typeof(string), typeof({{defaultTestNamespace}}.{{defaultTestClassName}}), null, (Microsoft.Maui.Controls.BindingMode)0, null, null, null, null, null);
                public partial string @namespace { get => (string)GetValue(namespaceProperty); set => SetValue(namespaceProperty, value); }
            }
            """;

		await VerifySourceGeneratorAsync(source, expectedGenerated);
	}

	[Fact]
	public async Task GenerateBindableProperty_PropertyIsByteEnum_GeneratesCorrectCode()
	{
		const string source =
			/* language=C#-test */
			//lang=csharp
			$$"""
            using CommunityToolkit.Maui;
            using Microsoft.Maui.Controls;

            namespace {{defaultTestNamespace}};

            public partial class {{defaultTestClassName}} : View
            {
                [BindableProperty]
                public partial Status InvoiceStatus { get; set; } = Status.Approved;
            }
            
            public enum Status : byte
            {
                Pending = 0,
                Approved = 1,
                Rejected = 2
            }
            """;

		const string expectedGenerated =
			/* language=C#-test */
			//lang=csharp
			$$"""
            // <auto-generated>
            // See: CommunityToolkit.Maui.SourceGenerators.BindablePropertyAttributeSourceGenerator
            #pragma warning disable
            #nullable enable
            namespace {{defaultTestNamespace}};
            public partial class {{defaultTestClassName}}
            {
                [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
                bool __isInitializingInvoiceStatus;
                /// <summary>
                /// BindableProperty for the <see cref = "InvoiceStatus"/> property.
                /// </summary>
                public static readonly global::Microsoft.Maui.Controls.BindableProperty InvoiceStatusProperty = global::Microsoft.Maui.Controls.BindableProperty.Create("InvoiceStatus", typeof(TestNamespace.Status), typeof({{defaultTestNamespace}}.{{defaultTestClassName}}), null, (Microsoft.Maui.Controls.BindingMode)0, null, null, null, null, __BindablePropertyInitHelpers.CreateDefaultInvoiceStatus);
                public partial TestNamespace.Status InvoiceStatus { get => __isInitializingInvoiceStatus ? field : (TestNamespace.Status)GetValue(InvoiceStatusProperty); set => SetValue(InvoiceStatusProperty, value); }

                [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
                static class __BindablePropertyInitHelpers
                {
                    public static object CreateDefaultInvoiceStatus(global::Microsoft.Maui.Controls.BindableObject bindable)
                    {
                        (({{defaultTestClassName}})bindable).__isInitializingInvoiceStatus = true;
                        var defaultValue = (({{defaultTestClassName}})bindable).InvoiceStatus;
                        (({{defaultTestClassName}})bindable).__isInitializingInvoiceStatus = false;
                        return defaultValue;
                    }
                }
            }
            """;

		await VerifySourceGeneratorAsync(source, expectedGenerated);
	}

	[Fact]
	public async Task GenerateBindableProperty_PropertyIsLongEnum_GeneratesCorrectCode()
	{
		const string source =
			/* language=C#-test */
			//lang=csharp
			$$"""
            using CommunityToolkit.Maui;
            using Microsoft.Maui.Controls;

            namespace {{defaultTestNamespace}};

            public partial class {{defaultTestClassName}} : View
            {
                [BindableProperty]
                public partial Status InvoiceStatus { get; set; } = Status.Rejected;
            }
            
            public enum Status : long
            {
                Pending = 0,
                Approved = 1,
                Rejected = long.MaxValue
            }
            """;

		const string expectedGenerated =
			/* language=C#-test */
			//lang=csharp
			$$"""
            // <auto-generated>
            // See: CommunityToolkit.Maui.SourceGenerators.BindablePropertyAttributeSourceGenerator
            #pragma warning disable
            #nullable enable
            namespace {{defaultTestNamespace}};
            public partial class {{defaultTestClassName}}
            {
                [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
                bool __isInitializingInvoiceStatus;
                /// <summary>
                /// BindableProperty for the <see cref = "InvoiceStatus"/> property.
                /// </summary>
                public static readonly global::Microsoft.Maui.Controls.BindableProperty InvoiceStatusProperty = global::Microsoft.Maui.Controls.BindableProperty.Create("InvoiceStatus", typeof(TestNamespace.Status), typeof({{defaultTestNamespace}}.{{defaultTestClassName}}), null, (Microsoft.Maui.Controls.BindingMode)0, null, null, null, null, __BindablePropertyInitHelpers.CreateDefaultInvoiceStatus);
                public partial TestNamespace.Status InvoiceStatus { get => __isInitializingInvoiceStatus ? field : (TestNamespace.Status)GetValue(InvoiceStatusProperty); set => SetValue(InvoiceStatusProperty, value); }

                [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
                static class __BindablePropertyInitHelpers
                {
                    public static object CreateDefaultInvoiceStatus(global::Microsoft.Maui.Controls.BindableObject bindable)
                    {
                        (({{defaultTestClassName}})bindable).__isInitializingInvoiceStatus = true;
                        var defaultValue = (({{defaultTestClassName}})bindable).InvoiceStatus;
                        (({{defaultTestClassName}})bindable).__isInitializingInvoiceStatus = false;
                        return defaultValue;
                    }
                }
            }
            """;

		await VerifySourceGeneratorAsync(source, expectedGenerated);
	}

	[Fact]
	public async Task GenerateBindableProperty_NullableValueTypes_GeneratesCorrectCode()
	{
		const string source =
			/* language=C#-test */
			//lang=csharp
			$$"""			
            using System;
            using CommunityToolkit.Maui;
            using Microsoft.Maui.Controls;

            namespace {{defaultTestNamespace}};

            public partial class {{defaultTestClassName}} : View
            {
                [BindableProperty]
                public partial int? NullableInt { get; set; }

                [BindableProperty]
                public partial DateTime? NullableDateTime { get; set; }

                [BindableProperty]
                public partial bool? NullableBool { get; set; }
            }
            """;

		const string expectedGenerated =
			/* language=C#-test */
			//lang=csharp
			$$"""
            // <auto-generated>
            // See: CommunityToolkit.Maui.SourceGenerators.BindablePropertyAttributeSourceGenerator
            #pragma warning disable
            #nullable enable
            namespace {{defaultTestNamespace}};
            public partial class {{defaultTestClassName}}
            {
                /// <summary>
                /// BindableProperty for the <see cref = "NullableInt"/> property.
                /// </summary>
                public static readonly global::Microsoft.Maui.Controls.BindableProperty NullableIntProperty = global::Microsoft.Maui.Controls.BindableProperty.Create("NullableInt", typeof(int? ), typeof({{defaultTestNamespace}}.{{defaultTestClassName}}), null, (Microsoft.Maui.Controls.BindingMode)0, null, null, null, null, null);
                public partial int? NullableInt { get => (int? )GetValue(NullableIntProperty); set => SetValue(NullableIntProperty, value); }

                /// <summary>
                /// BindableProperty for the <see cref = "NullableDateTime"/> property.
                /// </summary>
                public static readonly global::Microsoft.Maui.Controls.BindableProperty NullableDateTimeProperty = global::Microsoft.Maui.Controls.BindableProperty.Create("NullableDateTime", typeof(System.DateTime? ), typeof({{defaultTestNamespace}}.{{defaultTestClassName}}), null, (Microsoft.Maui.Controls.BindingMode)0, null, null, null, null, null);
                public partial System.DateTime? NullableDateTime { get => (System.DateTime? )GetValue(NullableDateTimeProperty); set => SetValue(NullableDateTimeProperty, value); }

                /// <summary>
                /// BindableProperty for the <see cref = "NullableBool"/> property.
                /// </summary>
                public static readonly global::Microsoft.Maui.Controls.BindableProperty NullableBoolProperty = global::Microsoft.Maui.Controls.BindableProperty.Create("NullableBool", typeof(bool? ), typeof({{defaultTestNamespace}}.{{defaultTestClassName}}), null, (Microsoft.Maui.Controls.BindingMode)0, null, null, null, null, null);
                public partial bool? NullableBool { get => (bool? )GetValue(NullableBoolProperty); set => SetValue(NullableBoolProperty, value); }
            }
            """;

		await VerifySourceGeneratorAsync(source, expectedGenerated);
	}

	[Fact]
	public async Task GenerateBindableProperty_ArrayTypes_GeneratesCorrectCode()
	{
		const string source =
			/* language=C#-test */
			//lang=csharp
			$$"""
            using CommunityToolkit.Maui;
            using Microsoft.Maui.Controls;

            namespace {{defaultTestNamespace}};

            public partial class {{defaultTestClassName}} : View
            {
                [BindableProperty]
                public partial string[] StringArray { get; set; }

                [BindableProperty]
                public partial int[, ] MultiDimensionalArray { get; set; }

                [BindableProperty]
                public partial byte[][] JaggedArray { get; set; }
            }
            """;

		const string expectedGenerated =
			/* language=C#-test */
			//lang=csharp
			$$"""
            // <auto-generated>
            // See: CommunityToolkit.Maui.SourceGenerators.BindablePropertyAttributeSourceGenerator
            #pragma warning disable
            #nullable enable
            namespace {{defaultTestNamespace}};
            public partial class {{defaultTestClassName}}
            {
                /// <summary>
                /// BindableProperty for the <see cref = "StringArray"/> property.
                /// </summary>
                public static readonly global::Microsoft.Maui.Controls.BindableProperty StringArrayProperty = global::Microsoft.Maui.Controls.BindableProperty.Create("StringArray", typeof(string[]), typeof({{defaultTestNamespace}}.{{defaultTestClassName}}), null, (Microsoft.Maui.Controls.BindingMode)0, null, null, null, null, null);
                public partial string[] StringArray { get => (string[])GetValue(StringArrayProperty); set => SetValue(StringArrayProperty, value); }

                /// <summary>
                /// BindableProperty for the <see cref = "MultiDimensionalArray"/> property.
                /// </summary>
                public static readonly global::Microsoft.Maui.Controls.BindableProperty MultiDimensionalArrayProperty = global::Microsoft.Maui.Controls.BindableProperty.Create("MultiDimensionalArray", typeof(int[, ]), typeof({{defaultTestNamespace}}.{{defaultTestClassName}}), null, (Microsoft.Maui.Controls.BindingMode)0, null, null, null, null, null);
                public partial int[, ] MultiDimensionalArray { get => (int[, ])GetValue(MultiDimensionalArrayProperty); set => SetValue(MultiDimensionalArrayProperty, value); }

                /// <summary>
                /// BindableProperty for the <see cref = "JaggedArray"/> property.
                /// </summary>
                public static readonly global::Microsoft.Maui.Controls.BindableProperty JaggedArrayProperty = global::Microsoft.Maui.Controls.BindableProperty.Create("JaggedArray", typeof(byte[][]), typeof({{defaultTestNamespace}}.{{defaultTestClassName}}), null, (Microsoft.Maui.Controls.BindingMode)0, null, null, null, null, null);
                public partial byte[][] JaggedArray { get => (byte[][])GetValue(JaggedArrayProperty); set => SetValue(JaggedArrayProperty, value); }
            }
            """;

		await VerifySourceGeneratorAsync(source, expectedGenerated);
	}

	[Fact]
	public async Task GenerateBindableProperty_LongNamespaces_GeneratesCorrectCode()
	{
		const string source =
			/* language=C#-test */
			//lang=csharp
			$$"""
            using CommunityToolkit.Maui;
            using Microsoft.Maui.Controls;

            namespace Very.Long.Namespace.With.Many.Segments.TestNamespace;

            public partial class {{defaultTestClassName}} : View
            {
                [BindableProperty]
                public partial string Text { get; set; }
            }
            """;

		const string expectedGenerated =
			/* language=C#-test */
			//lang=csharp
			$$"""
            // <auto-generated>
            // See: CommunityToolkit.Maui.SourceGenerators.BindablePropertyAttributeSourceGenerator
            #pragma warning disable
            #nullable enable
            namespace Very.Long.Namespace.With.Many.Segments.TestNamespace;
            public partial class {{defaultTestClassName}}
            {
                /// <summary>
                /// BindableProperty for the <see cref = "Text"/> property.
                /// </summary>
                public static readonly global::Microsoft.Maui.Controls.BindableProperty TextProperty = global::Microsoft.Maui.Controls.BindableProperty.Create("Text", typeof(string), typeof(Very.Long.Namespace.With.Many.Segments.TestNamespace.TestView), null, (Microsoft.Maui.Controls.BindingMode)0, null, null, null, null, null);
                public partial string Text { get => (string)GetValue(TextProperty); set => SetValue(TextProperty, value); }
            }
            """;

		await VerifySourceGeneratorAsync(source, expectedGenerated);
	}

	[Fact]
	public async Task GenerateBindableProperty_GlobalNamespace_GeneratesCorrectCode()
	{
		const string source =
			/* language=C#-test */
			//lang=csharp
			$$"""
            using CommunityToolkit.Maui;
            using Microsoft.Maui.Controls;

            public partial class {{defaultTestClassName}} : View
            {
                [BindableProperty]
                public partial string Text { get; set; }
            }
            """;

		const string expectedGenerated =
			/* language=C#-test */
			//lang=csharp
			$$"""
            // <auto-generated>
            // See: CommunityToolkit.Maui.SourceGenerators.BindablePropertyAttributeSourceGenerator
            #pragma warning disable
            #nullable enable
            public partial class {{defaultTestClassName}}
            {
                /// <summary>
                /// BindableProperty for the <see cref = "Text"/> property.
                /// </summary>
                public static readonly global::Microsoft.Maui.Controls.BindableProperty TextProperty = global::Microsoft.Maui.Controls.BindableProperty.Create("Text", typeof(string), typeof(TestView), null, (Microsoft.Maui.Controls.BindingMode)0, null, null, null, null, null);
                public partial string Text { get => (string)GetValue(TextProperty); set => SetValue(TextProperty, value); }
            }
            """;

		await VerifySourceGeneratorAsync(source, expectedGenerated);
	}

	[Fact]
	public async Task GenerateBindableProperty_SpecialCharactersInPropertyName_GeneratesCorrectCode()
	{
		const string source =
			/* language=C#-test */
			//lang=csharp
			$$"""
            using CommunityToolkit.Maui;
            using Microsoft.Maui.Controls;

            namespace {{defaultTestNamespace}};

            public partial class {{defaultTestClassName}} : View
            {
                [BindableProperty()]
                public partial string Property_With_Underscores { get; set; }

                [BindableProperty()]
                public partial string Property123WithNumbers { get; set; }
            }
            """;

		const string expectedGenerated =
			/* language=C#-test */
			//lang=csharp
			$$"""
            // <auto-generated>
            // See: CommunityToolkit.Maui.SourceGenerators.BindablePropertyAttributeSourceGenerator
            #pragma warning disable
            #nullable enable
            namespace {{defaultTestNamespace}};
            public partial class {{defaultTestClassName}}
            {
                /// <summary>
                /// BindableProperty for the <see cref = "Property_With_Underscores"/> property.
                /// </summary>
                public static readonly global::Microsoft.Maui.Controls.BindableProperty Property_With_UnderscoresProperty = global::Microsoft.Maui.Controls.BindableProperty.Create("Property_With_Underscores", typeof(string), typeof({{defaultTestNamespace}}.{{defaultTestClassName}}), null, (Microsoft.Maui.Controls.BindingMode)0, null, null, null, null, null);
                public partial string Property_With_Underscores { get => (string)GetValue(Property_With_UnderscoresProperty); set => SetValue(Property_With_UnderscoresProperty, value); }

                /// <summary>
                /// BindableProperty for the <see cref = "Property123WithNumbers"/> property.
                /// </summary>
                public static readonly global::Microsoft.Maui.Controls.BindableProperty Property123WithNumbersProperty = global::Microsoft.Maui.Controls.BindableProperty.Create("Property123WithNumbers", typeof(string), typeof({{defaultTestNamespace}}.{{defaultTestClassName}}), null, (Microsoft.Maui.Controls.BindingMode)0, null, null, null, null, null);
                public partial string Property123WithNumbers { get => (string)GetValue(Property123WithNumbersProperty); set => SetValue(Property123WithNumbersProperty, value); }
            }
            """;

		await VerifySourceGeneratorAsync(source, expectedGenerated);
	}

	[Fact]
	public async Task GenerateBindableProperty_WithComplexDefaultValues_GeneratesCorrectCode()
	{
		const string source =
			/* language=C#-test */
			//lang=csharp
			$$"""
            using CommunityToolkit.Maui;
            using Microsoft.Maui.Controls;
            using System;

            namespace {{defaultTestNamespace}};

            public partial class {{defaultTestClassName}} : View
            {
                [BindableProperty]
                public partial bool IsEnabled { get; set; } = true;

                [BindableProperty]
                public partial double Pi { get; set; } = 3.14;

                [BindableProperty]
                public partial char Letter { get; set; } = 'A';
                
                [BindableProperty]
                public partial TimeSpan TimeSpent { get; set; } = System.TimeSpan.Zero;
                
                [BindableProperty]
                public partial double DoubleEpsilon { get; set; } = double.Epsilon;
                
                [BindableProperty]
                public partial double SingleEpsilon { get; set; } = float.Epsilon;
                
                [BindableProperty]
                public partial DateTimeOffset CurrentTime { get; set; } = DateTimeOffset.UtcNow;
            }
            """;

		const string expectedGenerated =
			/* language=C#-test */
			//lang=csharp
			$$"""
            // <auto-generated>
            // See: CommunityToolkit.Maui.SourceGenerators.BindablePropertyAttributeSourceGenerator
            #pragma warning disable
            #nullable enable
            namespace {{defaultTestNamespace}};
            public partial class {{defaultTestClassName}}
            {
                [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
                bool __isInitializingIsEnabled;
                /// <summary>
                /// BindableProperty for the <see cref = "IsEnabled"/> property.
                /// </summary>
                public static readonly global::Microsoft.Maui.Controls.BindableProperty IsEnabledProperty = global::Microsoft.Maui.Controls.BindableProperty.Create("IsEnabled", typeof(bool), typeof({{defaultTestNamespace}}.{{defaultTestClassName}}), null, (Microsoft.Maui.Controls.BindingMode)0, null, null, null, null, __BindablePropertyInitHelpers.CreateDefaultIsEnabled);
                public partial bool IsEnabled { get => __isInitializingIsEnabled ? field : (bool)GetValue(IsEnabledProperty); set => SetValue(IsEnabledProperty, value); }

                [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
                bool __isInitializingPi;
                /// <summary>
                /// BindableProperty for the <see cref = "Pi"/> property.
                /// </summary>
                public static readonly global::Microsoft.Maui.Controls.BindableProperty PiProperty = global::Microsoft.Maui.Controls.BindableProperty.Create("Pi", typeof(double), typeof({{defaultTestNamespace}}.{{defaultTestClassName}}), null, (Microsoft.Maui.Controls.BindingMode)0, null, null, null, null, __BindablePropertyInitHelpers.CreateDefaultPi);
                public partial double Pi { get => __isInitializingPi ? field : (double)GetValue(PiProperty); set => SetValue(PiProperty, value); }

                [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
                bool __isInitializingLetter;
                /// <summary>
                /// BindableProperty for the <see cref = "Letter"/> property.
                /// </summary>
                public static readonly global::Microsoft.Maui.Controls.BindableProperty LetterProperty = global::Microsoft.Maui.Controls.BindableProperty.Create("Letter", typeof(char), typeof({{defaultTestNamespace}}.{{defaultTestClassName}}), null, (Microsoft.Maui.Controls.BindingMode)0, null, null, null, null, __BindablePropertyInitHelpers.CreateDefaultLetter);
                public partial char Letter { get => __isInitializingLetter ? field : (char)GetValue(LetterProperty); set => SetValue(LetterProperty, value); }
            
                [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
                bool __isInitializingTimeSpent;
                /// <summary>
                /// BindableProperty for the <see cref = "TimeSpent"/> property.
                /// </summary>
                public static readonly global::Microsoft.Maui.Controls.BindableProperty TimeSpentProperty = global::Microsoft.Maui.Controls.BindableProperty.Create("TimeSpent", typeof(System.TimeSpan), typeof({{defaultTestNamespace}}.{{defaultTestClassName}}), null, (Microsoft.Maui.Controls.BindingMode)0, null, null, null, null, __BindablePropertyInitHelpers.CreateDefaultTimeSpent);
                public partial System.TimeSpan TimeSpent { get => __isInitializingTimeSpent ? field : (System.TimeSpan)GetValue(TimeSpentProperty); set => SetValue(TimeSpentProperty, value); }
            
                [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
                bool __isInitializingDoubleEpsilon;
                /// <summary>
                /// BindableProperty for the <see cref = "DoubleEpsilon"/> property.
                /// </summary>
                public static readonly global::Microsoft.Maui.Controls.BindableProperty DoubleEpsilonProperty = global::Microsoft.Maui.Controls.BindableProperty.Create("DoubleEpsilon", typeof(double), typeof({{defaultTestNamespace}}.{{defaultTestClassName}}), null, (Microsoft.Maui.Controls.BindingMode)0, null, null, null, null, __BindablePropertyInitHelpers.CreateDefaultDoubleEpsilon);
                public partial double DoubleEpsilon { get => __isInitializingDoubleEpsilon ? field : (double)GetValue(DoubleEpsilonProperty); set => SetValue(DoubleEpsilonProperty, value); }
            
                [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
                bool __isInitializingSingleEpsilon;
                /// <summary>
                /// BindableProperty for the <see cref = "SingleEpsilon"/> property.
                /// </summary>
                public static readonly global::Microsoft.Maui.Controls.BindableProperty SingleEpsilonProperty = global::Microsoft.Maui.Controls.BindableProperty.Create("SingleEpsilon", typeof(double), typeof({{defaultTestNamespace}}.{{defaultTestClassName}}), null, (Microsoft.Maui.Controls.BindingMode)0, null, null, null, null, __BindablePropertyInitHelpers.CreateDefaultSingleEpsilon);
                public partial double SingleEpsilon { get => __isInitializingSingleEpsilon ? field : (double)GetValue(SingleEpsilonProperty); set => SetValue(SingleEpsilonProperty, value); }
            
                [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
                bool __isInitializingCurrentTime;
                /// <summary>
                /// BindableProperty for the <see cref = "CurrentTime"/> property.
                /// </summary>
                public static readonly global::Microsoft.Maui.Controls.BindableProperty CurrentTimeProperty = global::Microsoft.Maui.Controls.BindableProperty.Create("CurrentTime", typeof(System.DateTimeOffset), typeof({{defaultTestNamespace}}.{{defaultTestClassName}}), null, (Microsoft.Maui.Controls.BindingMode)0, null, null, null, null, __BindablePropertyInitHelpers.CreateDefaultCurrentTime);
                public partial System.DateTimeOffset CurrentTime { get => __isInitializingCurrentTime ? field : (System.DateTimeOffset)GetValue(CurrentTimeProperty); set => SetValue(CurrentTimeProperty, value); }

                [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
                static class __BindablePropertyInitHelpers
                {
                    public static object CreateDefaultIsEnabled(global::Microsoft.Maui.Controls.BindableObject bindable)
                    {
                        (({{defaultTestClassName}})bindable).__isInitializingIsEnabled = true;
                        var defaultValue = (({{defaultTestClassName}})bindable).IsEnabled;
                        (({{defaultTestClassName}})bindable).__isInitializingIsEnabled = false;
                        return defaultValue;
                    }

                    public static object CreateDefaultPi(global::Microsoft.Maui.Controls.BindableObject bindable)
                    {
                        (({{defaultTestClassName}})bindable).__isInitializingPi = true;
                        var defaultValue = (({{defaultTestClassName}})bindable).Pi;
                        (({{defaultTestClassName}})bindable).__isInitializingPi = false;
                        return defaultValue;
                    }

                    public static object CreateDefaultLetter(global::Microsoft.Maui.Controls.BindableObject bindable)
                    {
                        (({{defaultTestClassName}})bindable).__isInitializingLetter = true;
                        var defaultValue = (({{defaultTestClassName}})bindable).Letter;
                        (({{defaultTestClassName}})bindable).__isInitializingLetter = false;
                        return defaultValue;
                    }

                    public static object CreateDefaultTimeSpent(global::Microsoft.Maui.Controls.BindableObject bindable)
                    {
                        (({{defaultTestClassName}})bindable).__isInitializingTimeSpent = true;
                        var defaultValue = (({{defaultTestClassName}})bindable).TimeSpent;
                        (({{defaultTestClassName}})bindable).__isInitializingTimeSpent = false;
                        return defaultValue;
                    }

                    public static object CreateDefaultDoubleEpsilon(global::Microsoft.Maui.Controls.BindableObject bindable)
                    {
                        (({{defaultTestClassName}})bindable).__isInitializingDoubleEpsilon = true;
                        var defaultValue = (({{defaultTestClassName}})bindable).DoubleEpsilon;
                        (({{defaultTestClassName}})bindable).__isInitializingDoubleEpsilon = false;
                        return defaultValue;
                    }

                    public static object CreateDefaultSingleEpsilon(global::Microsoft.Maui.Controls.BindableObject bindable)
                    {
                        (({{defaultTestClassName}})bindable).__isInitializingSingleEpsilon = true;
                        var defaultValue = (({{defaultTestClassName}})bindable).SingleEpsilon;
                        (({{defaultTestClassName}})bindable).__isInitializingSingleEpsilon = false;
                        return defaultValue;
                    }

                    public static object CreateDefaultCurrentTime(global::Microsoft.Maui.Controls.BindableObject bindable)
                    {
                        (({{defaultTestClassName}})bindable).__isInitializingCurrentTime = true;
                        var defaultValue = (({{defaultTestClassName}})bindable).CurrentTime;
                        (({{defaultTestClassName}})bindable).__isInitializingCurrentTime = false;
                        return defaultValue;
                    }
                }
            }
            """;

		await VerifySourceGeneratorAsync(source, expectedGenerated);
	}

	[Fact]
	public async Task GenerateBindableProperty_WithBothInitializerAndDefault_GeneratedCodeDefaultsToUseDefaultValueCreatorMethod()
	{
		const string source =
			/* language=C#-test */
			//lang=csharp
			$$"""
			using CommunityToolkit.Maui;
			using Microsoft.Maui.Controls;
			using System;

			namespace {{defaultTestNamespace}};

			public partial class {{defaultTestClassName}} : View
			{
			    [BindablePropertyAttribute(DefaultValueCreatorMethodName = nameof(CreateDefaultText))]
			    public partial string Text { get; set; } = "Initial Value";

				static string CreateDefaultText(BindableObject bindable)
				{
					return "Initial Value";
				}
			}
			""";

		const string expectedGenerated =
			/* language=C#-test */
			//lang=csharp
			$$"""
			// <auto-generated>
			// See: CommunityToolkit.Maui.SourceGenerators.BindablePropertyAttributeSourceGenerator
			#pragma warning disable
			#nullable enable
			namespace {{defaultTestNamespace}};
			public partial class {{defaultTestClassName}}
			{
			    /// <summary>
			    /// BindableProperty for the <see cref = "Text"/> property.
			    /// </summary>
			    public static readonly global::Microsoft.Maui.Controls.BindableProperty TextProperty = global::Microsoft.Maui.Controls.BindableProperty.Create("Text", typeof(string), typeof({{defaultTestNamespace}}.{{defaultTestClassName}}), null, (Microsoft.Maui.Controls.BindingMode)0, null, null, null, null, CreateDefaultText);
			    public partial string Text { get => false ? field : (string)GetValue(TextProperty); set => SetValue(TextProperty, value); }
			}
			""";

		await VerifySourceGeneratorAsync(source, expectedGenerated);
	}

	[Fact]
	public async Task GenerateBindableProperty_InternalProperty_GeneratesCorrectCode()
	{
		const string source =
			/* language=C#-test */
			//lang=csharp
			$$"""
			using CommunityToolkit.Maui;
			using Microsoft.Maui.Controls;
			using System;

			namespace {{defaultTestNamespace}};

			public partial class {{defaultTestClassName}} : View
			{
			    [BindablePropertyAttribute]
			    internal partial string Text { get; set; } = "Initial Value";

				[BindablePropertyAttribute]
			    protected internal partial string Time { get; set; } = string.Empty;

			    [BindablePropertyAttribute]
			    internal partial TimeSpan CustomDuration { get; private set; } = TimeSpan.FromSeconds(30);
			}
			""";

		const string expectedGenerated =
			/* language=C#-test */
			//lang=csharp
			$$"""
			// <auto-generated>
			// See: CommunityToolkit.Maui.SourceGenerators.BindablePropertyAttributeSourceGenerator
			#pragma warning disable
			#nullable enable
			namespace {{defaultTestNamespace}};
			public partial class {{defaultTestClassName}}
			{
			    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
			    bool __isInitializingText;
			    /// <summary>
			    /// BindableProperty for the <see cref = "Text"/> property.
			    /// </summary>
			    internal static readonly global::Microsoft.Maui.Controls.BindableProperty TextProperty = global::Microsoft.Maui.Controls.BindableProperty.Create("Text", typeof(string), typeof({{defaultTestNamespace}}.{{defaultTestClassName}}), null, (Microsoft.Maui.Controls.BindingMode)0, null, null, null, null, __BindablePropertyInitHelpers.CreateDefaultText);
			    internal partial string Text { get => __isInitializingText ? field : (string)GetValue(TextProperty); set => SetValue(TextProperty, value); }

			    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
			    bool __isInitializingTime;
			    /// <summary>
			    /// BindableProperty for the <see cref = "Time"/> property.
			    /// </summary>
			    protected internal static readonly global::Microsoft.Maui.Controls.BindableProperty TimeProperty = global::Microsoft.Maui.Controls.BindableProperty.Create("Time", typeof(string), typeof({{defaultTestNamespace}}.{{defaultTestClassName}}), null, (Microsoft.Maui.Controls.BindingMode)0, null, null, null, null, __BindablePropertyInitHelpers.CreateDefaultTime);
			    protected internal partial string Time { get => __isInitializingTime ? field : (string)GetValue(TimeProperty); set => SetValue(TimeProperty, value); }

			    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
			    bool __isInitializingCustomDuration;
			    static readonly global::Microsoft.Maui.Controls.BindablePropertyKey customDurationPropertyKey = global::Microsoft.Maui.Controls.BindableProperty.CreateReadOnly("CustomDuration", typeof(System.TimeSpan), typeof(TestNamespace.TestView), null, (Microsoft.Maui.Controls.BindingMode)0, null, null, null, null, __BindablePropertyInitHelpers.CreateDefaultCustomDuration);
			    /// <summary>
			    /// BindableProperty for the <see cref = "CustomDuration"/> property.
			    /// </summary>
			    internal static readonly global::Microsoft.Maui.Controls.BindableProperty CustomDurationProperty = customDurationPropertyKey.BindableProperty;
			    internal partial System.TimeSpan CustomDuration { get => __isInitializingCustomDuration ? field : (System.TimeSpan)GetValue(CustomDurationProperty); private set => SetValue(customDurationPropertyKey, value); }

			    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
			    static class __BindablePropertyInitHelpers
			    {
			        public static object CreateDefaultText(global::Microsoft.Maui.Controls.BindableObject bindable)
			        {
			            (({{defaultTestClassName}})bindable).__isInitializingText = true;
			            var defaultValue = (({{defaultTestClassName}})bindable).Text;
			            (({{defaultTestClassName}})bindable).__isInitializingText = false;
			            return defaultValue;
			        }

			        public static object CreateDefaultTime(global::Microsoft.Maui.Controls.BindableObject bindable)
			        {
			            (({{defaultTestClassName}})bindable).__isInitializingTime = true;
			            var defaultValue = (({{defaultTestClassName}})bindable).Time;
			            (({{defaultTestClassName}})bindable).__isInitializingTime = false;
			            return defaultValue;
			        }

			        public static object CreateDefaultCustomDuration(global::Microsoft.Maui.Controls.BindableObject bindable)
			        {
			            (({{defaultTestClassName}})bindable).__isInitializingCustomDuration = true;
			            var defaultValue = (({{defaultTestClassName}})bindable).CustomDuration;
			            (({{defaultTestClassName}})bindable).__isInitializingCustomDuration = false;
			            return defaultValue;
			        }
			    }
			}
			""";

		await VerifySourceGeneratorAsync(source, expectedGenerated);
	}

	[Fact]
	public async Task GenerateBindableProperty_PrivateProperty_ThrowsNotSupportedException()
	{
		const string source =
			/* language=C#-test */
			//lang=csharp
			$$"""
			using CommunityToolkit.Maui;
			using Microsoft.Maui.Controls;

			namespace {{defaultTestNamespace}};

			public partial class {{defaultTestClassName}} : View
			{
			    [BindablePropertyAttribute]
			    private partial string Text { get; set; }
			}
			""";

		await Assert.ThrowsAsync<InvalidOperationException>(async () => await VerifySourceGeneratorAsync(source, string.Empty));
	}

	[Fact]
	public async Task GenerateBindableProperty_ProtectedProperty_ThrowsNotSupportedException()
	{
		const string source =
			/* language=C#-test */
			//lang=csharp
			$$"""
			using CommunityToolkit.Maui;
			using Microsoft.Maui.Controls;

			namespace {{defaultTestNamespace}};

			public partial class {{defaultTestClassName}} : View
			{
			    [BindablePropertyAttribute]
			    protected partial string Text { get; set; }
			}
			""";

		await Assert.ThrowsAsync<InvalidOperationException>(async () => await VerifySourceGeneratorAsync(source, string.Empty));
	}

	[Fact]
	public async Task GenerateBindableProperty_PrivateProtectedProperty_ThrowsNotSupportedException()
	{
		const string source =
			/* language=C#-test */
			//lang=csharp
			$$"""
			using CommunityToolkit.Maui;
			using Microsoft.Maui.Controls;

			namespace {{defaultTestNamespace}};

			public partial class {{defaultTestClassName}} : View
			{
			    [BindablePropertyAttribute]
			    private protected partial string Text { get; set; }
			}
			""";

		await Assert.ThrowsAsync<InvalidOperationException>(async () => await VerifySourceGeneratorAsync(source, string.Empty));
	}
}