using Xunit;

namespace CommunityToolkit.Maui.SourceGenerators.Internal.UnitTests.AttachedBindablePropertyAttributeSourceGeneratorTests;

public class AttachedBindablePropertyAttributeSourceGenerator_ClassAttribute_EdgeCaseTests : BaseAttachedBindablePropertyAttributeSourceGeneratorTest
{
	[Fact]
	public async Task GenerateAttachedBindableProperty_LowercasePropertyName_ThrowsNotSupportedException()
	{
		const string source =
			/* language=C#-test */
			//lang=csharp
			$$"""
            using CommunityToolkit.Maui;
            using Microsoft.Maui.Controls;

            namespace {{defaultTestNamespace}};

            [AttachedBindableProperty<string>("text")]
            public partial class {{defaultTestClassName}} : View
            {
            }
            """;

		var invalidOperationException = await Assert.ThrowsAsync<InvalidOperationException>(() => VerifySourceGeneratorAsync(source, string.Empty));
		Assert.Contains("NotSupportedException", invalidOperationException.Message);
	}

	[Fact]
	public async Task GenerateAttachedBindableProperty_PropertyWithReservedKeywords_GeneratesCorrectCode()
	{
		const string source =
			/* language=C#-test */
			//lang=csharp
			$$"""
            using CommunityToolkit.Maui;
            using Microsoft.Maui.Controls;

            namespace {{defaultTestNamespace}};

            [AttachedBindableProperty<string>("Class")]
            [AttachedBindableProperty<string>("Namespace")]
            public partial class {{defaultTestClassName}} : View
            {
            }
            """;

		const string expectedGenerated =
			/* language=C#-test */
			//lang=csharp
			$$"""
            // <auto-generated>
            // See: CommunityToolkit.Maui.SourceGenerators.Internal.AttachedBindablePropertyAttributeSourceGenerator
            #pragma warning disable
            #nullable enable
            namespace {{defaultTestNamespace}};
            public partial class {{defaultTestClassName}}
            {
                /// <summary>
                /// Attached BindableProperty for the Class property.
                /// </summary>
                public static readonly global::Microsoft.Maui.Controls.BindableProperty ClassProperty = global::Microsoft.Maui.Controls.BindableProperty.CreateAttached("Class", typeof(string), typeof({{defaultTestNamespace}}.{{defaultTestClassName}}), null, (global::Microsoft.Maui.Controls.BindingMode)0, null, null, null, null, null);
                /// <summary>
                /// Gets Class for the <paramref name = "bindable"/> child element.
                /// </summary>
                public static string GetClass(global::Microsoft.Maui.Controls.BindableObject bindable) => (string)bindable.GetValue(ClassProperty);
                /// <summary>
                /// Sets Class for the <paramref name = "bindable"/> child element.
                /// </summary>
                public static void SetClass(global::Microsoft.Maui.Controls.BindableObject bindable, string value) => bindable.SetValue(ClassProperty, value);
                /// <summary>
                /// Attached BindableProperty for the Namespace property.
                /// </summary>
                public static readonly global::Microsoft.Maui.Controls.BindableProperty NamespaceProperty = global::Microsoft.Maui.Controls.BindableProperty.CreateAttached("Namespace", typeof(string), typeof({{defaultTestNamespace}}.{{defaultTestClassName}}), null, (global::Microsoft.Maui.Controls.BindingMode)0, null, null, null, null, null);
                /// <summary>
                /// Gets Namespace for the <paramref name = "bindable"/> child element.
                /// </summary>
                public static string GetNamespace(global::Microsoft.Maui.Controls.BindableObject bindable) => (string)bindable.GetValue(NamespaceProperty);
                /// <summary>
                /// Sets Namespace for the <paramref name = "bindable"/> child element.
                /// </summary>
                public static void SetNamespace(global::Microsoft.Maui.Controls.BindableObject bindable, string value) => bindable.SetValue(NamespaceProperty, value);
            }
            """;

		await VerifySourceGeneratorAsync(source, expectedGenerated);
	}

	[Fact]
	public async Task GenerateAttachedBindableProperty_PropertyIsByteEnum_GeneratesCorrectCode()
	{
		const string source =
			/* language=C#-test */
			//lang=csharp
			$$"""
            using CommunityToolkit.Maui;
            using Microsoft.Maui.Controls;

            namespace {{defaultTestNamespace}};

            [AttachedBindableProperty<Status>("InvoiceStatus", DefaultValue = Status.Approved)]
            public partial class {{defaultTestClassName}} : View
            {
            }
            
            public enum Status : byte
            {
                Pending = 0,
                Approved = 1,
                Rejected = 2
            }
            """;

		const string expectedGenerated =
			/* language=C#-test */
			//lang=csharp
			$$"""
            // <auto-generated>
            // See: CommunityToolkit.Maui.SourceGenerators.Internal.AttachedBindablePropertyAttributeSourceGenerator
            #pragma warning disable
            #nullable enable
            namespace {{defaultTestNamespace}};
            public partial class {{defaultTestClassName}}
            {
                /// <summary>
                /// Attached BindableProperty for the InvoiceStatus property.
                /// </summary>
                public static readonly global::Microsoft.Maui.Controls.BindableProperty InvoiceStatusProperty = global::Microsoft.Maui.Controls.BindableProperty.CreateAttached("InvoiceStatus", typeof(global::{{defaultTestNamespace}}.Status), typeof({{defaultTestNamespace}}.{{defaultTestClassName}}), (global::{{defaultTestNamespace}}.Status)1, (global::Microsoft.Maui.Controls.BindingMode)0, null, null, null, null, null);
                /// <summary>
                /// Gets InvoiceStatus for the <paramref name = "bindable"/> child element.
                /// </summary>
                public static global::{{defaultTestNamespace}}.Status GetInvoiceStatus(global::Microsoft.Maui.Controls.BindableObject bindable) => (global::{{defaultTestNamespace}}.Status)bindable.GetValue(InvoiceStatusProperty);
                /// <summary>
                /// Sets InvoiceStatus for the <paramref name = "bindable"/> child element.
                /// </summary>
                public static void SetInvoiceStatus(global::Microsoft.Maui.Controls.BindableObject bindable, global::{{defaultTestNamespace}}.Status value) => bindable.SetValue(InvoiceStatusProperty, value);
            }
            """;

		await VerifySourceGeneratorAsync(source, expectedGenerated);
	}

	[Fact]
	public async Task GenerateAttachedBindableProperty_PropertyIsLongEnum_GeneratesCorrectCode()
	{
		const string source =
			/* language=C#-test */
			//lang=csharp
			$$"""
            using CommunityToolkit.Maui;
            using Microsoft.Maui.Controls;

            namespace {{defaultTestNamespace}};

            [AttachedBindableProperty<Status>("InvoiceStatus", DefaultValue = Status.Rejected)]
            public partial class {{defaultTestClassName}} : View
            {
            }
            
            public enum Status : long
            {
                Pending = 0,
                Approved = 1,
                Rejected = long.MaxValue
            }
            """;

		const string expectedGenerated =
			/* language=C#-test */
			//lang=csharp
			$$"""
            // <auto-generated>
            // See: CommunityToolkit.Maui.SourceGenerators.Internal.AttachedBindablePropertyAttributeSourceGenerator
            #pragma warning disable
            #nullable enable
            namespace {{defaultTestNamespace}};
            public partial class {{defaultTestClassName}}
            {
                /// <summary>
                /// Attached BindableProperty for the InvoiceStatus property.
                /// </summary>
                public static readonly global::Microsoft.Maui.Controls.BindableProperty InvoiceStatusProperty = global::Microsoft.Maui.Controls.BindableProperty.CreateAttached("InvoiceStatus", typeof(global::{{defaultTestNamespace}}.Status), typeof({{defaultTestNamespace}}.{{defaultTestClassName}}), (global::{{defaultTestNamespace}}.Status)9223372036854775807L, (global::Microsoft.Maui.Controls.BindingMode)0, null, null, null, null, null);
                /// <summary>
                /// Gets InvoiceStatus for the <paramref name = "bindable"/> child element.
                /// </summary>
                public static global::{{defaultTestNamespace}}.Status GetInvoiceStatus(global::Microsoft.Maui.Controls.BindableObject bindable) => (global::{{defaultTestNamespace}}.Status)bindable.GetValue(InvoiceStatusProperty);
                /// <summary>
                /// Sets InvoiceStatus for the <paramref name = "bindable"/> child element.
                /// </summary>
                public static void SetInvoiceStatus(global::Microsoft.Maui.Controls.BindableObject bindable, global::{{defaultTestNamespace}}.Status value) => bindable.SetValue(InvoiceStatusProperty, value);
            }
            """;

		await VerifySourceGeneratorAsync(source, expectedGenerated);
	}

	[Fact]
	public async Task GenerateAttachedBindableProperty_NullableValueTypes_GeneratesCorrectCode()
	{
		const string source =
			/* language=C#-test */
			//lang=csharp
			$$"""			
            using System;
            using CommunityToolkit.Maui;
            using Microsoft.Maui.Controls;

            namespace {{defaultTestNamespace}};

            [AttachedBindableProperty<int?>("NullableInt", IsNullable = true)]
            [AttachedBindableProperty<DateTime?>("NullableDateTime", IsNullable = true)]
            [AttachedBindableProperty<bool?>("NullableBool", IsNullable = true)]
            public partial class {{defaultTestClassName}} : View
            {
            }
            """;

		const string expectedGenerated =
			/* language=C#-test */
			//lang=csharp
			$$"""
            // <auto-generated>
            // See: CommunityToolkit.Maui.SourceGenerators.Internal.AttachedBindablePropertyAttributeSourceGenerator
            #pragma warning disable
            #nullable enable
            namespace {{defaultTestNamespace}};
            public partial class {{defaultTestClassName}}
            {
                /// <summary>
                /// Attached BindableProperty for the NullableInt property.
                /// </summary>
                public static readonly global::Microsoft.Maui.Controls.BindableProperty NullableIntProperty = global::Microsoft.Maui.Controls.BindableProperty.CreateAttached("NullableInt", typeof(int), typeof({{defaultTestNamespace}}.{{defaultTestClassName}}), null, (global::Microsoft.Maui.Controls.BindingMode)0, null, null, null, null, null);
                /// <summary>
                /// Gets NullableInt for the <paramref name = "bindable"/> child element.
                /// </summary>
                public static int? GetNullableInt(global::Microsoft.Maui.Controls.BindableObject bindable) => (int? )bindable.GetValue(NullableIntProperty);
                /// <summary>
                /// Sets NullableInt for the <paramref name = "bindable"/> child element.
                /// </summary>
                public static void SetNullableInt(global::Microsoft.Maui.Controls.BindableObject bindable, int? value) => bindable.SetValue(NullableIntProperty, value);
                /// <summary>
                /// Attached BindableProperty for the NullableDateTime property.
                /// </summary>
                public static readonly global::Microsoft.Maui.Controls.BindableProperty NullableDateTimeProperty = global::Microsoft.Maui.Controls.BindableProperty.CreateAttached("NullableDateTime", typeof(global::System.DateTime), typeof({{defaultTestNamespace}}.{{defaultTestClassName}}), null, (global::Microsoft.Maui.Controls.BindingMode)0, null, null, null, null, null);
                /// <summary>
                /// Gets NullableDateTime for the <paramref name = "bindable"/> child element.
                /// </summary>
                public static global::System.DateTime? GetNullableDateTime(global::Microsoft.Maui.Controls.BindableObject bindable) => (global::System.DateTime? )bindable.GetValue(NullableDateTimeProperty);
                /// <summary>
                /// Sets NullableDateTime for the <paramref name = "bindable"/> child element.
                /// </summary>
                public static void SetNullableDateTime(global::Microsoft.Maui.Controls.BindableObject bindable, global::System.DateTime? value) => bindable.SetValue(NullableDateTimeProperty, value);
                /// <summary>
                /// Attached BindableProperty for the NullableBool property.
                /// </summary>
                public static readonly global::Microsoft.Maui.Controls.BindableProperty NullableBoolProperty = global::Microsoft.Maui.Controls.BindableProperty.CreateAttached("NullableBool", typeof(bool), typeof({{defaultTestNamespace}}.{{defaultTestClassName}}), null, (global::Microsoft.Maui.Controls.BindingMode)0, null, null, null, null, null);
                /// <summary>
                /// Gets NullableBool for the <paramref name = "bindable"/> child element.
                /// </summary>
                public static bool? GetNullableBool(global::Microsoft.Maui.Controls.BindableObject bindable) => (bool? )bindable.GetValue(NullableBoolProperty);
                /// <summary>
                /// Sets NullableBool for the <paramref name = "bindable"/> child element.
                /// </summary>
                public static void SetNullableBool(global::Microsoft.Maui.Controls.BindableObject bindable, bool? value) => bindable.SetValue(NullableBoolProperty, value);
            }
            """;

		await VerifySourceGeneratorAsync(source, expectedGenerated);
	}

	[Fact]
	public async Task GenerateAttachedBindableProperty_ArrayTypes_GeneratesCorrectCode()
	{
		const string source =
			/* language=C#-test */
			//lang=csharp
			$$"""
            using CommunityToolkit.Maui;
            using Microsoft.Maui.Controls;

            namespace {{defaultTestNamespace}};

            [AttachedBindableProperty<string[]>("StringArray")]
            [AttachedBindableProperty<int[,]>("MultiDimensionalArray")]
            [AttachedBindableProperty<byte[][]>("JaggedArray")]
            public partial class {{defaultTestClassName}} : View
            {
            }
            """;

		const string expectedGenerated =
			/* language=C#-test */
			//lang=csharp
			$$"""
            // <auto-generated>
            // See: CommunityToolkit.Maui.SourceGenerators.Internal.AttachedBindablePropertyAttributeSourceGenerator
            #pragma warning disable
            #nullable enable
            namespace {{defaultTestNamespace}};
            public partial class {{defaultTestClassName}}
            {
                /// <summary>
                /// Attached BindableProperty for the StringArray property.
                /// </summary>
                public static readonly global::Microsoft.Maui.Controls.BindableProperty StringArrayProperty = global::Microsoft.Maui.Controls.BindableProperty.CreateAttached("StringArray", typeof(string[]), typeof({{defaultTestNamespace}}.{{defaultTestClassName}}), null, (global::Microsoft.Maui.Controls.BindingMode)0, null, null, null, null, null);
                /// <summary>
                /// Gets StringArray for the <paramref name = "bindable"/> child element.
                /// </summary>
                public static string[] GetStringArray(global::Microsoft.Maui.Controls.BindableObject bindable) => (string[])bindable.GetValue(StringArrayProperty);
                /// <summary>
                /// Sets StringArray for the <paramref name = "bindable"/> child element.
                /// </summary>
                public static void SetStringArray(global::Microsoft.Maui.Controls.BindableObject bindable, string[] value) => bindable.SetValue(StringArrayProperty, value);
                /// <summary>
                /// Attached BindableProperty for the MultiDimensionalArray property.
                /// </summary>
                public static readonly global::Microsoft.Maui.Controls.BindableProperty MultiDimensionalArrayProperty = global::Microsoft.Maui.Controls.BindableProperty.CreateAttached("MultiDimensionalArray", typeof(int[, ]), typeof({{defaultTestNamespace}}.{{defaultTestClassName}}), null, (global::Microsoft.Maui.Controls.BindingMode)0, null, null, null, null, null);
                /// <summary>
                /// Gets MultiDimensionalArray for the <paramref name = "bindable"/> child element.
                /// </summary>
                public static int[, ] GetMultiDimensionalArray(global::Microsoft.Maui.Controls.BindableObject bindable) => (int[, ])bindable.GetValue(MultiDimensionalArrayProperty);
                /// <summary>
                /// Sets MultiDimensionalArray for the <paramref name = "bindable"/> child element.
                /// </summary>
                public static void SetMultiDimensionalArray(global::Microsoft.Maui.Controls.BindableObject bindable, int[, ] value) => bindable.SetValue(MultiDimensionalArrayProperty, value);
                /// <summary>
                /// Attached BindableProperty for the JaggedArray property.
                /// </summary>
                public static readonly global::Microsoft.Maui.Controls.BindableProperty JaggedArrayProperty = global::Microsoft.Maui.Controls.BindableProperty.CreateAttached("JaggedArray", typeof(byte[][]), typeof({{defaultTestNamespace}}.{{defaultTestClassName}}), null, (global::Microsoft.Maui.Controls.BindingMode)0, null, null, null, null, null);
                /// <summary>
                /// Gets JaggedArray for the <paramref name = "bindable"/> child element.
                /// </summary>
                public static byte[][] GetJaggedArray(global::Microsoft.Maui.Controls.BindableObject bindable) => (byte[][])bindable.GetValue(JaggedArrayProperty);
                /// <summary>
                /// Sets JaggedArray for the <paramref name = "bindable"/> child element.
                /// </summary>
                public static void SetJaggedArray(global::Microsoft.Maui.Controls.BindableObject bindable, byte[][] value) => bindable.SetValue(JaggedArrayProperty, value);
            }
            """;

		await VerifySourceGeneratorAsync(source, expectedGenerated);
	}

	[Fact]
	public async Task GenerateAttachedBindableProperty_LongNamespaces_GeneratesCorrectCode()
	{
		const string source =
			/* language=C#-test */
			//lang=csharp
			$$"""
            using CommunityToolkit.Maui;
            using Microsoft.Maui.Controls;

            namespace Very.Long.Namespace.With.Many.Segments.TestNamespace;

            [AttachedBindableProperty<string>("Text")]
            public partial class {{defaultTestClassName}} : View
            {
            }
            """;

		const string expectedGenerated =
			/* language=C#-test */
			//lang=csharp
			$$"""
			// <auto-generated>
			// See: CommunityToolkit.Maui.SourceGenerators.Internal.AttachedBindablePropertyAttributeSourceGenerator
			#pragma warning disable
			#nullable enable
			namespace Very.Long.Namespace.With.Many.Segments.TestNamespace;
			public partial class {{defaultTestClassName}}
			{
			    /// <summary>
			    /// Attached BindableProperty for the Text property.
			    /// </summary>
			    public static readonly global::Microsoft.Maui.Controls.BindableProperty TextProperty = global::Microsoft.Maui.Controls.BindableProperty.CreateAttached("Text", typeof(string), typeof(Very.Long.Namespace.With.Many.Segments.TestNamespace.{{defaultTestClassName}}), null, (global::Microsoft.Maui.Controls.BindingMode)0, null, null, null, null, null);
			    /// <summary>
			    /// Gets Text for the <paramref name = "bindable"/> child element.
			    /// </summary>
			    public static string GetText(global::Microsoft.Maui.Controls.BindableObject bindable) => (string)bindable.GetValue(TextProperty);
			    /// <summary>
			    /// Sets Text for the <paramref name = "bindable"/> child element.
			    /// </summary>
			    public static void SetText(global::Microsoft.Maui.Controls.BindableObject bindable, string value) => bindable.SetValue(TextProperty, value);
			}
			""";

		await VerifySourceGeneratorAsync(source, expectedGenerated);
	}

	[Fact]
	public async Task GenerateAttachedBindableProperty_GlobalNamespace_GeneratesCorrectCode()
	{
		const string source =
			/* language=C#-test */
			//lang=csharp
			$$"""
            using CommunityToolkit.Maui;
            using Microsoft.Maui.Controls;

            [AttachedBindableProperty<string>("Text")]
            public partial class {{defaultTestClassName}} : View
            {
            }
            """;

		const string expectedGenerated =
			/* language=C#-test */
			//lang=csharp
			$$"""
			// <auto-generated>
			// See: CommunityToolkit.Maui.SourceGenerators.Internal.AttachedBindablePropertyAttributeSourceGenerator
			#pragma warning disable
			#nullable enable
			public partial class {{defaultTestClassName}}
			{
			    /// <summary>
			    /// Attached BindableProperty for the Text property.
			    /// </summary>
			    public static readonly global::Microsoft.Maui.Controls.BindableProperty TextProperty = global::Microsoft.Maui.Controls.BindableProperty.CreateAttached("Text", typeof(string), typeof({{defaultTestClassName}}), null, (global::Microsoft.Maui.Controls.BindingMode)0, null, null, null, null, null);
			    /// <summary>
			    /// Gets Text for the <paramref name = "bindable"/> child element.
			    /// </summary>
			    public static string GetText(global::Microsoft.Maui.Controls.BindableObject bindable) => (string)bindable.GetValue(TextProperty);
			    /// <summary>
			    /// Sets Text for the <paramref name = "bindable"/> child element.
			    /// </summary>
			    public static void SetText(global::Microsoft.Maui.Controls.BindableObject bindable, string value) => bindable.SetValue(TextProperty, value);
			}
			""";

		await VerifySourceGeneratorAsync(source, expectedGenerated);
	}

	[Fact]
	public async Task GenerateAttachedBindableProperty_SpecialCharactersInPropertyName_GeneratesCorrectCode()
	{
		const string source =
			/* language=C#-test */
			//lang=csharp
			$$"""
            using CommunityToolkit.Maui;
            using Microsoft.Maui.Controls;

            namespace {{defaultTestNamespace}};

            [AttachedBindableProperty<string>("Property_With_Underscores")]
            [AttachedBindableProperty<string>("Property123WithNumbers")]
            public partial class {{defaultTestClassName}} : View
            {
            }
            """;

		const string expectedGenerated =
			/* language=C#-test */
			//lang=csharp
			$$"""
			// <auto-generated>
			// See: CommunityToolkit.Maui.SourceGenerators.Internal.AttachedBindablePropertyAttributeSourceGenerator
			#pragma warning disable
			#nullable enable
			namespace {{defaultTestNamespace}};
			public partial class {{defaultTestClassName}}
			{
			    /// <summary>
			    /// Attached BindableProperty for the Property_With_Underscores property.
			    /// </summary>
			    public static readonly global::Microsoft.Maui.Controls.BindableProperty Property_With_UnderscoresProperty = global::Microsoft.Maui.Controls.BindableProperty.CreateAttached("Property_With_Underscores", typeof(string), typeof({{defaultTestNamespace}}.{{defaultTestClassName}}), null, (global::Microsoft.Maui.Controls.BindingMode)0, null, null, null, null, null);
			    /// <summary>
			    /// Gets Property_With_Underscores for the <paramref name = "bindable"/> child element.
			    /// </summary>
			    public static string GetProperty_With_Underscores(global::Microsoft.Maui.Controls.BindableObject bindable) => (string)bindable.GetValue(Property_With_UnderscoresProperty);
			    /// <summary>
			    /// Sets Property_With_Underscores for the <paramref name = "bindable"/> child element.
			    /// </summary>
			    public static void SetProperty_With_Underscores(global::Microsoft.Maui.Controls.BindableObject bindable, string value) => bindable.SetValue(Property_With_UnderscoresProperty, value);
			    /// <summary>
			    /// Attached BindableProperty for the Property123WithNumbers property.
			    /// </summary>
			    public static readonly global::Microsoft.Maui.Controls.BindableProperty Property123WithNumbersProperty = global::Microsoft.Maui.Controls.BindableProperty.CreateAttached("Property123WithNumbers", typeof(string), typeof({{defaultTestNamespace}}.{{defaultTestClassName}}), null, (global::Microsoft.Maui.Controls.BindingMode)0, null, null, null, null, null);
			    /// <summary>
			    /// Gets Property123WithNumbers for the <paramref name = "bindable"/> child element.
			    /// </summary>
			    public static string GetProperty123WithNumbers(global::Microsoft.Maui.Controls.BindableObject bindable) => (string)bindable.GetValue(Property123WithNumbersProperty);
			    /// <summary>
			    /// Sets Property123WithNumbers for the <paramref name = "bindable"/> child element.
			    /// </summary>
			    public static void SetProperty123WithNumbers(global::Microsoft.Maui.Controls.BindableObject bindable, string value) => bindable.SetValue(Property123WithNumbersProperty, value);
			}
			""";

		await VerifySourceGeneratorAsync(source, expectedGenerated);
	}

	[Fact]
	public async Task GenerateAttachedBindableProperty_WithComplexDefaultValues_GeneratesCorrectCode()
	{
		const string source =
			/* language=C#-test */
			//lang=csharp
			$$"""
            using CommunityToolkit.Maui;
            using Microsoft.Maui.Controls;
            using System;

            namespace {{defaultTestNamespace}};

            [AttachedBindableProperty<bool>("IsEnabled", DefaultValue = true)]
            [AttachedBindableProperty<double>("Pi", DefaultValue = 3.14)]
            [AttachedBindableProperty<char>("Letter", DefaultValue = 'A')]
            [AttachedBindableProperty<double>("DoubleEpsilon", DefaultValue = double.Epsilon)]
            [AttachedBindableProperty<float>("SingleEpsilon", DefaultValue = float.Epsilon)]
            public partial class {{defaultTestClassName}} : View
            {
            }
            """;

		const string expectedGenerated =
			/* language=C#-test */
			//lang=csharp
			$$"""
            // <auto-generated>
            // See: CommunityToolkit.Maui.SourceGenerators.Internal.AttachedBindablePropertyAttributeSourceGenerator
            #pragma warning disable
            #nullable enable
            namespace {{defaultTestNamespace}};
            public partial class {{defaultTestClassName}}
            {
                /// <summary>
                /// Attached BindableProperty for the IsEnabled property.
                /// </summary>
                public static readonly global::Microsoft.Maui.Controls.BindableProperty IsEnabledProperty = global::Microsoft.Maui.Controls.BindableProperty.CreateAttached("IsEnabled", typeof(bool), typeof({{defaultTestNamespace}}.{{defaultTestClassName}}), (bool)true, (global::Microsoft.Maui.Controls.BindingMode)0, null, null, null, null, null);
                /// <summary>
                /// Gets IsEnabled for the <paramref name = "bindable"/> child element.
                /// </summary>
                public static bool GetIsEnabled(global::Microsoft.Maui.Controls.BindableObject bindable) => (bool)bindable.GetValue(IsEnabledProperty);
                /// <summary>
                /// Sets IsEnabled for the <paramref name = "bindable"/> child element.
                /// </summary>
                public static void SetIsEnabled(global::Microsoft.Maui.Controls.BindableObject bindable, bool value) => bindable.SetValue(IsEnabledProperty, value);
                /// <summary>
                /// Attached BindableProperty for the Pi property.
                /// </summary>
                public static readonly global::Microsoft.Maui.Controls.BindableProperty PiProperty = global::Microsoft.Maui.Controls.BindableProperty.CreateAttached("Pi", typeof(double), typeof({{defaultTestNamespace}}.{{defaultTestClassName}}), (double)3.1400000000000001, (global::Microsoft.Maui.Controls.BindingMode)0, null, null, null, null, null);
                /// <summary>
                /// Gets Pi for the <paramref name = "bindable"/> child element.
                /// </summary>
                public static double GetPi(global::Microsoft.Maui.Controls.BindableObject bindable) => (double)bindable.GetValue(PiProperty);
                /// <summary>
                /// Sets Pi for the <paramref name = "bindable"/> child element.
                /// </summary>
                public static void SetPi(global::Microsoft.Maui.Controls.BindableObject bindable, double value) => bindable.SetValue(PiProperty, value);
                /// <summary>
                /// Attached BindableProperty for the Letter property.
                /// </summary>
                public static readonly global::Microsoft.Maui.Controls.BindableProperty LetterProperty = global::Microsoft.Maui.Controls.BindableProperty.CreateAttached("Letter", typeof(char), typeof({{defaultTestNamespace}}.{{defaultTestClassName}}), (char)'A', (global::Microsoft.Maui.Controls.BindingMode)0, null, null, null, null, null);
                /// <summary>
                /// Gets Letter for the <paramref name = "bindable"/> child element.
                /// </summary>
                public static char GetLetter(global::Microsoft.Maui.Controls.BindableObject bindable) => (char)bindable.GetValue(LetterProperty);
                /// <summary>
                /// Sets Letter for the <paramref name = "bindable"/> child element.
                /// </summary>
                public static void SetLetter(global::Microsoft.Maui.Controls.BindableObject bindable, char value) => bindable.SetValue(LetterProperty, value);
                /// <summary>
                /// Attached BindableProperty for the DoubleEpsilon property.
                /// </summary>
                public static readonly global::Microsoft.Maui.Controls.BindableProperty DoubleEpsilonProperty = global::Microsoft.Maui.Controls.BindableProperty.CreateAttached("DoubleEpsilon", typeof(double), typeof({{defaultTestNamespace}}.{{defaultTestClassName}}), (double)double.Epsilon, (global::Microsoft.Maui.Controls.BindingMode)0, null, null, null, null, null);
                /// <summary>
                /// Gets DoubleEpsilon for the <paramref name = "bindable"/> child element.
                /// </summary>
                public static double GetDoubleEpsilon(global::Microsoft.Maui.Controls.BindableObject bindable) => (double)bindable.GetValue(DoubleEpsilonProperty);
                /// <summary>
                /// Sets DoubleEpsilon for the <paramref name = "bindable"/> child element.
                /// </summary>
                public static void SetDoubleEpsilon(global::Microsoft.Maui.Controls.BindableObject bindable, double value) => bindable.SetValue(DoubleEpsilonProperty, value);
                /// <summary>
                /// Attached BindableProperty for the SingleEpsilon property.
                /// </summary>
                public static readonly global::Microsoft.Maui.Controls.BindableProperty SingleEpsilonProperty = global::Microsoft.Maui.Controls.BindableProperty.CreateAttached("SingleEpsilon", typeof(float), typeof({{defaultTestNamespace}}.{{defaultTestClassName}}), (float)float.Epsilon, (global::Microsoft.Maui.Controls.BindingMode)0, null, null, null, null, null);
                /// <summary>
                /// Gets SingleEpsilon for the <paramref name = "bindable"/> child element.
                /// </summary>
                public static float GetSingleEpsilon(global::Microsoft.Maui.Controls.BindableObject bindable) => (float)bindable.GetValue(SingleEpsilonProperty);
                /// <summary>
                /// Sets SingleEpsilon for the <paramref name = "bindable"/> child element.
                /// </summary>
                public static void SetSingleEpsilon(global::Microsoft.Maui.Controls.BindableObject bindable, float value) => bindable.SetValue(SingleEpsilonProperty, value);
            }
            """;

		await VerifySourceGeneratorAsync(source, expectedGenerated);
	}

	[Fact]
	public async Task GenerateAttachedBindableProperty_WithBothInitializerAndDefault_GeneratedCodeSetsBothValues()
	{
		const string source =
			/* language=C#-test */
			//lang=csharp
			$$"""
			using CommunityToolkit.Maui;
			using Microsoft.Maui.Controls;
			using System;

			namespace {{defaultTestNamespace}};

			[AttachedBindablePropertyAttribute<string>("Text", DefaultValue = "Initial Value", DefaultValueCreatorMethodName = nameof(CreateDefaultText))]
			public partial class {{defaultTestClassName}} : View
			{
				static string CreateDefaultText(global::Microsoft.Maui.Controls.BindableObject bindable)
				{
					return "Initial Value";
				}
			}
			""";

		const string expectedGenerated =
			/* language=C#-test */
			//lang=csharp
			$$"""
			// <auto-generated>
			// See: CommunityToolkit.Maui.SourceGenerators.Internal.AttachedBindablePropertyAttributeSourceGenerator
			#pragma warning disable
			#nullable enable
			namespace {{defaultTestNamespace}};
			public partial class {{defaultTestClassName}}
			{
			    /// <summary>
			    /// Attached BindableProperty for the Text property.
			    /// </summary>
			    public static readonly global::Microsoft.Maui.Controls.BindableProperty TextProperty = global::Microsoft.Maui.Controls.BindableProperty.CreateAttached("Text", typeof(string), typeof({{defaultTestNamespace}}.{{defaultTestClassName}}), (string)"Initial Value", (global::Microsoft.Maui.Controls.BindingMode)0, null, null, null, null, CreateDefaultText);
			    /// <summary>
			    /// Gets Text for the <paramref name = "bindable"/> child element.
			    /// </summary>
			    public static string GetText(global::Microsoft.Maui.Controls.BindableObject bindable) => (string)bindable.GetValue(TextProperty);
			    /// <summary>
			    /// Sets Text for the <paramref name = "bindable"/> child element.
			    /// </summary>
			    public static void SetText(global::Microsoft.Maui.Controls.BindableObject bindable, string value) => bindable.SetValue(TextProperty, value);
			}
			""";

		await VerifySourceGeneratorAsync(source, expectedGenerated);
	}
}