using Xunit;

namespace CommunityToolkit.Maui.SourceGenerators.Internal.UnitTests.AttachedBindablePropertyAttributeSourceGeneratorTests;

public class AttachedBindablePropertyAttributeSourceGenerator_ConstructorAttribute_IntegrationTests : BaseAttachedBindablePropertyAttributeSourceGeneratorTest
{
	[Fact]
	public async Task GenerateAttachedBindableProperty_ComplexInheritanceScenario_GeneratesCorrectCode()
	{
		const string source =
			/* language=C#-test */
			//lang=csharp
			$$"""
			using CommunityToolkit.Maui;
			using Microsoft.Maui.Controls;

			namespace {{defaultTestNamespace}};

			public abstract partial class BaseView : View
			{
				[AttachedBindablePropertyAttribute<string>("Text")]
				protected BaseView()
				{
				}
			}

			public partial class DerivedView : BaseView
			{
				[AttachedBindablePropertyAttribute<string>("DerivedText")]
				public DerivedView()
				{
				}
			}
			""";

		const string expectedBaseGenerated =
			/* language=C#-test */
			//lang=csharp
			$$"""
			// <auto-generated>
			// See: CommunityToolkit.Maui.SourceGenerators.Internal.AttachedBindablePropertyAttributeSourceGenerator
			#pragma warning disable
			#nullable enable
			namespace {{defaultTestNamespace}};
			public partial class {{defaultTestClassName}}
			{
			    /// <summary>
			    /// Attached BindableProperty for the Text property.
			    /// </summary>
			    public static readonly global::Microsoft.Maui.Controls.BindableProperty TextProperty = global::Microsoft.Maui.Controls.BindableProperty.CreateAttached("Text", typeof(string), typeof({{defaultTestNamespace}}.BaseView), null, Microsoft.Maui.Controls.BindingMode.OneWay, null, null, null, null, null);
			    /// <summary>
			    /// Gets Text for the <paramref =  " bindable " /> child element.
			    /// </summary>
			    public static string GetText(global::Microsoft.Maui.Controls.BindableObject bindable) => (string)bindable.GetValue(TextProperty);
			    /// <summary>
			    /// Sets Text for the <paramref =  " bindable " /> child element.
			    /// </summary>
			    public static void SetText(global::Microsoft.Maui.Controls.BindableObject bindable, string value) => bindable.SetValue(TextProperty, value);
			}
			""";

		const string expectedDerivedGenerated =
			/* language=C#-test */
			//lang=csharp
			$$"""
			// <auto-generated>
			// See: CommunityToolkit.Maui.SourceGenerators.Internal.AttachedBindablePropertyAttributeSourceGenerator
			#pragma warning disable
			#nullable enable
			namespace {{defaultTestNamespace}};
			public partial class {{defaultTestClassName}}
			{
			    /// <summary>
			    /// Attached BindableProperty for the DerivedText property.
			    /// </summary>
			    public static readonly global::Microsoft.Maui.Controls.BindableProperty DerivedTextProperty = global::Microsoft.Maui.Controls.BindableProperty.CreateAttached("DerivedText", typeof(string), typeof({{defaultTestNamespace}}.DerivedView), null, Microsoft.Maui.Controls.BindingMode.OneWay, null, null, null, null, null);
			    /// <summary>
			    /// Gets Text for the <paramref =  " bindable " /> child element.
			    /// </summary>
			    public static string GetDerivedText(global::Microsoft.Maui.Controls.BindableObject bindable) => (string)bindable.GetValue(TextProperty);
			    /// <summary>
			    /// Sets Text for the <paramref =  " bindable " /> child element.
			    /// </summary>
			    public static void SetDerivedText(global::Microsoft.Maui.Controls.BindableObject bindable, string value) => bindable.SetValue(TextProperty, value);
			}
			""";

		await VerifySourceGeneratorAsync(source, expectedAttribute, ("BaseView.g.cs", expectedBaseGenerated), ("DerivedView.g.cs", expectedDerivedGenerated));
	}

	[Fact]
	public async Task GenerateAttachedBindableProperty_GenericClass_GeneratesCorrectCode()
	{
		const string source =
			/* language=C#-test */
			//lang=csharp
			$$"""
		    using CommunityToolkit.Maui;
		    using Microsoft.Maui.Controls;

		    namespace {{defaultTestNamespace}};

		    public partial class {{defaultTestClassName}}<TSourceGenerator,U> : View where TSourceGenerator : class
		    {
		    	[AttachedBindablePropertyAttribute<string>("Text")]
		    	public {{defaultTestClassName}}()
		    	{
		    	}
		    }
		    """;

		const string expectedGenerated =
			/* language=C#-test */
			//lang=csharp
			$$"""
			// <auto-generated>
			// See: CommunityToolkit.Maui.SourceGenerators.Internal.AttachedBindablePropertyAttributeSourceGenerator
			#pragma warning disable
			#nullable enable
			namespace {{defaultTestNamespace}};
			public partial class {{defaultTestClassName}}<TSourceGenerator, U>
			{
			    /// <summary>
			    /// Attached BindableProperty for the Text property.
			    /// </summary>
			    public static readonly global::Microsoft.Maui.Controls.BindableProperty TextProperty = global::Microsoft.Maui.Controls.BindableProperty.CreateAttached("Text", typeof(string), typeof({{defaultTestNamespace}}.{{defaultTestClassName}}<TSourceGenerator, U>), null, Microsoft.Maui.Controls.BindingMode.OneWay, null, null, null, null, null);
			    /// <summary>
			    /// Gets Text for the <paramref =  " bindable " /> child element.
			    /// </summary>
			    public static string GetText(global::Microsoft.Maui.Controls.BindableObject bindable) => (string)bindable.GetValue(TextProperty);
			    /// <summary>
			    /// Sets Text for the <paramref =  " bindable " /> child element.
			    /// </summary>
			    public static void SetText(global::Microsoft.Maui.Controls.BindableObject bindable, string value) => bindable.SetValue(TextProperty, value);
			}
			""";

		await VerifySourceGeneratorAsync(source, expectedGenerated);
	}

	[Fact]
	public async Task GenerateAttachedBindableProperty_AttributeOnNestedInnerClass_GeneratesCorrectCode()
	{
		const string outerClassName = "Outerclass";

		const string source =
			/* language=C#-test */
			//lang=csharp
			$$"""
		    using CommunityToolkit.Maui;
		    using Microsoft.Maui.Controls;

		    namespace {{defaultTestNamespace}};

		    public partial class {{outerClassName}}
		    {
		    	public {{outerClassName}}()
		    	{
		    	}

		        public partial class {{defaultTestClassName}} : View
		        {
		    		[AttachedBindablePropertyAttribute<string>("Text")]
		    		public {{defaultTestClassName}}()
		    		{
		    		}
		        }
		    }
		    """;

		const string expectedGenerated =
			/* language=C#-test */
			//lang=csharp
			$$$""""
			// <auto-generated>
			// See: CommunityToolkit.Maui.SourceGenerators.Internal.AttachedBindablePropertyAttributeSourceGenerator
			#pragma warning disable
			#nullable enable
			namespace {{{defaultTestNamespace}}};
			public partial class {{{outerClassName}}}
			{
				public partial class {{{defaultTestClassName}}}
				{
				    /// <summary>
				    /// Attached BindableProperty for the Text property.
				    /// </summary>
				    public static readonly global::Microsoft.Maui.Controls.BindableProperty TextProperty = global::Microsoft.Maui.Controls.BindableProperty.CreateAttached("Text", typeof(string), typeof({{{defaultTestNamespace}}}.{{{outerClassName}}}.{{{defaultTestClassName}}}), null, Microsoft.Maui.Controls.BindingMode.OneWay, null, null, null, null, null);
				    /// <summary>
				    /// Gets Text for the <paramref =  " bindable " /> child element.
				    /// </summary>
				    public static string GetText(global::Microsoft.Maui.Controls.BindableObject bindable) => (string)bindable.GetValue(TextProperty);
				    /// <summary>
				    /// Sets Text for the <paramref =  " bindable " /> child element.
				    /// </summary>
				    public static void SetText(global::Microsoft.Maui.Controls.BindableObject bindable, string value) => bindable.SetValue(TextProperty, value);
				}
			}
			"""";

		await VerifySourceGeneratorAsync(source, expectedAttribute, ($"{outerClassName}.{defaultTestClassName}.g.cs", expectedGenerated));
	}

	[Fact]
	public async Task GenerateAttachedBindableProperty_NestedInnerClassWithAttributeOnOutterClass_GeneratesCorrectCode()
	{
		const string outerClassName = "Outerclass";

		const string source =
			/* language=C#-test */
			//lang=csharp
			$$"""
		    using CommunityToolkit.Maui;
		    using Microsoft.Maui.Controls;

		    namespace {{defaultTestNamespace}};

		    public partial class {{outerClassName}} : View
		    {
		        [AttachedBindablePropertyAttribute<string>("Text")]
		    	public {{outerClassName}}()
		    	{
		    	}

		        public partial class {{defaultTestClassName}} : View
		        {
		    		public {{defaultTestClassName}}()
		    		{
		    		}
		        }
		    }
		    """;

		const string expectedGenerated =
			/* language=C#-test */
			//lang=csharp
			$$$""""
			// <auto-generated>
			// See: CommunityToolkit.Maui.SourceGenerators.Internal.AttachedBindablePropertyAttributeSourceGenerator
			#pragma warning disable
			#nullable enable
			namespace {{{defaultTestNamespace}}};
			public partial class {{{outerClassName}}}
			{
				/// <summary>
				/// Attached BindableProperty for the Text property.
				/// </summary>
				public static readonly global::Microsoft.Maui.Controls.BindableProperty TextProperty = global::Microsoft.Maui.Controls.BindableProperty.CreateAttached("Text", typeof(string), typeof({{{defaultTestNamespace}}}.{{{outerClassName}}}), null, Microsoft.Maui.Controls.BindingMode.OneWay, null, null, null, null, null);
				/// <summary>
				/// Gets Text for the <paramref =  " bindable " /> child element.
				/// </summary>
				public static string GetText(global::Microsoft.Maui.Controls.BindableObject bindable) => (string)bindable.GetValue(TextProperty);
				/// <summary>
				/// Sets Text for the <paramref =  " bindable " /> child element.
				/// </summary>
				public static void SetText(global::Microsoft.Maui.Controls.BindableObject bindable, string value) => bindable.SetValue(TextProperty, value);
			}
			"""";

		await VerifySourceGeneratorAsync(source, expectedGenerated);
	}

	[Fact]
	public async Task GenerateAttachedBindableProperty_WithCustomTypes_GeneratesCorrectCode()
	{
		const string source =
			/* language=C#-test */
			//lang=csharp
			$$"""
		    using CommunityToolkit.Maui;
		    using Microsoft.Maui.Controls;
		    using System.Collections.Generic;

		    namespace {{defaultTestNamespace}};

		    public class CustomModel
		    {
		        public string Name { get; set; }
		    }

		    public partial class {{defaultTestClassName}} : View
		    {
		        [AttachedBindablePropertyAttribute<CustomModel?>("Model")]
		    	public {{defaultTestClassName}}()
		    	{
		    	}
		    }
		    """;

		const string expectedGenerated =
			/* language=C#-test */
			//lang=csharp
			$$"""
			// <auto-generated>
			// See: CommunityToolkit.Maui.SourceGenerators.Internal.AttachedBindablePropertyAttributeSourceGenerator
			#pragma warning disable
			#nullable enable
			namespace {{defaultTestNamespace}};
			public partial class {{defaultTestClassName}}
			{
			    /// <summary>
			    /// Attached BindableProperty for the Model property.
			    /// </summary>
			    public static readonly global::Microsoft.Maui.Controls.BindableProperty ModelProperty = global::Microsoft.Maui.Controls.BindableProperty.CreateAttached("Model", typeof({{defaultTestNamespace}}.CustomModel), typeof({{defaultTestNamespace}}.{{defaultTestClassName}}), null, Microsoft.Maui.Controls.BindingMode.OneWay, null, null, null, null, null);
			    /// <summary>
			    /// Gets Model for the <paramref =  " bindable " /> child element.
			    /// </summary>
			    public static {{defaultTestNamespace}}.CustomModel GetModel(global::Microsoft.Maui.Controls.BindableObject bindable) => ({{defaultTestNamespace}}.CustomModel)bindable.GetValue(TextProperty);
			    /// <summary>
			    /// Sets Model for the <paramref =  " bindable " /> child element.
			    /// </summary>
			    public static void SetModel(global::Microsoft.Maui.Controls.BindableObject bindable, {{defaultTestNamespace}}.CustomModel value) => bindable.SetValue(TextProperty, value);
			}
			""";

		await VerifySourceGeneratorAsync(source, expectedGenerated);
	}

	[Fact]
	public async Task GenerateAttachedBindableProperty_MultipleClassesInSameFile_GeneratesCorrectCode()
	{
		const string source =
			/* language=C#-test */
			//lang=csharp
			$$"""
		    using CommunityToolkit.Maui;
		    using Microsoft.Maui.Controls;

		    namespace {{defaultTestNamespace}};

		    public partial class FirstView : View
		    {
		        [AttachedBindablePropertyAttribute<string>("FirstText")]
		    	public FirstView()
		    	{
		    	}
		    }

		    public partial class SecondView : View
		    {
		        [AttachedBindablePropertyAttribute<string>("SecondText")]
		    	public SecondView()
		    	{
		    	}
		    }
		    """;

		const string expectedFirstGenerated =
			/* language=C#-test */
			//lang=csharp
			$$"""
			// <auto-generated>
			// See: CommunityToolkit.Maui.SourceGenerators.Internal.AttachedBindablePropertyAttributeSourceGenerator
			#pragma warning disable
			#nullable enable
			namespace {{defaultTestNamespace}};
			public partial class FirstView
			{
			    /// <summary>
			    /// Attached BindableProperty for the Text property.
			    /// </summary>
			    public static readonly global::Microsoft.Maui.Controls.BindableProperty FirstTextProperty = global::Microsoft.Maui.Controls.BindableProperty.CreateAttached("FirstText", typeof(string), typeof({{defaultTestNamespace}}.FirstView), null, Microsoft.Maui.Controls.BindingMode.OneWay, null, null, null, null, null);
			    /// <summary>
			    /// Gets FirstText for the <paramref =  " bindable " /> child element.
			    /// </summary>
			    public static string GetFirstText(global::Microsoft.Maui.Controls.BindableObject bindable) => (string)bindable.GetValue(FirstTextProperty);
			    /// <summary>
			    /// Sets FirstText for the <paramref =  " bindable " /> child element.
			    /// </summary>
			    public static void SetFirstText(global::Microsoft.Maui.Controls.BindableObject bindable, string value) => bindable.SetValue(FirstTextProperty, value);
			}
			""";

		const string expectedSecondGenerated =
			/* language=C#-test */
			//lang=csharp
			$$"""
			// <auto-generated>			
			// See: CommunityToolkit.Maui.SourceGenerators.Internal.AttachedBindablePropertyAttributeSourceGenerator
			#pragma warning disable
			#nullable enable
			namespace {{defaultTestNamespace}};
			public partial class SecondView
			{
			    /// <summary>
			    /// Attached BindableProperty for the Text property.
			    /// </summary>
			    public static readonly global::Microsoft.Maui.Controls.BindableProperty SecondTextProperty = global::Microsoft.Maui.Controls.BindableProperty.CreateAttached("SecondText", typeof(string), typeof({{defaultTestNamespace}}.SecondView), null, Microsoft.Maui.Controls.BindingMode.OneWay, null, null, null, null, null);
			    /// <summary>
			    /// Gets SecondText for the <paramref =  " bindable " /> child element.
			    /// </summary>
			    public static string GetSecondText(global::Microsoft.Maui.Controls.BindableObject bindable) => (string)bindable.GetValue(SecondTextProperty);
			    /// <summary>
			    /// Sets SecondText for the <paramref =  " bindable " /> child element.
			    /// </summary>
			    public static void SetSecondText(global::Microsoft.Maui.Controls.BindableObject bindable, string value) => bindable.SetValue(SecondTextProperty, value);
			}
			""";


		await VerifySourceGeneratorAsync(source, expectedAttribute, ("FirstView.g.cs", expectedFirstGenerated), ("SecondView.g.cs", expectedSecondGenerated));
	}
}