using Xunit;

namespace CommunityToolkit.Maui.SourceGenerators.Internal.UnitTests.AttachedBindablePropertyAttributeSourceGeneratorTests;

public class AttachedBindablePropertyAttributeSourceGenerator_ClassAttribute_EdgeCaseTests : BaseBindablePropertyAttributeSourceGeneratorTest
{
	[Fact]
	public async Task GenerateAttachedBindableProperty_LowercasePropertyName_ThrowsNotSupportedException()
	{
		const string source =
			/* language=C#-test */
			//lang=csharp
			$$"""
            using CommunityToolkit.Maui;
            using Microsoft.Maui.Controls;

            namespace {{defaultTestNamespace}};

            [AttachedBindableProperty<string>("text")]
            public partial class {{defaultTestClassName}} : View
            {
            }
            """;

		await Assert.ThrowsAsync<NotSupportedException>(() => VerifySourceGeneratorAsync(source, string.Empty));
	}

	[Fact]
	public async Task GenerateAttachedBindableProperty_PropertyWithReservedKeywords_GeneratesCorrectCode()
	{
		const string source =
			/* language=C#-test */
			//lang=csharp
			$$"""
            using CommunityToolkit.Maui;
            using Microsoft.Maui.Controls;

            namespace {{defaultTestNamespace}};

            [AttachedBindableProperty<string>("Class")]
            [AttachedBindableProperty<string>("Namespace")]
            public partial class {{defaultTestClassName}} : View
            {
            }
            """;

		const string expectedGenerated =
			/* language=C#-test */
			//lang=csharp
			$$"""
            // <auto-generated>
            // See: CommunityToolkit.Maui.SourceGenerators.Internal.AttachedBindablePropertyAttributeSourceGenerator
            #pragma warning disable
            #nullable enable
            namespace {{defaultTestNamespace}};
            public partial class {{defaultTestClassName}}
            {
                /// <summary>
                /// Attached BindableProperty for the Class property.
                /// </summary>
                public static readonly global::Microsoft.Maui.Controls.BindableProperty ClassProperty = global::Microsoft.Maui.Controls.BindableProperty.CreateAttached("Class", typeof(string), typeof({{defaultTestNamespace}}.{{defaultTestClassName}}), null, Microsoft.Maui.Controls.BindingMode.OneWay, null, null, null, null, null);
                /// <summary>
                /// Attached BindableProperty for the Namespace property.
                /// </summary>
                public static readonly global::Microsoft.Maui.Controls.BindableProperty NamespaceProperty = global::Microsoft.Maui.Controls.BindableProperty.CreateAttached("Namespace", typeof(string), typeof({{defaultTestNamespace}}.{{defaultTestClassName}}), null, Microsoft.Maui.Controls.BindingMode.OneWay, null, null, null, null, null);
                /// <summary>
                /// Gets Class for the <paramref = "bindable"/> child element.
                /// </summary>
                public static string GetClass(BindableObject bindable) => (string)bindable.GetValue(ClassProperty);
                /// <summary>
                /// Gets Namespace for the <paramref = "bindable"/> child element.
                /// </summary>
                public static string GetNamespace(BindableObject bindable) => (string)bindable.GetValue(NamespaceProperty);
                /// <summary>
                /// Sets Class for the <paramref = "bindable"/> child element.
                /// </summary>
                public static void SetClass(BindableObject bindable, string value) => bindable.SetValue(ClassProperty, value);
                /// <summary>
                /// Sets Namespace for the <paramref = "bindable"/> child element.
                /// </summary>
                public static void SetNamespace(BindableObject bindable, string value) => bindable.SetValue(NamespaceProperty, value);
            }
            """;

		await VerifySourceGeneratorAsync(source, expectedGenerated);
	}

	[Fact]
	public async Task GenerateAttachedBindableProperty_PropertyIsByteEnum_GeneratesCorrectCode()
	{
		const string source =
			/* language=C#-test */
			//lang=csharp
			$$"""
            using CommunityToolkit.Maui;
            using Microsoft.Maui.Controls;

            namespace {{defaultTestNamespace}};

            [AttachedBindableProperty<Status>("InvoiceStatus", DefaultValue = Status.Approved)]
            public partial class {{defaultTestClassName}} : View
            {
            }
            
            public enum Status : byte
            {
                Pending = 0,
                Approved = 1,
                Rejected = 2
            }
            """;

		const string expectedGenerated =
			/* language=C#-test */
			//lang=csharp
			$$"""
            // <auto-generated>
            // See: CommunityToolkit.Maui.SourceGenerators.Internal.AttachedBindablePropertyAttributeSourceGenerator
            #pragma warning disable
            #nullable enable
            namespace {{defaultTestNamespace}};
            public partial class {{defaultTestClassName}}
            {
                /// <summary>
                /// Attached BindableProperty for the InvoiceStatus property.
                /// </summary>
                public static readonly global::Microsoft.Maui.Controls.BindableProperty InvoiceStatusProperty = global::Microsoft.Maui.Controls.BindableProperty.CreateAttached("InvoiceStatus", typeof({{defaultTestNamespace}}.Status), typeof({{defaultTestNamespace}}.{{defaultTestClassName}}), ({{defaultTestNamespace}}.Status){{defaultTestNamespace}}.Status.Approved, Microsoft.Maui.Controls.BindingMode.OneWay, null, null, null, null, null);
                /// <summary>
                /// Gets InvoiceStatus for the <paramref = "bindable"/> child element.
                /// </summary>
                public static string GetInvoiceStatus(BindableObject bindable) => (string)bindable.GetValue(InvoiceStatus);
                /// <summary>
                /// Sets InvoiceStatus for the <paramref = "bindable"/> child element.
                /// </summary>
                public static void SetInvoiceStatus(BindableObject bindable, {{defaultTestNamespace}}.Status value) => bindable.SetValue(InvoiceStatus, value);
            }
            """;

		await VerifySourceGeneratorAsync(source, expectedGenerated);
	}

	[Fact]
	public async Task GenerateAttachedBindableProperty_PropertyIsLongEnum_GeneratesCorrectCode()
	{
		const string source =
			/* language=C#-test */
			//lang=csharp
			$$"""
            using CommunityToolkit.Maui;
            using Microsoft.Maui.Controls;

            namespace {{defaultTestNamespace}};

            [AttachedBindableProperty<Status>("InvoiceStatus", DefaultValue = Status.Rejected)]
            public partial class {{defaultTestClassName}} : View
            {
            }
            
            public enum Status : long
            {
                Pending = 0,
                Approved = 1,
                Rejected = long.MaxValue
            }
            """;

		const string expectedGenerated =
			/* language=C#-test */
			//lang=csharp
			$$"""
            // <auto-generated>
            // See: CommunityToolkit.Maui.SourceGenerators.Internal.AttachedBindablePropertyAttributeSourceGenerator
            #pragma warning disable
            #nullable enable
            namespace {{defaultTestNamespace}};
            public partial class {{defaultTestClassName}}
            {
                /// <summary>
                /// Attached BindableProperty for the Status property.
                /// </summary>
                public static readonly global::Microsoft.Maui.Controls.BindableProperty InvoiceStatusProperty = global::Microsoft.Maui.Controls.BindableProperty.CreateAttached("InvoiceStatus", typeof({{defaultTestNamespace}}.Status), typeof({{defaultTestNamespace}}.{{defaultTestClassName}}), ({{defaultTestNamespace}}.Status){{defaultTestNamespace}}.Status.Rejected, Microsoft.Maui.Controls.BindingMode.OneWay, null, null, null, null, null);
                /// <summary>
                /// Gets InvoiceStatus for the <paramref = "bindable"/> child element.
                /// </summary>
                public static string GetInvoiceStatus(BindableObject bindable) => (string)bindable.GetValue(InvoiceStatusProperty);
                /// <summary>
                /// Sets InvoiceStatus for the <paramref = "bindable"/> child element.
                /// </summary>
                public static void SetInvoiceStatus(BindableObject bindable, {{defaultTestNamespace}}.Status value) => bindable.SetValue(InvoiceStatusProperty, value);
            }
            """;

		await VerifySourceGeneratorAsync(source, expectedGenerated);
	}

	[Fact]
	public async Task GenerateAttachedBindableProperty_NullableValueTypes_GeneratesCorrectCode()
	{
		const string source =
			/* language=C#-test */
			//lang=csharp
			$$"""			
            using System;
            using CommunityToolkit.Maui;
            using Microsoft.Maui.Controls;

            namespace {{defaultTestNamespace}};

            [AttachedBindableProperty<int?>("NullableInt")]
            [AttachedBindableProperty<DateTime?>("NullableDateTime")]
            [AttachedBindableProperty<bool?>("NullableBool")]
            public partial class {{defaultTestClassName}} : View
            {
            }
            """;

		const string expectedGenerated =
			/* language=C#-test */
			//lang=csharp
			$$"""
            // <auto-generated>
            // See: CommunityToolkit.Maui.SourceGenerators.Internal.AttachedBindablePropertyAttributeSourceGenerator
            #pragma warning disable
            #nullable enable
            namespace {{defaultTestNamespace}};
            public partial class {{defaultTestClassName}}
            {
                /// <summary>
                /// Attached BindableProperty for the NullableInt property.
                /// </summary>
                public static readonly global::Microsoft.Maui.Controls.BindableProperty NullableIntProperty = global::Microsoft.Maui.Controls.BindableProperty.CreateAttached("NullableInt", typeof(int), typeof({{defaultTestNamespace}}.{{defaultTestClassName}}), null, Microsoft.Maui.Controls.BindingMode.OneWay, null, null, null, null, null);
                /// <summary>
                /// Attached BindableProperty for the NullableDateTime property.
                /// </summary>
                public static readonly global::Microsoft.Maui.Controls.BindableProperty NullableDateTimeProperty = global::Microsoft.Maui.Controls.BindableProperty.CreateAttached("NullableDateTime", typeof(DateTime), typeof({{defaultTestNamespace}}.{{defaultTestClassName}}), null, Microsoft.Maui.Controls.BindingMode.OneWay, null, null, null, null, null);
                /// <summary>
                /// Attached BindableProperty for the NullableBool property.
                /// </summary>
                public static readonly global::Microsoft.Maui.Controls.BindableProperty NullableBoolProperty = global::Microsoft.Maui.Controls.BindableProperty.CreateAttached("NullableBool", typeof(bool), typeof({{defaultTestNamespace}}.{{defaultTestClassName}}), null, Microsoft.Maui.Controls.BindingMode.OneWay, null, null, null, null, null);
                /// <summary>
                /// Gets NullableInt for the <paramref = "bindable"/> child element.
                /// </summary>
                public static int? GetNullableInt(BindableObject bindable) => (int?)bindable.GetValue(NullableIntProperty);
                /// <summary>
                /// Gets NullableDateTime for the <paramref = "bindable"/> child element.
                /// </summary>
                public static DateTime? GetNullableDateTime(BindableObject bindable) => (DateTime?)bindable.GetValue(NullableDateTimeProperty);
                /// <summary>
                /// Gets NullableBool for the <paramref = "bindable"/> child element.
                /// </summary>
                public static bool? GetNullableBool(BindableObject bindable) => (bool?)bindable.GetValue(NullableBoolProperty);
                /// <summary>
                /// Sets NullableInt for the <paramref = "bindable"/> child element.
                /// </summary>
                public static void SetNullableInt(BindableObject bindable, int? value) => bindable.SetValue(NullableIntProperty, value);
                /// <summary>
                /// Sets NullableDateTime for the <paramref = "bindable"/> child element.
                /// </summary>
                public static void SetNullableDateTime(BindableObject bindable, DateTime? value) => bindable.SetValue(NullableDateTimeProperty, value);
                /// <summary>
                /// Sets NullableBool for the <paramref = "bindable"/> child element.
                /// </summary>
                public static void SetNullableBool(BindableObject bindable, bool? value) => bindable.SetValue(NullableBoolProperty, value);
            }
            """;

		await VerifySourceGeneratorAsync(source, expectedGenerated);
	}

	[Fact]
	public async Task GenerateAttachedBindableProperty_ArrayTypes_GeneratesCorrectCode()
	{
		const string source =
			/* language=C#-test */
			//lang=csharp
			$$"""
            using CommunityToolkit.Maui;
            using Microsoft.Maui.Controls;

            namespace {{defaultTestNamespace}};

            [AttachedBindableProperty<string[]>("StringArray")]
            [AttachedBindableProperty<int[,]>("MultiDimensionalArray")]
            [AttachedBindableProperty<byte[][]>("JaggedArray")]
            public partial class {{defaultTestClassName}} : View
            {
            }
            """;

		const string expectedGenerated =
			/* language=C#-test */
			//lang=csharp
			$$"""
            // <auto-generated>
            // See: CommunityToolkit.Maui.SourceGenerators.Internal.AttachedBindablePropertyAttributeSourceGenerator
            #pragma warning disable
            #nullable enable
            namespace {{defaultTestNamespace}};
            public partial class {{defaultTestClassName}}
            {
                /// <summary>
                /// Attached BindableProperty for the StringArray property.
                /// </summary>
                public static readonly global::Microsoft.Maui.Controls.BindableProperty StringArrayProperty = global::Microsoft.Maui.Controls.BindableProperty.CreateAttached("StringArray", typeof(string[]), typeof({{defaultTestNamespace}}.{{defaultTestClassName}}), null, Microsoft.Maui.Controls.BindingMode.OneWay, null, null, null, null, null);
                /// <summary>
                /// Attached BindableProperty for the MultiDimensionalArray property.
                /// </summary>
                public static readonly global::Microsoft.Maui.Controls.BindableProperty MultiDimensionalArrayProperty = global::Microsoft.Maui.Controls.BindableProperty.CreateAttached("MultiDimensionalArray", typeof(int[,]), typeof({{defaultTestNamespace}}.{{defaultTestClassName}}), null, Microsoft.Maui.Controls.BindingMode.OneWay, null, null, null, null, null);
                /// <summary>
                /// Attached BindableProperty for the JaggedArray property.
                /// </summary>
                public static readonly global::Microsoft.Maui.Controls.BindableProperty JaggedArrayProperty = global::Microsoft.Maui.Controls.BindableProperty.CreateAttached("JaggedArray", byte[][], typeof({{defaultTestNamespace}}.{{defaultTestClassName}}), null, Microsoft.Maui.Controls.BindingMode.OneWay, null, null, null, null, null);
                /// <summary>
                /// Gets StringArray for the <paramref = "bindable"/> child element.
                /// </summary>
                public static string[] GetStringArray(BindableObject bindable) => (string[])bindable.GetValue(StringArrayProperty);
                /// <summary>
                /// Gets MultiDimensionalArray for the <paramref = "bindable"/> child element.
                /// </summary>
                public static int[,] GetMultiDimensionalArray(BindableObject bindable) => (int[,])bindable.GetValue(MultiDimensionalArrayProperty);
                /// <summary>
                /// Gets JaggedArray for the <paramref = "bindable"/> child element.
                /// </summary>
                public static byte[][] GetJaggedArray(BindableObject bindable) => (byte[][])bindable.GetValue(JaggedArrayProperty);
                /// <summary>
                /// Sets StringArray for the <paramref = "bindable"/> child element.
                /// </summary>
                public static void SetStringArray(BindableObject bindable, string[] value) => bindable.SetValue(StringArray, value);
                /// <summary>
                /// Sets MultiDimensionalArray for the <paramref = "bindable"/> child element.
                /// </summary>
                public static void SetMultiDimensionalArray(BindableObject bindable, int[,] value) => bindable.SetValue(MultiDimensionalArrayProperty, value);
                /// <summary>
                /// Sets JaggedArray for the <paramref = "bindable"/> child element.
                /// </summary>
                public static void SetJaggedArray(BindableObject bindable, byte[][] value) => bindable.SetValue(JaggedArrayProperty, value);
            }
            """;

		await VerifySourceGeneratorAsync(source, expectedGenerated);
	}

	[Fact]
	public async Task GenerateAttachedBindableProperty_LongNamespaces_GeneratesCorrectCode()
	{
		const string source =
			/* language=C#-test */
			//lang=csharp
			$$"""
            using CommunityToolkit.Maui;
            using Microsoft.Maui.Controls;

            namespace Very.Long.Namespace.With.Many.Segments.TestNamespace;

            [AttachedBindableProperty<string>("Text")]
            public partial class {{defaultTestClassName}} : View
            {
            }
            """;

		const string expectedGenerated =
			/* language=C#-test */
			//lang=csharp
			$$"""
			// <auto-generated>
			// See: CommunityToolkit.Maui.SourceGenerators.Internal.AttachedBindablePropertyAttributeSourceGenerator
			#pragma warning disable
			#nullable enable
			namespace Very.Long.Namespace.With.Many.Segments.TestNamespace;
			public partial class {{defaultTestClassName}}
			{
			    /// <summary>
			    /// Attached BindableProperty for the Text property.
			    /// </summary>
			    public static readonly global::Microsoft.Maui.Controls.BindableProperty TextProperty = global::Microsoft.Maui.Controls.BindableProperty.CreateAttached("Text", typeof(string), typeof(Very.Long.Namespace.With.Many.Segments.TestNamespace.{{defaultTestClassName}}), null, Microsoft.Maui.Controls.BindingMode.OneWay, null, null, null, null, null);
			    /// <summary>
			    /// Gets Text for the <paramref = "bindable"/> child element.
			    /// </summary>
			    public static string GetText(BindableObject bindable) => (string)bindable.GetValue(TextProperty);
			    /// <summary>
			    /// Sets Text for the <paramref = "bindable"/> child element.
			    /// </summary>
			    public static void SetText(BindableObject bindable, string value) => bindable.SetValue(TextProperty, value);
			}
			""";

		await VerifySourceGeneratorAsync(source, expectedGenerated);
	}

	[Fact]
	public async Task GenerateAttachedBindableProperty_GlobalNamespace_GeneratesCorrectCode()
	{
		const string source =
			/* language=C#-test */
			//lang=csharp
			$$"""
            using CommunityToolkit.Maui;
            using Microsoft.Maui.Controls;

            [AttachedBindableProperty<string>("Text")]
            public partial class {{defaultTestClassName}} : View
            {
            }
            """;

		const string expectedGenerated =
			/* language=C#-test */
			//lang=csharp
			$$"""
			// <auto-generated>
			// See: CommunityToolkit.Maui.SourceGenerators.Internal.AttachedBindablePropertyAttributeSourceGenerator
			#pragma warning disable
			#nullable enable
			public partial class {{defaultTestClassName}}
			{
			    /// <summary>
			    /// Attached BindableProperty for the Text property.
			    /// </summary>
			    public static readonly global::Microsoft.Maui.Controls.BindableProperty TextProperty = global::Microsoft.Maui.Controls.BindableProperty.CreateAttached("Text", typeof(string), typeof({{defaultTestClassName}}), null, Microsoft.Maui.Controls.BindingMode.OneWay, null, null, null, null, null);
			    /// <summary>
			    /// Gets Text for the <paramref = "bindable"/> child element.
			    /// </summary>
			    public static string GetText(BindableObject bindable) => (string)bindable.GetValue(TextProperty);
			    /// <summary>
			    /// Sets Text for the <paramref = "bindable"/> child element.
			    /// </summary>
			    public static void SetText(BindableObject bindable, string value) => bindable.SetValue(TextProperty, value);
			}
			""";

		await VerifySourceGeneratorAsync(source, expectedGenerated);
	}

	[Fact]
	public async Task GenerateAttachedBindableProperty_SpecialCharactersInPropertyName_GeneratesCorrectCode()
	{
		const string source =
			/* language=C#-test */
			//lang=csharp
			$$"""
            using CommunityToolkit.Maui;
            using Microsoft.Maui.Controls;

            namespace {{defaultTestNamespace}};

            [AttachedBindableProperty<string>("Property_With_Underscores")]
            [AttachedBindableProperty<string>("Property123WithNumbers")]
            public partial class {{defaultTestClassName}} : View
            {
            }
            """;

		const string expectedGenerated =
			/* language=C#-test */
			//lang=csharp
			$$"""
			// <auto-generated>
			// See: CommunityToolkit.Maui.SourceGenerators.Internal.AttachedBindablePropertyAttributeSourceGenerator
			#pragma warning disable
			#nullable enable
			public partial class {{defaultTestClassName}}
			{
			    /// <summary>
			    /// Attached BindableProperty for the Property_With_Underscores property.
			    /// </summary>
			    public static readonly global::Microsoft.Maui.Controls.BindableProperty Property_With_UnderscoresProperty = global::Microsoft.Maui.Controls.BindableProperty.CreateAttached("Property_With_Underscores", typeof(string), typeof({{defaultTestClassName}}), null, Microsoft.Maui.Controls.BindingMode.OneWay, null, null, null, null, null);
			    /// <summary>
			    /// Attached BindableProperty for the Property123WithNumbers property.
			    /// </summary>
			    public static readonly global::Microsoft.Maui.Controls.BindableProperty Property123WithNumbersProperty = global::Microsoft.Maui.Controls.BindableProperty.CreateAttached("Property123WithNumbers", typeof(string), typeof({{defaultTestClassName}}), null, Microsoft.Maui.Controls.BindingMode.OneWay, null, null, null, null, null);
			    /// <summary>
			    /// Gets Property_With_Underscores for the <paramref = "bindable"/> child element.
			    /// </summary>
			    public static string GetProperty_With_Underscores(BindableObject bindable) => (string)bindable.GetValue(Property_With_UnderscoresProperty);
			    /// <summary>
			    /// Gets Property123WithNumbers for the <paramref = "bindable"/> child element.
			    /// </summary>
			    public static string GetProperty123WithNumbers(BindableObject bindable) => (string)bindable.GetValue(Property123WithNumbersProperty);
			    /// <summary>
			    /// Sets Property_With_Underscores for the <paramref = "bindable"/> child element.
			    /// </summary>
			    public static void SetProperty_With_Underscores(BindableObject bindable, string value) => bindable.SetValue(Property_With_UnderscoresProperty, value);
			    /// <summary>
			    /// Sets Property123WithNumbers for the <paramref = "bindable"/> child element.
			    /// </summary>
			    public static void SetProperty123WithNumbers(BindableObject bindable, string value) => bindable.SetValue(Property123WithNumbersProperty, value);
			}
			""";

		await VerifySourceGeneratorAsync(source, expectedGenerated);
	}

	[Fact]
	public async Task GenerateAttachedBindableProperty_WithComplexDefaultValues_GeneratesCorrectCode()
	{
		const string source =
			/* language=C#-test */
			//lang=csharp
			$$"""
            using CommunityToolkit.Maui;
            using Microsoft.Maui.Controls;
            using System;

            namespace {{defaultTestNamespace}};

            [AttachedBindableProperty<bool>("IsEnabled", DefaultValue = true)]
            [AttachedBindableProperty<double>("Pi", DefaultValue = 3.14)]
            [AttachedBindableProperty<char>("Letter", DefaultValue = 'A')]
            [AttachedBindableProperty<TimeSpan>("TimeSpent", DefaultValue = System.TimeSpan.Zero)]
            [AttachedBindableProperty<double>("DoubleEpsilon", DefaultValue = double.Epsilon)]
            [AttachedBindableProperty<float>("SingleEpsilon", DefaultValue = float.Epsilon)]
            [AttachedBindableProperty<DateTimeOffset>("CurrentTime", DefaultValue = DateTimeOffset.UtcNow)]
            public partial class {{defaultTestClassName}} : View
            {
            }
            """;

		const string expectedGenerated =
			/* language=C#-test */
			//lang=csharp
			$$"""
            // <auto-generated>
            // See: CommunityToolkit.Maui.SourceGenerators.Internal.AttachedBindablePropertyAttributeSourceGenerator
            #pragma warning disable
            #nullable enable
            namespace {{defaultTestNamespace}};
            public partial class {{defaultTestClassName}}
            {
                /// <summary>
                /// Attached BindableProperty for the IsEnabled property.
                /// </summary>
                public static readonly global::Microsoft.Maui.Controls.BindableProperty IsEnabledProperty = global::Microsoft.Maui.Controls.BindableProperty.CreateAttached("IsEnabled", typeof(bool), typeof({{defaultTestClassName}}), (bool)true, Microsoft.Maui.Controls.BindingMode.OneWay, null, null, null, null, null);
                /// <summary>
                /// Attached BindableProperty for the Pi property.
                /// </summary>
                public static readonly global::Microsoft.Maui.Controls.BindableProperty PiProperty = global::Microsoft.Maui.Controls.BindableProperty.CreateAttached("Pi", typeof(double), typeof({{defaultTestClassName}}), (double)double.Pi, Microsoft.Maui.Controls.BindingMode.OneWay, null, null, null, null, null);
                /// <summary>
                /// Attached BindableProperty for the Letter property.
                /// </summary>
                public static readonly global::Microsoft.Maui.Controls.BindableProperty LetterProperty = global::Microsoft.Maui.Controls.BindableProperty.CreateAttached("Letter", typeof(char), typeof({{defaultTestClassName}}), (char)'A', Microsoft.Maui.Controls.BindingMode.OneWay, null, null, null, null, null);
                /// <summary>
                /// Attached BindableProperty for the TimeSpent property.
                /// </summary>
                public static readonly global::Microsoft.Maui.Controls.BindableProperty TimeSpentProperty = global::Microsoft.Maui.Controls.BindableProperty.CreateAttached("TimeSpent", typeof(TimeSpan), typeof({{defaultTestClassName}}), (global::System.TimeSpan)System.TimeSpan.Zero, Microsoft.Maui.Controls.BindingMode.OneWay, null, null, null, null, null);
                /// <summary>
                /// Attached BindableProperty for the DoubleEpsilon property.
                /// </summary>
                public static readonly global::Microsoft.Maui.Controls.BindableProperty DoubleEpsilonProperty = global::Microsoft.Maui.Controls.BindableProperty.CreateAttached("DoubleEpsilon", typeof(double), typeof({{defaultTestClassName}}), (double)double.Epsilon, Microsoft.Maui.Controls.BindingMode.OneWay, null, null, null, null, null);
                /// <summary>
                /// Attached BindableProperty for the SingleEpsilon property.
                /// </summary>
                public static readonly global::Microsoft.Maui.Controls.BindableProperty SingleEpsilonProperty = global::Microsoft.Maui.Controls.BindableProperty.CreateAttached("SingleEpsilon", typeof(float), typeof({{defaultTestClassName}}), (float)float.Epsilon, Microsoft.Maui.Controls.BindingMode.OneWay, null, null, null, null, null);
                /// <summary>
                /// Attached BindableProperty for the CurrentTime property.
                /// </summary>
                public static readonly global::Microsoft.Maui.Controls.BindableProperty CurrentTimeProperty = global::Microsoft.Maui.Controls.BindableProperty.CreateAttached("CurrentTime", typeof(global::System.DateTime), typeof({{defaultTestClassName}}), (global::System.DateTime)DateTimeOffset.UtcNow, Microsoft.Maui.Controls.BindingMode.OneWay, null, null, null, null, null);
                /// <summary>
                /// Gets IsEnabled for the <paramref = "bindable"/> child element.
                /// </summary>
                public static bool GetIsEnabled(BindableObject bindable) => (bool)bindable.GetValue(IsEnabledProperty);
                /// <summary>
                /// Gets Pi for the <paramref = "bindable"/> child element.
                /// </summary>
                public static double GetPi(BindableObject bindable) => (double)bindable.GetValue(PiProperty);
                /// <summary>
                /// Gets Letter for the <paramref = "bindable"/> child element.
                /// </summary>
                public static char GetLetter(BindableObject bindable) => (char)bindable.GetValue(TextProperty);
                /// <summary>
                /// Gets TimeSpent for the <paramref = "bindable"/> child element.
                /// </summary>
                public static global::System.TimeSpan GetTimeSpent(BindableObject bindable) => (global::System.TimeSpan)bindable.GetValue(TimeSpentProperty);
                /// <summary>
                /// Gets DoubleEpsilon for the <paramref = "bindable"/> child element.
                /// </summary>
                public static double GetDoubleEpsilon(BindableObject bindable) => (double)bindable.GetValue(DoubleEpsilonProperty);
                /// <summary>
                /// Gets SingleEpsilon for the <paramref = "bindable"/> child element.
                /// </summary>
                public static double GetSingleEpsilon(BindableObject bindable) => (float)bindable.GetValue(SingleEpsilonProperty);
                /// <summary>
                /// Gets CurrentTime for the <paramref = "bindable"/> child element.
                /// </summary>
                public static global::System.DateTime GetCurrentTime(BindableObject bindable) => (global::System.DateTime)bindable.GetValue(CurrentTimeProperty);
                /// <summary>
                /// Sets IsEnabled for the <paramref = "bindable"/> child element.
                /// </summary>
                public static void SetIsEnabled(BindableObject bindable, ool value) => bindable.SetValue(IsEnabledProperty, value);
                /// <summary>
                /// Sets Pi for the <paramref = "bindable"/> child element.
                /// </summary>
                public static void SetPi(BindableObject bindable, double value) => bindable.SetValue(PiProperty, value);
                /// <summary>
                /// Sets Letter for the <paramref = "bindable"/> child element.
                /// </summary>
                public static void SetLetter(BindableObject bindable, char value) => bindable.SetValue(LetterProperty, value);
                /// <summary>
                /// Sets TimeSpent for the <paramref = "bindable"/> child element.
                /// </summary>
                public static void SetTimeSpent(BindableObject bindable, global::System.TimeSpan value) => bindable.SetValue(TimeSpentProperty, value);
                /// <summary>
                /// Sets DoubleEpsilon for the <paramref = "bindable"/> child element.
                /// </summary>
                public static void SetDoubleEpsilon(BindableObject bindable, double value) => bindable.SetValue(DoubleEpsilonProperty, value);
                /// <summary>
                /// Sets SingleEpsilon for the <paramref = "bindable"/> child element.
                /// </summary>
                public static void SetSingleEpsilon(BindableObject bindable, float value) => bindable.SetValue(SingleEpsilonProperty, value);
                /// <summary>
                /// Sets CurrentTime for the <paramref = "bindable"/> child element.
                /// </summary>
                public static void SetCurrentTime(BindableObject bindable) => bindable.SetValue(CurrentTimeProperty, value);
            }
            """;

		await VerifySourceGeneratorAsync(source, expectedGenerated);
	}

	[Fact]
	public async Task GenerateAttachedBindableProperty_WithBothInitializerAndDefault_GeneratedCodeSetsBothValues()
	{
		const string source =
			/* language=C#-test */
			//lang=csharp
			$$"""
			using CommunityToolkit.Maui;
			using Microsoft.Maui.Controls;
			using System;

			namespace {{defaultTestNamespace}};

			[AttachedBindablePropertyAttribute<string>("Text", DefaultValue = "Initial Value", DefaultValueCreatorMethodName = nameof(CreateDefaultText))]
			public partial class {{defaultTestClassName}} : View
			{
				static string CreateDefaultText(BindableObject bindable)
				{
					return "Initial Value";
				}
			}
			""";

		const string expectedGenerated =
			/* language=C#-test */
			//lang=csharp
			$$"""
			// <auto-generated>
			// See: CommunityToolkit.Maui.SourceGenerators.Internal.AttachedBindablePropertyAttributeSourceGenerator
			#pragma warning disable
			#nullable enable
			namespace {{defaultTestNamespace}};
			public partial class {{defaultTestClassName}}
			{
			    /// <summary>
			    /// Attached BindableProperty for the Text property.
			    /// </summary>
			    public static readonly global::Microsoft.Maui.Controls.BindableProperty TextProperty = global::Microsoft.Maui.Controls.BindableProperty.CreateAttached("Text", typeof(string), typeof({{defaultTestNamespace}}.{{defaultTestClassName}}), (string)"Initial Value", Microsoft.Maui.Controls.BindingMode.OneWay, null, null, null, null, CreateDefaultText);
			    /// <summary>
			    /// Gets Text for the <paramref = "bindable"/> child element.
			    /// </summary>
			    public static string GetText(BindableObject bindable) => (string)bindable.GetValue(TextProperty);
			    /// <summary>
			    /// Sets Text for the <paramref = "bindable"/> child element.
			    /// </summary>
			    public static void SetText(BindableObject bindable, string value) => bindable.SetValue(TextProperty, value);
			}
			""";

		await VerifySourceGeneratorAsync(source, expectedGenerated);
	}
}