using Xunit;

namespace CommunityToolkit.Maui.SourceGenerators.Internal.UnitTests.AttachedBindablePropertyAttributeSourceGeneratorTests;

public class AttachedBindablePropertyAttributeSourceGenerator_ClassAttribute_IntegrationTests : BaseAttachedBindablePropertyAttributeSourceGeneratorTest
{
	[Fact]
	public async Task GenerateAttachedBindableProperty_ComplexInheritanceScenario_GeneratesCorrectCode()
	{
		const string source =
			/* language=C#-test */
			//lang=csharp
			$$"""
			using CommunityToolkit.Maui;
			using Microsoft.Maui.Controls;

			namespace {{defaultTestNamespace}};

			[AttachedBindablePropertyAttribute<string>("Text")]
			public abstract partial class BaseView : View
			{
			}

			[AttachedBindablePropertyAttribute<string>("DerivedText")]
			public partial class DerivedView : BaseView
			{
			}
			""";

		const string expectedBaseGenerated =
			/* language=C#-test */
			//lang=csharp
			$$"""
			// <auto-generated>
			// See: CommunityToolkit.Maui.SourceGenerators.Internal.AttachedBindablePropertyAttributeSourceGenerator
			#pragma warning disable
			#nullable enable
			namespace {{defaultTestNamespace}};
			public partial class BaseView
			{
			    /// <summary>
			    /// Attached BindableProperty for the Text property.
			    /// </summary>
			    public static readonly global::Microsoft.Maui.Controls.BindableProperty TextProperty = global::Microsoft.Maui.Controls.BindableProperty.CreateAttached("Text", typeof(string), typeof({{defaultTestNamespace}}.BaseView), null, (Microsoft.Maui.Controls.BindingMode)0, null, null, null, null, null);
			    /// <summary>
			    /// Gets Text for the <paramref name = "bindable"/> child element.
			    /// </summary>
			    public static string GetText(global::Microsoft.Maui.Controls.BindableObject bindable) => (string)bindable.GetValue(TextProperty);
			    /// <summary>
			    /// Sets Text for the <paramref name = "bindable"/> child element.
			    /// </summary>
			    public static void SetText(global::Microsoft.Maui.Controls.BindableObject bindable, string value) => bindable.SetValue(TextProperty, value);
			}
			""";

		const string expectedDerivedGenerated =
			/* language=C#-test */
			//lang=csharp
			$$"""
			// <auto-generated>
			// See: CommunityToolkit.Maui.SourceGenerators.Internal.AttachedBindablePropertyAttributeSourceGenerator
			#pragma warning disable
			#nullable enable
			namespace {{defaultTestNamespace}};
			public partial class DerivedView
			{
			    /// <summary>
			    /// Attached BindableProperty for the DerivedText property.
			    /// </summary>
			    public static readonly global::Microsoft.Maui.Controls.BindableProperty DerivedTextProperty = global::Microsoft.Maui.Controls.BindableProperty.CreateAttached("DerivedText", typeof(string), typeof({{defaultTestNamespace}}.DerivedView), null, (Microsoft.Maui.Controls.BindingMode)0, null, null, null, null, null);
			    /// <summary>
			    /// Gets DerivedText for the <paramref name = "bindable"/> child element.
			    /// </summary>
			    public static string GetDerivedText(global::Microsoft.Maui.Controls.BindableObject bindable) => (string)bindable.GetValue(DerivedTextProperty);
			    /// <summary>
			    /// Sets DerivedText for the <paramref name = "bindable"/> child element.
			    /// </summary>
			    public static void SetDerivedText(global::Microsoft.Maui.Controls.BindableObject bindable, string value) => bindable.SetValue(DerivedTextProperty, value);
			}
			""";

		await VerifySourceGeneratorAsync(source, ("BaseView.g.cs", expectedBaseGenerated), ("DerivedView.g.cs", expectedDerivedGenerated));
	}

	[Fact]
	public async Task GenerateAttachedBindableProperty_GenericClass_GeneratesCorrectCode()
	{
		const string source =
			/* language=C#-test */
			//lang=csharp
			$$"""
		    using CommunityToolkit.Maui;
		    using Microsoft.Maui.Controls;

		    namespace {{defaultTestNamespace}};

		    [AttachedBindablePropertyAttribute<string>("Text")]
		    public partial class {{defaultTestClassName}}<T,U> : View where T : class
		    {
		    }
		    """;

		const string expectedGenerated =
			/* language=C#-test */
			//lang=csharp
			$$"""
			// <auto-generated>
			// See: CommunityToolkit.Maui.SourceGenerators.Internal.AttachedBindablePropertyAttributeSourceGenerator
			#pragma warning disable
			#nullable enable
			namespace {{defaultTestNamespace}};
			public partial class {{defaultTestClassName}}<T, U>
			{
			    /// <summary>
			    /// Attached BindableProperty for the Text property.
			    /// </summary>
			    public static readonly global::Microsoft.Maui.Controls.BindableProperty TextProperty = global::Microsoft.Maui.Controls.BindableProperty.CreateAttached("Text", typeof(string), typeof({{defaultTestNamespace}}.{{defaultTestClassName}}<T, U>), null, (Microsoft.Maui.Controls.BindingMode)0, null, null, null, null, null);
			    /// <summary>
			    /// Gets Text for the <paramref name = "bindable"/> child element.
			    /// </summary>
			    public static string GetText(global::Microsoft.Maui.Controls.BindableObject bindable) => (string)bindable.GetValue(TextProperty);
			    /// <summary>
			    /// Sets Text for the <paramref name = "bindable"/> child element.
			    /// </summary>
			    public static void SetText(global::Microsoft.Maui.Controls.BindableObject bindable, string value) => bindable.SetValue(TextProperty, value);
			}
			""";

		await VerifySourceGeneratorAsync(source, expectedGenerated);
	}

	[Fact]
	public async Task GenerateAttachedBindableProperty_AttributeOnNestedInnerClass_GeneratesCorrectCode()
	{
		const string outerClassName = "Outerclass";

		const string source =
			/* language=C#-test */
			//lang=csharp
			$$"""
		    using CommunityToolkit.Maui;
		    using Microsoft.Maui.Controls;

		    namespace {{defaultTestNamespace}};

		    public partial class {{outerClassName}}
		    {
		        [AttachedBindablePropertyAttribute<string>("Text")]
		        public partial class {{defaultTestClassName}} : View
		        {
		        }
		    }
		    """;

		const string expectedGenerated =
			/* language=C#-test */
			//lang=csharp
			$$$""""
			// <auto-generated>
			// See: CommunityToolkit.Maui.SourceGenerators.Internal.AttachedBindablePropertyAttributeSourceGenerator
			#pragma warning disable
			#nullable enable
			namespace {{{defaultTestNamespace}}};
			public partial class {{{outerClassName}}}
			{
			    public partial class {{{defaultTestClassName}}}
			    {
			        /// <summary>
			        /// Attached BindableProperty for the Text property.
			        /// </summary>
			        public static readonly global::Microsoft.Maui.Controls.BindableProperty TextProperty = global::Microsoft.Maui.Controls.BindableProperty.CreateAttached("Text", typeof(string), typeof({{{defaultTestNamespace}}}.{{{outerClassName}}}.{{{defaultTestClassName}}}), null, (Microsoft.Maui.Controls.BindingMode)0, null, null, null, null, null);
			        /// <summary>
			        /// Gets Text for the <paramref name = "bindable"/> child element.
			        /// </summary>
			        public static string GetText(global::Microsoft.Maui.Controls.BindableObject bindable) => (string)bindable.GetValue(TextProperty);
			        /// <summary>
			        /// Sets Text for the <paramref name = "bindable"/> child element.
			        /// </summary>
			        public static void SetText(global::Microsoft.Maui.Controls.BindableObject bindable, string value) => bindable.SetValue(TextProperty, value);
			    }
			}
			"""";

		await VerifySourceGeneratorAsync(source, ($"{outerClassName}.{defaultTestClassName}.g.cs", expectedGenerated));
	}

	[Fact]
	public async Task GenerateAttachedBindableProperty_NestedInnerClassWithAttributeOnOutterClass_GeneratesCorrectCode()
	{
		const string outerClassName = "Outerclass";

		const string source =
			/* language=C#-test */
			//lang=csharp
			$$"""
		    using CommunityToolkit.Maui;
		    using Microsoft.Maui.Controls;

		    namespace {{defaultTestNamespace}};

		    [AttachedBindablePropertyAttribute<string>("Text")]
		    public partial class {{outerClassName}} : View
		    {
		        public partial class {{defaultTestClassName}} : View
		        {
		        }
		    }
		    """;

		const string expectedGenerated =
			/* language=C#-test */
			//lang=csharp
			$$$""""
			// <auto-generated>
			// See: CommunityToolkit.Maui.SourceGenerators.Internal.AttachedBindablePropertyAttributeSourceGenerator
			#pragma warning disable
			#nullable enable
			namespace {{{defaultTestNamespace}}};
			public partial class {{{outerClassName}}}
			{
			    /// <summary>
			    /// Attached BindableProperty for the Text property.
			    /// </summary>
			    public static readonly global::Microsoft.Maui.Controls.BindableProperty TextProperty = global::Microsoft.Maui.Controls.BindableProperty.CreateAttached("Text", typeof(string), typeof({{{defaultTestNamespace}}}.{{{outerClassName}}}), null, (Microsoft.Maui.Controls.BindingMode)0, null, null, null, null, null);
			    /// <summary>
			    /// Gets Text for the <paramref name = "bindable"/> child element.
			    /// </summary>
			    public static string GetText(global::Microsoft.Maui.Controls.BindableObject bindable) => (string)bindable.GetValue(TextProperty);
			    /// <summary>
			    /// Sets Text for the <paramref name = "bindable"/> child element.
			    /// </summary>
			    public static void SetText(global::Microsoft.Maui.Controls.BindableObject bindable, string value) => bindable.SetValue(TextProperty, value);
			}
			"""";

		await VerifySourceGeneratorAsync(source, ($"{outerClassName}.g.cs", expectedGenerated));
	}

	[Fact]
	public async Task GenerateAttachedBindableProperty_WithCustomTypes_GeneratesCorrectCode()
	{
		const string source =
			/* language=C#-test */
			//lang=csharp
			$$"""
		    using CommunityToolkit.Maui;
		    using Microsoft.Maui.Controls;
		    using System.Collections.Generic;

		    namespace {{defaultTestNamespace}};

		    public class CustomModel
		    {
		        public string Name { get; set; }
		    }

		    [AttachedBindablePropertyAttribute<CustomModel>("Model", true)]
		    public partial class {{defaultTestClassName}} : View
		    {
		    }
		    """;

		const string expectedGenerated =
			/* language=C#-test */
			//lang=csharp
			$$"""
			// <auto-generated>
			// See: CommunityToolkit.Maui.SourceGenerators.Internal.AttachedBindablePropertyAttributeSourceGenerator
			#pragma warning disable
			#nullable enable
			namespace {{defaultTestNamespace}};
			public partial class {{defaultTestClassName}}
			{
			    /// <summary>
			    /// Attached BindableProperty for the Model property.
			    /// </summary>
			    public static readonly global::Microsoft.Maui.Controls.BindableProperty ModelProperty = global::Microsoft.Maui.Controls.BindableProperty.CreateAttached("Model", typeof(global::{{defaultTestNamespace}}.CustomModel), typeof({{defaultTestNamespace}}.{{defaultTestClassName}}), null, (Microsoft.Maui.Controls.BindingMode)0, null, null, null, null, null);
			    /// <summary>
			    /// Gets Model for the <paramref name = "bindable"/> child element.
			    /// </summary>
			    public static global::{{defaultTestNamespace}}.CustomModel? GetModel(global::Microsoft.Maui.Controls.BindableObject bindable) => (global::{{defaultTestNamespace}}.CustomModel? )bindable.GetValue(ModelProperty);
			    /// <summary>
			    /// Sets Model for the <paramref name = "bindable"/> child element.
			    /// </summary>
			    public static void SetModel(global::Microsoft.Maui.Controls.BindableObject bindable, global::{{defaultTestNamespace}}.CustomModel? value) => bindable.SetValue(ModelProperty, value);
			}
			""";

		await VerifySourceGeneratorAsync(source, expectedGenerated);
	}

	[Fact]
	public async Task GenerateAttachedBindableProperty_MultipleClassesInSameFile_GeneratesCorrectCode()
	{
		const string source =
			/* language=C#-test */
			//lang=csharp
			$$"""
		    using CommunityToolkit.Maui;
		    using Microsoft.Maui.Controls;

		    namespace {{defaultTestNamespace}};

		    [AttachedBindablePropertyAttribute<string>("FirstText")]
		    public partial class FirstView : View
		    {
		    }

		    [AttachedBindablePropertyAttribute<string>("SecondText")]
		    public partial class SecondView : View
		    {
		    }
		    """;

		const string expectedFirstGenerated =
			/* language=C#-test */
			//lang=csharp
			$$"""
			// <auto-generated>
			// See: CommunityToolkit.Maui.SourceGenerators.Internal.AttachedBindablePropertyAttributeSourceGenerator
			#pragma warning disable
			#nullable enable
			namespace {{defaultTestNamespace}};
			public partial class FirstView
			{
			    /// <summary>
			    /// Attached BindableProperty for the FirstText property.
			    /// </summary>
			    public static readonly global::Microsoft.Maui.Controls.BindableProperty FirstTextProperty = global::Microsoft.Maui.Controls.BindableProperty.CreateAttached("FirstText", typeof(string), typeof({{defaultTestNamespace}}.FirstView), null, (Microsoft.Maui.Controls.BindingMode)0, null, null, null, null, null);
			    /// <summary>
			    /// Gets FirstText for the <paramref name = "bindable"/> child element.
			    /// </summary>
			    public static string GetFirstText(global::Microsoft.Maui.Controls.BindableObject bindable) => (string)bindable.GetValue(FirstTextProperty);
			    /// <summary>
			    /// Sets FirstText for the <paramref name = "bindable"/> child element.
			    /// </summary>
			    public static void SetFirstText(global::Microsoft.Maui.Controls.BindableObject bindable, string value) => bindable.SetValue(FirstTextProperty, value);
			}
			""";

		const string expectedSecondGenerated =
			/* language=C#-test */
			//lang=csharp
			$$"""
			// <auto-generated>
			// See: CommunityToolkit.Maui.SourceGenerators.Internal.AttachedBindablePropertyAttributeSourceGenerator
			#pragma warning disable
			#nullable enable
			namespace {{defaultTestNamespace}};
			public partial class SecondView
			{
			    /// <summary>
			    /// Attached BindableProperty for the SecondText property.
			    /// </summary>
			    public static readonly global::Microsoft.Maui.Controls.BindableProperty SecondTextProperty = global::Microsoft.Maui.Controls.BindableProperty.CreateAttached("SecondText", typeof(string), typeof({{defaultTestNamespace}}.SecondView), null, (Microsoft.Maui.Controls.BindingMode)0, null, null, null, null, null);
			    /// <summary>
			    /// Gets SecondText for the <paramref name = "bindable"/> child element.
			    /// </summary>
			    public static string GetSecondText(global::Microsoft.Maui.Controls.BindableObject bindable) => (string)bindable.GetValue(SecondTextProperty);
			    /// <summary>
			    /// Sets SecondText for the <paramref name = "bindable"/> child element.
			    /// </summary>
			    public static void SetSecondText(global::Microsoft.Maui.Controls.BindableObject bindable, string value) => bindable.SetValue(SecondTextProperty, value);
			}
			""";


		await VerifySourceGeneratorAsync(source, ("FirstView.g.cs", expectedFirstGenerated), ("SecondView.g.cs", expectedSecondGenerated));
	}
}