namespace CommunityToolkit.Maui.SourceGenerators.Internal.UnitTests.AttachedBindablePropertyAttributeSourceGeneratorTests;

public abstract class BaseAttachedBindablePropertyAttributeSourceGeneratorTest : BaseTest
{
	const string generatedBindablePropertyAttributeFileName = "AttachedBindablePropertyAttribute.g.cs";
	const string expectedAttribute =
		/* language=C#-test */
		//lang=csharp
		$$"""
		  // <auto-generated>
		  // See: CommunityToolkit.Maui.SourceGenerators.Internal.AttachedBindablePropertySourceGenerator

		  #pragma warning disable
		  #nullable enable
		  namespace CommunityToolkit.Maui;

		  [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
		  [global::System.AttributeUsage(global::System.AttributeTargets.Class | global::System.AttributeTargets.Constructor, AllowMultiple = true, Inherited = false)]
		  [global::System.Diagnostics.CodeAnalysis.Experimental("{{BindablePropertyDiagnostic.BindablePropertyAttributeExperimentalDiagnosticId}}")]
		  public sealed partial class AttachedBindablePropertyAttribute<T>(string propertyName) : global::System.Attribute where T : notnull
		  {
		  	public string PropertyName { get; } = propertyName;
		  	public bool IsNullable { get; init; }
		  	public T DefaultValue { get; init; }
		  	public global::Microsoft.Maui.Controls.BindingMode DefaultBindingMode { get; init; }
		  	public string ValidateValueMethodName { get; init; } = string.Empty;
		  	public string PropertyChangedMethodName { get; init; } = string.Empty;
		  	public string PropertyChangingMethodName { get; init; } = string.Empty;
		  	public string CoerceValueMethodName { get; init; } = string.Empty;
		  	public string DefaultValueCreatorMethodName { get; init; } = string.Empty;
		  	public string? BindablePropertyXmlDocumentation { get; init; }
		  	public string? GetterMethodXmlDocumentation { get; init; }
		  	public string? SetterMethodXmlDocumentation { get; init; }
		  	public global::CommunityToolkit.Maui.AccessModifier BindablePropertyAccessibility { get; init; } = global::CommunityToolkit.Maui.AccessModifier.Public;
		  	public global::CommunityToolkit.Maui.AccessModifier GetterAccessibility { get; init; } = global::CommunityToolkit.Maui.AccessModifier.Public;
		  	public global::CommunityToolkit.Maui.AccessModifier SetterAccessibility { get; init; } = global::CommunityToolkit.Maui.AccessModifier.Public;
		  }
		  """;

	const string generatedEnumFileName = "AccessModifier.g.cs";
	const string expectedEnum =
		/* language=C#-test */
		//lang=csharp
		$$"""
		  // <auto-generated>
		  // See: CommunityToolkit.Maui.SourceGenerators.Internal.AttachedBindablePropertySourceGenerator

		  #pragma warning disable
		  #nullable enable
		  namespace CommunityToolkit.Maui;

		  public enum AccessModifier
		  {
		  	Public = 0,
		  	Internal = 1,
		  	ProtectedInternal = 2,
		  	Protected = 3,
		  	PrivateProtected = 4,
		  	Private = 5,
		  	None = 6
		  }
		  """;

	protected static Task VerifySourceGeneratorAsync(string source, params List<(string FileName, string GeneratedFile)> expectedGeneratedFilesList)
	{
		expectedGeneratedFilesList.Add((generatedBindablePropertyAttributeFileName, expectedAttribute));
		expectedGeneratedFilesList.Add((generatedEnumFileName, expectedEnum));

		return VerifySourceGeneratorAsync<AttachedBindablePropertyAttributeSourceGenerator>(source, expectedGeneratedFilesList);
	}


	protected static Task VerifySourceGeneratorAsync(string source, string expectedGeneratedFile)
	{
		List<(string FileName, string GeneratedFile)> expectedGeneratedFilesList =
		[
			(generatedBindablePropertyAttributeFileName, expectedAttribute),
			(generatedEnumFileName, expectedEnum),
			($"{defaultTestClassName}.g.cs", expectedGeneratedFile)
		];

		return VerifySourceGeneratorAsync<AttachedBindablePropertyAttributeSourceGenerator>(source, expectedGeneratedFilesList);
	}
}