namespace CommunityToolkit.Maui.SourceGenerators.Internal.UnitTests.AttachedBindablePropertyAttributeSourceGeneratorTests;

public class BaseAttachedBindablePropertyAttributeSourceGeneratorTest : BaseTest
{
	protected const string defaultTestClassName = "TestView";
	protected const string defaultTestNamespace = "TestNamespace";
	protected const string generatedBindablePropertyAttributeFileName = "AttachedBindablePropertyAttribute.g.cs";

	protected const string expectedAttribute =
		/* language=C#-test */
		//lang=csharp
		$$"""
		// <auto-generated>
		  // See: CommunityToolkit.Maui.SourceGenerators.Internal.AttachedBindablePropertySourceGenerator

		  #pragma warning disable
		  #nullable enable
		  namespace CommunityToolkit.Maui;

		  [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
		  [global::System.AttributeUsage(global::System.AttributeTargets.Class | global::System.AttributeTargets.Constructor, AllowMultiple = true, Inherited = false)]
		  [global::System.Diagnostics.CodeAnalysis.Experimental("{{BindablePropertyDiagnostic.BindablePropertyAttributeExperimentalDiagnosticId}}")]
		  sealed partial class AttachedBindablePropertyAttribute<TSourceGenerator>(string propertyName) : global::System.Attribute
		  {
		  	public string? PropertyName { get; } = propertyName;
		  	public global::System.Type? DeclaringType { get; init; }
		  	public global::Microsoft.Maui.Controls.BindingMode DefaultBindingMode { get; init; }
		  	public string ValidateValueMethodName { get; init; } = string.Empty;
		  	public string PropertyChangedMethodName { get; init; } = string.Empty;
		  	public string PropertyChangingMethodName { get; init; } = string.Empty;
		  	public string CoerceValueMethodName { get; init; } = string.Empty;
		  	public string DefaultValueCreatorMethodName { get; init; } = string.Empty;
		  	public global::Microsoft.CodeAnalysis.Accessibility GetterAccessibility { get; init; } = global::Microsoft.CodeAnalysis.Accessibility.Public;
		  	public global::Microsoft.CodeAnalysis.Accessibility SetterAccessibility { get; init; } = global::Microsoft.CodeAnalysis.Accessibility.Public;
		  }
		""";

	protected static Task VerifySourceGeneratorAsync(string source, string expectedAttribute, params List<(string FileName, string GeneratedFile)> expectedGenerated) =>
		VerifySourceGeneratorAsync<AttachedBindablePropertyAttributeSourceGenerator>(source, expectedAttribute, generatedBindablePropertyAttributeFileName, expectedGenerated);


	protected static Task VerifySourceGeneratorAsync(string source, string expectedGenerated) =>
		VerifySourceGeneratorAsync<AttachedBindablePropertyAttributeSourceGenerator>(source, expectedAttribute, generatedBindablePropertyAttributeFileName, ($"{defaultTestClassName}.g.cs", expectedGenerated));
}