using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace CommunityToolkit.Maui.SourceGenerators;

/// <summary>
/// Source generator that detects when Android Foreground Service is enabled for MediaElement
/// and generates the required assembly-level permissions and service attributes.
/// </summary>
[Generator]
public class AndroidMediaElementServiceConfigurationGenerator : IIncrementalGenerator
{
	const string mediaElementOptionsClassName = "MediaElementOptions";
	const string isAndroidForegroundServiceEnabledProperty = "IsAndroidForegroundServiceEnabled";

	public void Initialize(IncrementalGeneratorInitializationContext context)
	{
		// Detect calls to SetDefaultAndroidForegroundServiceEnabled to determine if it's enabled
		var mediaElementProvider = context.SyntaxProvider
			.CreateSyntaxProvider(
				predicate: (syntax, _) => IsMediaElementOptionsClass(syntax) || IsMediaControlsServiceClass(syntax),
				transform: (ctx, _) => GetConfigurationInfo(ctx))
			.Where(info => info is not null)
			.Collect();

		context.RegisterSourceOutput(mediaElementProvider, (spc, configs) =>
		{
			var nonNullConfigs = configs.Where(c => c is not null).Cast<ConfigurationInfo>().ToList();
			if (nonNullConfigs.Any(c => c.IsForegroundServiceEnabled))
			{
				GenerateAndroidPermissionsAndAttributes(spc, nonNullConfigs.First(c => c.IsForegroundServiceEnabled));
			}
		});
	}

	static bool IsMediaElementOptionsClass(SyntaxNode node)
	{
		return node is ClassDeclarationSyntax classDecl &&
			   classDecl.Identifier.Text.Contains(mediaElementOptionsClassName);
	}

	static bool IsMediaControlsServiceClass(SyntaxNode node)
	{
		return node is ClassDeclarationSyntax classDecl &&
			   classDecl.Identifier.Text.Contains("MediaControlsService");
	}

	static ConfigurationInfo? GetConfigurationInfo(GeneratorSyntaxContext context)
	{
		if (context.Node is not ClassDeclarationSyntax classDecl)
		{
			return null;
		}

		var className = classDecl.Identifier.Text;

		if (className.Contains(mediaElementOptionsClassName))
		{
			// Look for the IsAndroidForegroundServiceEnabled property
			var propertyDecl = classDecl.Members
				.OfType<PropertyDeclarationSyntax>()
				.FirstOrDefault(p => p.Identifier.Text == isAndroidForegroundServiceEnabledProperty);

			if (propertyDecl?.Initializer?.Value is null)
			{
				return null;
			}

			// Check if the property is initialized to true
			var isEnabled = propertyDecl.Initializer.Value.Kind() == SyntaxKind.TrueLiteralExpression;

			var semanticModel = context.SemanticModel;
			var symbol = semanticModel.GetDeclaredSymbol(classDecl) as INamedTypeSymbol;

			return new ConfigurationInfo
			{
				ClassName = className,
				Namespace = symbol?.ContainingNamespace.ToDisplayString() ?? "",
				IsForegroundServiceEnabled = isEnabled,
				ClassType = "MediaElementOptions"
			};
		}
		else if (className.Contains("MediaControlsService"))
		{
			var semanticModel = context.SemanticModel;
			var symbol = semanticModel.GetDeclaredSymbol(classDecl) as INamedTypeSymbol;

			return new ConfigurationInfo
			{
				ClassName = className,
				Namespace = symbol?.ContainingNamespace.ToDisplayString() ?? "",
				IsForegroundServiceEnabled = true,
				ClassType = "MediaControlsService"
			};
		}

		return null;
	}

	static void GenerateAndroidPermissionsAndAttributes(SourceProductionContext context, ConfigurationInfo config)
	{
		var sb = new StringBuilder();

		sb.AppendLine("// <auto-generated>");
		sb.AppendLine("// See: CommunityToolkit.Maui.SourceGenerators.AndroidMediaElementServiceConfigurationGenerator");
		sb.AppendLine("// This file provides assembly-level Android permissions and service attributes");
		sb.AppendLine("// when Android Foreground Service is enabled for MediaElement.");
		sb.AppendLine("");
		sb.AppendLine("#pragma warning disable");
		sb.AppendLine("#nullable enable");
		sb.AppendLine("");
		sb.AppendLine("#if ANDROID");
		sb.AppendLine("using Android.App;");
		sb.AppendLine("");
		sb.AppendLine("[assembly: UsesPermission(Android.Manifest.Permission.ForegroundServiceMediaPlayback)]");
		sb.AppendLine("[assembly: UsesPermission(Android.Manifest.Permission.ForegroundService)]");
		sb.AppendLine("[assembly: UsesPermission(Android.Manifest.Permission.MediaContentControl)]");
		sb.AppendLine("[assembly: UsesPermission(Android.Manifest.Permission.PostNotifications)]");
		sb.AppendLine("");
		sb.AppendLine("namespace CommunityToolkit.Maui.Android;");
		sb.AppendLine("");
		sb.AppendLine("/// <summary>");
		sb.AppendLine("/// Auto-generated configuration for Android MediaElement Service.");
		sb.AppendLine("/// </summary>");
		sb.AppendLine("/// <remarks>");
		sb.AppendLine("/// This file is auto-generated and provides assembly-level permissions");
		sb.AppendLine("/// for MediaElement when <see cref=\"CommunityToolkit.Maui.Core.MediaElementOptions.IsAndroidForegroundServiceEnabled\"/> is enabled.");
		sb.AppendLine("/// </remarks>");
		sb.AppendLine("internal static class AndroidMediaElementServiceConfiguration");
		sb.AppendLine("{");
		sb.AppendLine("\t/// <summary>");
		sb.AppendLine("\t/// Indicates that Android MediaElement Service configuration is required.");
		sb.AppendLine("\t/// </summary>");
		sb.AppendLine("\tpublic const bool IsRequired = true;");
		sb.AppendLine("}");
		sb.AppendLine("#endif");

		var source = sb.ToString();
		context.AddSource("AndroidMediaElementServiceConfiguration.g.cs", SourceText.From(source, Encoding.UTF8));

		// Generate service attributes for MediaControlsService
		GenerateServiceAttributes(context);
	}

	static void GenerateServiceAttributes(SourceProductionContext context)
	{
		var sb = new StringBuilder();

		sb.AppendLine("// <auto-generated>");
		sb.AppendLine("// See: CommunityToolkit.Maui.SourceGenerators.AndroidMediaElementServiceConfigurationGenerator");
		sb.AppendLine("// This file provides service attributes for MediaControlsService");
		sb.AppendLine("// when Android Foreground Service is enabled.");
		sb.AppendLine("");
		sb.AppendLine("#pragma warning disable");
		sb.AppendLine("#nullable enable");
		sb.AppendLine("");
		sb.AppendLine("#if ANDROID");
		sb.AppendLine("using Android.App;");
		sb.AppendLine("using Android.Content.PM;");
		sb.AppendLine("");
		sb.AppendLine("namespace CommunityToolkit.Maui.Media.Services;");
		sb.AppendLine("");
		sb.AppendLine("/// <summary>");
		sb.AppendLine("/// Partial class providing generated attributes for MediaControlsService");
		sb.AppendLine("/// </summary>");
		sb.AppendLine("[IntentFilter([\"androidx.media3.session.MediaSessionService\"])]");
		sb.AppendLine("[Service(Exported = false, Enabled = true, Name = \"communityToolkit.maui.media.services\", ForegroundServiceType = ForegroundService.TypeMediaPlayback)]");
		sb.AppendLine("partial class MediaControlsService");
		sb.AppendLine("{");
		sb.AppendLine("}");
		sb.AppendLine("#endif");

		var source = sb.ToString();
		context.AddSource("MediaControlsService.Attributes.g.cs", SourceText.From(source, Encoding.UTF8));
	}

	sealed class ConfigurationInfo
	{
		public string? ClassName { get; set; }
		public string? Namespace { get; set; }
		public bool IsForegroundServiceEnabled { get; set; }
		public string? ClassType { get; set; }
	}
}
