// CommunityToolkit.Maui.Analyzers/EnumDescriptionGenerator.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

using CommunityToolkit.Maui.SourceGenerators.Helpers;
using CommunityToolkit.Maui.SourceGenerators.Models;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace CommunityToolkit.Maui.Analyzers;

[Generator]
public class EnumDescriptionGenerator : IIncrementalGenerator
{
	// Using fields instead of const to avoid naming rule violations
	static readonly string displayAttributeName = "System.ComponentModel.DataAnnotations.DisplayAttribute";
	static readonly string descriptionAttributeName = "System.ComponentModel.DescriptionAttribute";

   static EnumDescriptionModel? CreateEnumDescriptionModel(INamedTypeSymbol? enumSymbol)
   {
	   if (enumSymbol is null || enumSymbol.TypeKind != TypeKind.Enum || !EnumDescriptionGeneratorHelper.IsAccessibleFromNamespace(enumSymbol))
	   {
		   return null;
	   }

	   string ns = enumSymbol.ContainingNamespace.ToDisplayString();
	   string enumName = enumSymbol.Name;
	   string enumQualifiedName = enumSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

	   var members = new List<EnumMemberModel>();
	   foreach (IFieldSymbol member in enumSymbol.GetMembers().OfType<IFieldSymbol>())
	   {
		   if (member.ConstantValue is null)
		   {
			   continue;
		   }

		   string? description = EnumDescriptionGeneratorHelper.GetDescriptionFromDescriptionAttribute(member, descriptionAttributeName);
		   string? displayName = null;
		   string? resourceType = null;
		   if (EnumDescriptionGeneratorHelper.TryGetDisplayInfo(member, displayAttributeName, out var dn, out var rt))
		   {
			   displayName = dn;
			   resourceType = rt?.ToDisplayString();
		   }

		   members.Add(new EnumMemberModel(
			   member.Name,
			   description,
			   displayName,
			   resourceType
		   ));
	   }

	   return new EnumDescriptionModel(enumName, ns, enumQualifiedName, members);
   }

	public void Initialize(IncrementalGeneratorInitializationContext context)
	{
       IncrementalValuesProvider<EnumDescriptionModel?> enumModels = context.SyntaxProvider
		   .CreateSyntaxProvider(
			   predicate: static (node, _) => node is EnumDeclarationSyntax,
			   transform: static (ctx, _) => EnumDescriptionGenerator.CreateEnumDescriptionModel(ctx.SemanticModel.GetDeclaredSymbol(ctx.Node) as INamedTypeSymbol))
		   .Where(static model => model is not null);

       context.RegisterSourceOutput(enumModels, (spc, model) =>
	   {
		   if (model is null)
		   {
			   return;
		   }

		   string code = GenerateCode(model);
		   string hintName = $"{model.QualifiedName.Replace(".", "_")}.g.cs";
		   spc.AddSource(hintName, SourceText.From(code, Encoding.UTF8));
	   });
	}

   static string GenerateCode(EnumDescriptionModel model)
	{
       string ns = model.Namespace;
	   string enumName = model.EnumName;
	   string enumQualifiedName = model.QualifiedName;
	   // Remove 'global::' prefix if present
	   string cleanedQualifiedName = enumQualifiedName.StartsWith("global::", StringComparison.Ordinal)
		   ? enumQualifiedName.Substring(8)
		   : enumQualifiedName;
	   // Replace invalid characters for identifiers
	   string baseClassName = cleanedQualifiedName.Replace(".", "_").Replace("+", "_");
	   string initializerClassName = $"{baseClassName}_DescriptionInitializer";

		var sb = new StringBuilder();
		sb.AppendLine("// <auto-generated />");
		sb.AppendLine("#nullable enable");
		sb.AppendLine("using CommunityToolkit.Maui.Converters;");
		sb.AppendLine();

		if (!string.IsNullOrEmpty(ns))
		{
			sb.AppendLine($"namespace {ns};");
			sb.AppendLine();
		}

		sb.AppendLine($"internal static class {initializerClassName}");
		sb.AppendLine("{");
		sb.AppendLine("    [global::System.Runtime.CompilerServices.ModuleInitializer]");
		sb.AppendLine("    internal static void Initialize()");
		sb.AppendLine("    {");
		sb.AppendLine("        var dict = new global::System.Collections.Generic.Dictionary<string, string>();");
		sb.AppendLine("        var resolvers = new global::System.Collections.Generic.Dictionary<string, global::System.Func<global::System.Globalization.CultureInfo?, string>>();");

       foreach (var member in model.Members)
	   {
		   string fallbackDescription = member.Description ?? member.Name;
		   if (member.DisplayName is not null && !string.IsNullOrWhiteSpace(member.DisplayName))
		   {
			   if (member.ResourceType is not null)
			   {
				   // Cannot safely resolve localized resource access at compile-time
				   sb.AppendLine($"        dict[\"{member.Name}\"] = \"{EnumDescriptionGeneratorHelper.EscapeString(fallbackDescription)}\";");
				   continue;
			   }
			   sb.AppendLine($"        dict[\"{member.Name}\"] = \"{EnumDescriptionGeneratorHelper.EscapeString(member.DisplayName)}\";");
			   continue;
		   }
		   sb.AppendLine($"        dict[\"{member.Name}\"] = \"{EnumDescriptionGeneratorHelper.EscapeString(fallbackDescription)}\";");
	   }

		sb.AppendLine();
		sb.AppendLine($"        EnumDescriptionRegistry.Register(typeof({enumQualifiedName}), dict);");
		sb.AppendLine("        if (resolvers.Count > 0)");
		sb.AppendLine("        {");
		sb.AppendLine($"            EnumDescriptionRegistry.Register(typeof({enumQualifiedName}), resolvers);");
		sb.AppendLine("        }");
		sb.AppendLine("    }");
		sb.AppendLine("}");

		return sb.ToString();
	}

}