// CommunityToolkit.Maui.Analyzers/EnumDescriptionGenerator.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace CommunityToolkit.Maui.Analyzers;

[Generator]
public class EnumDescriptionGenerator : IIncrementalGenerator
{
	// Using fields instead of const to avoid naming rule violations
	static readonly string displayAttributeName = "System.ComponentModel.DataAnnotations.DisplayAttribute";
	static readonly string descriptionAttributeName = "System.ComponentModel.DescriptionAttribute";

	public void Initialize(IncrementalGeneratorInitializationContext context)
	{
		IncrementalValuesProvider<INamedTypeSymbol?> enumDeclarations = context.SyntaxProvider
			.CreateSyntaxProvider(
				predicate: static (node, _) => node is EnumDeclarationSyntax,
				transform: static (ctx, _) => ctx.SemanticModel.GetDeclaredSymbol(ctx.Node) as INamedTypeSymbol)
         .Where(static enumSymbol => enumSymbol?.TypeKind == TypeKind.Enum)
			.Where(static enumSymbol => enumSymbol is not null && IsAccessibleFromNamespace(enumSymbol));

		context.RegisterSourceOutput(enumDeclarations, static (spc, enumSymbol) =>
		{
			if (enumSymbol is null)
			{
				return;
			}

			string code = GenerateCode(enumSymbol);
			string hintName = $"{enumSymbol.ToDisplayString().Replace(".", "_")}.g.cs";
			spc.AddSource(hintName, SourceText.From(code, Encoding.UTF8));
		});
	}

	static string GenerateCode(INamedTypeSymbol enumSymbol)
	{
		string ns = enumSymbol.ContainingNamespace.ToDisplayString();
		string enumName = enumSymbol.Name;
		string enumQualifiedName = enumSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
		string initializerClassName = $"{enumName}DescriptionInitializer_{GetStableHash(enumQualifiedName)}";

		var sb = new StringBuilder();
		sb.AppendLine("// <auto-generated />");
		sb.AppendLine("#nullable enable");
       sb.AppendLine("using CommunityToolkit.Maui.Converters;");
		sb.AppendLine();

		if (!string.IsNullOrEmpty(ns))
		{
			sb.AppendLine($"namespace {ns};");
			sb.AppendLine();
		}

      sb.AppendLine($"internal static class {initializerClassName}");
		sb.AppendLine("{");
      sb.AppendLine("    [global::System.Runtime.CompilerServices.ModuleInitializer]");
		sb.AppendLine("    internal static void Initialize()");
		sb.AppendLine("    {");
		sb.AppendLine("        var dict = new global::System.Collections.Generic.Dictionary<string, string>();");
		sb.AppendLine("        var resolvers = new global::System.Collections.Generic.Dictionary<string, global::System.Func<global::System.Globalization.CultureInfo?, string>>();");

		foreach (IFieldSymbol member in enumSymbol.GetMembers().OfType<IFieldSymbol>())
		{
			if (member.ConstantValue is null)
			{
				continue;
			}

            string? descriptionFromDescriptionAttribute = GetDescriptionFromDescriptionAttribute(member);
			string fallbackDescription = descriptionFromDescriptionAttribute ?? member.Name;

            if (TryGetDisplayInfo(member, out var displayName, out var resourceType)
				&& displayName is not null
				&& !string.IsNullOrWhiteSpace(displayName))
			{
               if (resourceType is not null)
				{
                    // displayName is checked for null above
					if (TryGetLocalizedDisplayResolverExpression(resourceType, displayName!, enumSymbol.ContainingAssembly, out var localizedExpression))
					{
						sb.AppendLine($"        resolvers[\"{member.Name}\"] = static culture =>");
						sb.AppendLine("        {");
						sb.AppendLine($"            var text = {localizedExpression};");
						sb.AppendLine($"            return global::System.String.IsNullOrWhiteSpace(text) ? \"{EscapeString(fallbackDescription)}\" : text;");
						sb.AppendLine("        };");
						continue;
					}

					// Cannot safely resolve localized resource access at compile-time
					sb.AppendLine($"        dict[\"{member.Name}\"] = \"{EscapeString(fallbackDescription)}\";");
					continue;
				}

               sb.AppendLine($"        dict[\"{member.Name}\"] = \"{EscapeString(displayName!)}\";");
				continue;
			}

			sb.AppendLine($"        dict[\"{member.Name}\"] = \"{EscapeString(fallbackDescription)}\";");
		}

		sb.AppendLine();
       sb.AppendLine($"        EnumDescriptionRegistry.Register(typeof({enumQualifiedName}), dict);");
		sb.AppendLine("        if (resolvers.Count > 0)");
		sb.AppendLine("        {");
		sb.AppendLine($"            EnumDescriptionRegistry.Register(typeof({enumQualifiedName}), resolvers);");
		sb.AppendLine("        }");
		sb.AppendLine("    }");
		sb.AppendLine("}");

		return sb.ToString();
	}

   static string? GetDescriptionFromDescriptionAttribute(IFieldSymbol member)
	{
     // Check for DescriptionAttribute
		AttributeData? descAttr = member.GetAttributes()
			.FirstOrDefault(attr => attr.AttributeClass?.ToDisplayString() == descriptionAttributeName);

		if (descAttr is not null && descAttr.ConstructorArguments.Length > 0)
		{
         if (descAttr.ConstructorArguments[0].Value is string description && !string.IsNullOrWhiteSpace(description))
			{
             return description;
			}
		}

     return null;
	}

	static bool TryGetDisplayInfo(IFieldSymbol member, out string? displayName, out INamedTypeSymbol? resourceType)
	{
		displayName = null;
		resourceType = null;

		AttributeData? displayAttr = member.GetAttributes()
			.FirstOrDefault(attr => attr.AttributeClass?.ToDisplayString() == displayAttributeName);

		if (displayAttr is null)
		{
			return false;
		}

		foreach (KeyValuePair<string, TypedConstant> namedArg in displayAttr.NamedArguments)
		{
			if (namedArg.Key == "Name" && !namedArg.Value.IsNull && namedArg.Value.Value is string name)
			{
				displayName = name;
			}
			else if (namedArg.Key == "ResourceType" && !namedArg.Value.IsNull && namedArg.Value.Value is INamedTypeSymbol namedType)
			{
				resourceType = namedType;
			}
			else if (namedArg.Key == "ResourceType" && !namedArg.Value.IsNull && namedArg.Value.Value is ITypeSymbol typeSymbol && typeSymbol is INamedTypeSymbol resourceNamedType)
			{
				resourceType = resourceNamedType;
			}
		}

		return true;
	}

	static bool TryGetLocalizedDisplayResolverExpression(INamedTypeSymbol resourceType, string resourceKey, IAssemblySymbol targetAssembly, out string expression)
	{
		expression = string.Empty;

		if (TryGetResourceManagerExpression(resourceType, resourceKey, targetAssembly, out var resourceManagerExpression))
		{
			expression = resourceManagerExpression;
			return true;
		}

		if (SyntaxFacts.IsValidIdentifier(resourceKey)
			&& TryGetResourceMemberExpression(resourceType, resourceKey, targetAssembly, out var resourceMemberExpression))
		{
			expression = resourceMemberExpression;
			return true;
		}

		return false;
	}

	static bool TryGetResourceManagerExpression(INamedTypeSymbol resourceType, string resourceKey, IAssemblySymbol targetAssembly, out string expression)
	{
		expression = string.Empty;

		IPropertySymbol? resourceManagerProperty = resourceType
			.GetMembers("ResourceManager")
			.OfType<IPropertySymbol>()
			.FirstOrDefault(static p => p.IsStatic && p.GetMethod is not null);

		if (resourceManagerProperty is null || !IsAccessibleToAssembly(resourceManagerProperty, targetAssembly))
		{
			return false;
		}

		if (resourceManagerProperty.Type.ToDisplayString() != "System.Resources.ResourceManager")
		{
			return false;
		}

      var resourceTypeName = resourceType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
		expression = $"{resourceTypeName}.ResourceManager.GetString(\"{EscapeString(resourceKey)}\", culture ?? global::System.Globalization.CultureInfo.CurrentUICulture)";
		return true;
	}

	static bool TryGetResourceMemberExpression(INamedTypeSymbol resourceType, string resourceKey, IAssemblySymbol targetAssembly, out string expression)
	{
		expression = string.Empty;

		IPropertySymbol? property = resourceType.GetMembers(resourceKey).OfType<IPropertySymbol>()
			.FirstOrDefault(static p => p.IsStatic && p.GetMethod is not null);

		if (property is not null)
		{
			if (property.Type.SpecialType == SpecialType.System_String && IsAccessibleToAssembly(property, targetAssembly))
			{
				var resourceTypeName = resourceType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
               expression = $"{resourceTypeName}.{resourceKey}";
				return true;
			}

			return false;
		}

		IFieldSymbol? field = resourceType.GetMembers(resourceKey).OfType<IFieldSymbol>()
			.FirstOrDefault(static f => f.IsStatic);

		if (field is not null && field.Type.SpecialType == SpecialType.System_String && IsAccessibleToAssembly(field, targetAssembly))
		{
			var resourceTypeName = resourceType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
           expression = $"{resourceTypeName}.{resourceKey}";
			return true;
		}

		return false;
	}

	static bool IsAccessibleToAssembly(ISymbol symbol, IAssemblySymbol targetAssembly)
		=> symbol.DeclaredAccessibility switch
		{
			Accessibility.Public => true,
			Accessibility.Internal or Accessibility.ProtectedOrInternal => SymbolEqualityComparer.Default.Equals(symbol.ContainingAssembly, targetAssembly),
			_ => false
		};

	static string EscapeString(string input)
	{
		return input.Replace("\\", "\\\\")
				   .Replace("\"", "\\\"")
				   .Replace("\n", "\\n")
				   .Replace("\r", "\\r")
				   .Replace("\t", "\\t");
	}

	static string GetStableHash(string value)
	{
		unchecked
		{
			uint hash = 2166136261;
			foreach (char c in value)
			{
				hash ^= c;
				hash *= 16777619;
			}

			return hash.ToString("x8", System.Globalization.CultureInfo.InvariantCulture);
		}
	}

	static bool IsAccessibleFromNamespace(INamedTypeSymbol enumSymbol)
	{
		if (!IsTypeAccessible(enumSymbol))
		{
			return false;
		}

		INamedTypeSymbol? containingType = enumSymbol.ContainingType;
		while (containingType is not null)
		{
			if (!IsTypeAccessible(containingType))
			{
				return false;
			}

			containingType = containingType.ContainingType;
		}

		return true;
	}

	static bool IsTypeAccessible(INamedTypeSymbol typeSymbol)
		=> typeSymbol.DeclaredAccessibility is Accessibility.Public or Accessibility.Internal or Accessibility.ProtectedOrInternal;
}