// CommunityToolkit.Maui.Analyzers/EnumDescriptionGenerator.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

using CommunityToolkit.Maui.SourceGenerators.Helpers;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace CommunityToolkit.Maui.Analyzers;

[Generator]
public class EnumDescriptionGenerator : IIncrementalGenerator
{
	// Using fields instead of const to avoid naming rule violations
	static readonly string displayAttributeName = "System.ComponentModel.DataAnnotations.DisplayAttribute";
	static readonly string descriptionAttributeName = "System.ComponentModel.DescriptionAttribute";

	public void Initialize(IncrementalGeneratorInitializationContext context)
	{
		IncrementalValuesProvider<INamedTypeSymbol?> enumDeclarations = context.SyntaxProvider
			.CreateSyntaxProvider(
				predicate: static (node, _) => node is EnumDeclarationSyntax,
				transform: static (ctx, _) => ctx.SemanticModel.GetDeclaredSymbol(ctx.Node) as INamedTypeSymbol)
		 .Where(static enumSymbol => enumSymbol?.TypeKind == TypeKind.Enum)
			.Where(static enumSymbol => enumSymbol is not null && EnumDescriptionGeneratorHelper.IsAccessibleFromNamespace(enumSymbol));

		context.RegisterSourceOutput(enumDeclarations, static (spc, enumSymbol) =>
		{
			if (enumSymbol is null)
			{
				return;
			}

			string code = GenerateCode(enumSymbol);
			string hintName = $"{enumSymbol.ToDisplayString().Replace(".", "_")}.g.cs";
			spc.AddSource(hintName, SourceText.From(code, Encoding.UTF8));
		});
	}

	static string GenerateCode(INamedTypeSymbol enumSymbol)
	{
		string ns = enumSymbol.ContainingNamespace.ToDisplayString();
		string enumName = enumSymbol.Name;
		string enumQualifiedName = enumSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
		// Remove 'global::' prefix if present
		string cleanedQualifiedName = enumQualifiedName.StartsWith("global::", StringComparison.Ordinal)
			? enumQualifiedName.Substring(8)
			: enumQualifiedName;
		// Replace invalid characters for identifiers
		string baseClassName = cleanedQualifiedName.Replace(".", "_").Replace("+", "_");
		string initializerClassName = $"{baseClassName}_DescriptionInitializer";

		var sb = new StringBuilder();
		sb.AppendLine("// <auto-generated />");
		sb.AppendLine("#nullable enable");
		sb.AppendLine("using CommunityToolkit.Maui.Converters;");
		sb.AppendLine();

		if (!string.IsNullOrEmpty(ns))
		{
			sb.AppendLine($"namespace {ns};");
			sb.AppendLine();
		}

		sb.AppendLine($"internal static class {initializerClassName}");
		sb.AppendLine("{");
		sb.AppendLine("    [global::System.Runtime.CompilerServices.ModuleInitializer]");
		sb.AppendLine("    internal static void Initialize()");
		sb.AppendLine("    {");
		sb.AppendLine("        var dict = new global::System.Collections.Generic.Dictionary<string, string>();");
		sb.AppendLine("        var resolvers = new global::System.Collections.Generic.Dictionary<string, global::System.Func<global::System.Globalization.CultureInfo?, string>>();");

		foreach (IFieldSymbol member in enumSymbol.GetMembers().OfType<IFieldSymbol>())
		{
			if (member.ConstantValue is null)
			{
				continue;
			}





			string? descriptionFromDescriptionAttribute = EnumDescriptionGeneratorHelper.GetDescriptionFromDescriptionAttribute(member, descriptionAttributeName);
			string fallbackDescription = descriptionFromDescriptionAttribute ?? member.Name;

			if (EnumDescriptionGeneratorHelper.TryGetDisplayInfo(member, displayAttributeName, out var displayName, out var resourceType)
				&& displayName is not null
				&& !string.IsNullOrWhiteSpace(displayName))
			{
				if (resourceType is not null)
				{
					// displayName is checked for null above
					if (EnumDescriptionGeneratorHelper.TryGetLocalizedDisplayResolverExpression(resourceType, displayName!, enumSymbol.ContainingAssembly, out var localizedExpression))
					{
						sb.AppendLine($"        resolvers[\"{member.Name}\"] = static culture =>");
						sb.AppendLine("        {");
						sb.AppendLine($"            var text = {localizedExpression};");
						sb.AppendLine($"            return global::System.String.IsNullOrWhiteSpace(text) ? \"{EnumDescriptionGeneratorHelper.EscapeString(fallbackDescription)}\" : text;");
						sb.AppendLine("        };");
						continue;
					}

					// Cannot safely resolve localized resource access at compile-time
					sb.AppendLine($"        dict[\"{member.Name}\"] = \"{EnumDescriptionGeneratorHelper.EscapeString(fallbackDescription)}\";");
					continue;
				}

				sb.AppendLine($"        dict[\"{member.Name}\"] = \"{EnumDescriptionGeneratorHelper.EscapeString(displayName!)}\";");
				continue;
			}

			sb.AppendLine($"        dict[\"{member.Name}\"] = \"{EnumDescriptionGeneratorHelper.EscapeString(fallbackDescription)}\";");
		}

		sb.AppendLine();
		sb.AppendLine($"        EnumDescriptionRegistry.Register(typeof({enumQualifiedName}), dict);");
		sb.AppendLine("        if (resolvers.Count > 0)");
		sb.AppendLine("        {");
		sb.AppendLine($"            EnumDescriptionRegistry.Register(typeof({enumQualifiedName}), resolvers);");
		sb.AppendLine("        }");
		sb.AppendLine("    }");
		sb.AppendLine("}");

		return sb.ToString();
	}

}