namespace CommunityToolkit.Maui.MediaView;

/// <summary>
/// This class contains MediaView's <see cref="MauiAppBuilder"/> extensions.
/// </summary>
public static class AppBuilderExtensions
{
	/// <summary>
	/// Initializes the .NET MAUI Community Toolkit MediaView Library
	/// </summary>
	/// <param name="builder"><see cref="MauiAppBuilder"/> generated by <see cref="MauiApp"/>.</param>
	/// <returns><see cref="MauiAppBuilder"/> initialized for <see cref="MediaView"/>.</returns>
	public static MauiAppBuilder UseMauiCommunityToolkitMediaView(this MauiAppBuilder builder)
	{
		builder.ConfigureMauiHandlers(h =>
		{
			h.AddHandler<MediaView, MediaViewHandler>();
		});

		return builder;
	}
}