using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CommunityToolkit.Maui.Maps;

public static class AppHostBuilderExtensions
{
	/// <summary>
	/// Initializes the .NET MAUI Community Toolkit Maps Library
	/// </summary>
	/// <param name="builder"><see cref="MauiAppBuilder"/> generated by <see cref="MauiApp"/> </param>
	/// <returns><see cref="MauiAppBuilder"/> initialized for <see cref="CommunityToolkit.Maui.Core"/></returns>
	public static MauiAppBuilder UseMauiCommunityToolkitMaps(this MauiAppBuilder builder)
	{

		builder
		.ConfigureMauiHandlers(handlers =>
		{
			handlers.AddMauiCommunityToolkitMaps();
		});

		return builder;
	}


	public static IMauiHandlersCollection AddMauiCommunityToolkitMaps(this IMauiHandlersCollection handlersCollection)
	{
		handlersCollection.AddHandler<Map, MapHandler>();

		return handlersCollection;
	}
}
