namespace CommunityToolkit.Maui.Maps;

/// <summary>
/// Maps Extensions for <see cref="MauiAppBuilder"/>
/// </summary>
public static class AppHostBuilderExtensions
{
	/// <summary>
	/// Initializes the .NET MAUI Community Toolkit Maps Library
	/// </summary>
	/// <param name="builder"><see cref="MauiAppBuilder"/> generated by <see cref="MauiApp"/> </param>
	/// <param name="key"></param>
	/// <returns><see cref="MauiAppBuilder"/></returns>
	public static MauiAppBuilder UseMauiCommunityToolkitMaps(this MauiAppBuilder builder, string key)
	{
		builder.ConfigureMauiHandlers(handlers =>
		{
#if WINDOWS
			CommunityToolkit.Maui.Maps.Handlers.MapHandlerWindows.MapsKey = key;
			handlers.AddHandler<Microsoft.Maui.Controls.Maps.Map, CommunityToolkit.Maui.Maps.Handlers.MapHandlerWindows>();
#endif
		});

		return builder;
	}
}