namespace CommunityToolkit.Maui.Sample.Resources.Fonts;

/// <summary>
/// The unicode values for all FontAwesome v6.1.1 icons.
/// <para/>
/// See https://fontawesome.com/cheatsheet
/// <remark>This code was automatically generated by FA2CS (https://github.com/matthewrdev/fa2cs).</remark>
/// </summary>
public static class FontAwesomeIcons
{
	/// <summary>
	/// fa-microsoft unicode value ("\uf3ca").
	/// <para/>
	/// This icon supports the following styles: Brands
	/// <para/>
	/// Introduced in '5.0.0', Last Modified in '5.0.0'.
	/// <para/>
	/// See https://fontawesome.com/icons/microsoft
	/// </summary>
	public const string Microsoft = "\uf3ca";
}